### ISSUE TITLE
Quarto is installed newest version, but Rstudio cannot recognize

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#10030]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  2022.01.1 Build 175
    OS Version      :  Window 11
    R Version       :  4.1

### Describe the problem in detail
I have tried to installed newest version of Rstudio and Quarto many times but still constantly occur with this problem, specifying in the picture below:
![image](https://user-images.githubusercontent.com/63569637/139580988-937c2ee9-a438-47eb-8343-a6ac974f9e6d.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ntluong95 Thank you for raising this! I'll mark this for review as we continue to develop RStudio and its support of Quarto.

**Comment by mikebessuille** [comment]
@dragonstyle could this be due to Windows 11?

**Comment by dragonstyle** [comment]
@ntluong95 There was an issue in earlier daily builds with identifying the proper Quarto path on Windows (this is resulting in the version number that is detected not displaying properly in the warning message that you shared). We have fixed that issue, so if you update to the latest RStudio daily build, you should see a proper warning message (if the warning still applies). 

Thanks for reporting this!

**Comment by sammo3182** [comment]
Dear Rstudio team, this problem may still exist. I used daily builds of Rstudio desktop (in Win 11) and stable Rstudio server (in Linux Ubuntu) and both cannot recognize a newer version of Quarto well. I posted a [relevant issue](https://github.com/quarto-dev/quarto-r/issues/23) with more details in the quarto-r repo. Hope this can be solved soon.

**Comment by ronblum** [comment]
@sammo3182 Thanks for the info! I'll try to reproduce—can you give me the version numbers of RStudio Desktop and Quarto that you're using? Including both `quarto::quarto_version()` (RStudio console) and `quarto --version` (command line).

**Comment by sammo3182** [comment]
Sure, @ronblum. I'm using RStudio Server 2022.02.2 Build 485 on Linux and Rstudio desktop 2022.11.0 Build 73 on Windows. I guess it might be the build-in quarto in Rstudio that causes the problem.

```r
> quarto::quarto_version()
[1] ‘0.9.640’
```


```
~$ quarto --version
99.9.9
```

**Comment by ronblum** [comment]
That's interesting: I'm looking back at RStudio Desktop dailies and release candidates from RStudio Desktop 2022.02.2 and 2022.07.0:
- RStudio Desktop 2022.02.2+485 included Quarto 0.9.80
- RStudio Desktop 2022.07.0+547 included Quarto 0.9.634
- RStudio Desktop 2022.07.0+548 included Quarto 0.9.649

1) Did you by chance at some point install the Quarto CLI at some point, instead of building it?
2) Can you also check `quarto:quarto_path` and can you run all of these on both the RStudio Desktop and RStudio Server instances?

I haven't checked RStudio Server yet—focussing on RStudio Desktop first. Here's what I get on Windows when I run the following in desktop version 2022.11.0-daily+73, in which the bundled version of Quarto should be 1.0.32.
```
RStudio.Version()$long_version
quarto::quarto_version()
quarto::quarto_path()
```

Results:
```
> RStudio.Version()$long_version
[1] "2022.11.0-daily+73"
> quarto::quarto_version()
[1] '1.0.32'
> quarto::quarto_path()
[1] "C:\\PROGRA~1\\RStudio\\RESOUR~1\\app\\bin\\quarto\\bin\\quarto.cmd"
```

**Comment by sammo3182** [comment]
Ron  @ronblum , sorry for the late reply! I actually cannot show you the above because, a while ago, I needed Quarto to work so I manually copy the installed Quarto CLI to the Rstudio folder (I know it's risky, but it works anyway). What I can show is that, after my manual fixing, Rstudio recognizes the quarto `1.0.36`. But when I install the 1.0.37 version at `D:\Program Files\Quarto` in my Win 11, and Rstudio cannot recognize that but the previous `1.0.36`:

```r
> RStudio.Version()$long_version
[1] "2022.07.1+554"
> quarto::quarto_version()
[1] ‘1.0.36’
> quarto::quarto_path()
[1] "D:\\R\\RStudio\\bin\\quarto\\bin\\quarto.cmd"
```

So I have to install it to the "Rstudio" bin to make it work---like every time I update Rstudio? You are right. I do not "build" the quarto cli but merely install it. Isn't that what quarto.org instructs? I don't see a building 
phase there in the tutorial. Sorry if I misunderstand the guidance of quarto instruction.

**Comment by ronblum** [comment]
@sammo3182 no problem! I wonder if something got messed up because of the previous installations of the Quarto CLI to the RStudio directory. Let's see what the environment says:

1) In the RStudio Console Pane, which Quarto executable(s) does `Sys.which("quarto")` show?
2) In the RStudio Console Pane, does `Sys.getenv("PATH")` include the directory in which Quarto is installed?  
3) In the Windows command line, what do you get with `where quarto`?

**Comment by sammo3182** [comment]
@ronblum Ron, you're right. The Rstudio only recognizes its own quarto and the path of stand-alone installation of Quarto was not in the environment. It looks like the installed file does not automatically add the info to the environment (at least in Windows). If the users should add by themselves, it may need to be written in the instruction. Or, of course, a more convenient way is to let the installation automatically do it. I know it sounds like an issue for the Quarto group, not Rstudio. Should I submit a request to Quarto, then? On the other hand, it would be very convenient if there's a way to install AND update Qurato in Rstudio

**Comment by dongericoyu** [comment]
> @ronblum Ron, you're right. The Rstudio only recognizes its own quarto and the path of stand-alone installation of Quarto was not in the environment. It looks like the installed file does not automatically add the info to the environment (at least in Windows). If the users should add by themselves, it may need to be written in the instruction. Or, of course, a more convenient way is to let the installation automatically do it. I know it sounds like an issue for the Quarto group, not Rstudio. Should I submit a request to Quarto, then? On the other hand, it would be very convenient if there's a way to install AND update Qurato in Rstudio

Hi sammo, have you resolved the issue of recognizing Quarto in Rstudio? I am setting up my Windows 11 PC with the latest daily built Rstudio and still run into the same issue. Any new insight?
