### ISSUE TITLE
Find in Files has inconsistent behavior searching projects

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#10134]
### System details

    RStudio Edition : Server only
    RStudio Version : 2021.09.1+372
    OS Version      : n/a
    R Version       : n/a

### Steps to reproduce the problem
1. File -> New Project -> Version Control -> Git -> Repository Url: https://github.com/juliasilge/juliasilge.com
2. Bring up Find in Files (cmd + shift + F on mac or Edit -> Find in Files)
3. Search for any text that exists in the repository (e.g. ggplot)
4. Find in Files tab displays "No results found"

### Describe the problem in detail
Starting in 2021.09.1, certain projects will not yield any results when searched with Find in Files. If you close the project, then search the directory that contains the project, Find in Files returns the expected results.

Based on my brief investigation, I believe the bug is related to https://github.com/rstudio/rstudio/commit/fde2859fbdf6be4b75f63435e5403a424758caa4 and this code:
https://github.com/rstudio/rstudio/blob/a221a537c36b810f78b2e5ae72bb6cf80f99600e/src/cpp/session/modules/SessionFind.cpp#L939

which for certain website projects, adds the full project to the ignore directory list: 
https://github.com/rstudio/rstudio/blob/a221a537c36b810f78b2e5ae72bb6cf80f99600e/src/cpp/session/SessionModuleContext.cpp#L2922

This came up in this support ticket: https://rstudioide.zendesk.com/agent/tickets/68783 and is a regression in the Ghost Orchid patch.

### Describe the behavior you expected

Searching for words with find in files should work for all projects. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@jjallaire , is this urgent for Prairie Trillium?

**Comment by jjallaire** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/0708075ab8600db2689b2d0f1953f378cb183fa7

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2022.02.0+364 on MacOS 12.1
- RStudio Server 2022.02.0+364 on Ubuntu 20.04 via Chrome on MacOS 12.1

using the example above, cloning https://github.com/juliasilge/juliasilge.com. (I tried creating a simpler reprex, but this ended up being fast and reliable).

**Comment by oguchihy** [comment]
March 9 2022: Problem persists.  RStudio 2021.09.0 Build 351

Any solution(s) yet?

**Comment by melissa-barca** [comment]
@oguchihy This has been fixed in our latest release 2022.02.0+443 which is available for download here: https://www.rstudio.com/products/rstudio/download/#download
