### ISSUE TITLE
Spellcheck in Portuguese

### ISSUE THREAD

**Issue by rll307** [rstudio/rstudio#10442]
I am using **R-Studio 2021.09.2 Build 382** in a **MaOS running Monterey (12.1)**. I have had some trouble running a spelling check in Brazilian Portuguese while editing a *.Rmd file.

I have already set the locale in R-studio using:
```
Sys.setlocale(category = "LC_ALL", locale = "pt_BR.UTF-8")
Sys.getlocale()
[1] "pt_BR.UTF-8/pt_BR.UTF-8/pt_BR.UTF-8/C/pt_BR.UTF-8/en_US.UTF-8"
```
I have also changed the language for the spell check in the preferences:
![Screenshot 2022-01-26 at 12 45 40](https://user-images.githubusercontent.com/14953924/151239861-79014a95-c216-44f1-acba-0e79729d7877.png)

But, as the image bellow shows:

1. Almost every word in the text is marked as misspelled
2. The menu suggested a word with character encoding problem.

![Screenshot 2022-01-26 at 12 59 47](https://user-images.githubusercontent.com/14953924/151239997-826d8758-a64c-477e-97f7-fcdec2fbc835.png)

I had had some problems with Portuguese spellchecking in the past. It seems a problem pups up each new version.

**Comment by ronblum** [comment]
@rll307 Thank you for raising this problem! I can reproduce it in several languages, as well—I managed to run into an issue with Portuguese (Brazil), Portuguese (Portugal), German (New), and English (US). I can't figure out the pattern yet, and this is going back until at least 1.4.1717-3, even though it worked properly then. I'm testing to see if it's operating system-specific. A few questions:
1) What happens if you close and reopen the file? I've found that when I do that, realtime spellchecking works—until I try changing languages again.
2) What happens with the spellchecker using <kbd>Edit -> Check Spelling</kbd>?
3) By chance did you use a previous version of MacOS, like 11 or 10.15, and if so, did it work then?

**Comment by rll307** [comment]
@ronblum Thank you for your answer. Here follows m contribution:

> What happens if you close and reopen the file? I've found that when I do that, realtime spellchecking works—until I try changing languages again

I my case it does not make a difference. I tried:
1. Reopening the file
2. Quitting and reopening RStudio
2. Uninstalling and reinstalling the dictionaries
3. Uninstalling and reinstalling RStudio

None of these seem to work unfortunately. 

> What happens with the spellchecker using Edit -> Check Spelling?

It seems to run the same error. Here follows an image:

![Screenshot 2022-01-26 at 22 25 04](https://user-images.githubusercontent.com/14953924/151274804-c0deb322-7b76-45b1-9551-c70c557dede8.png)

> By chance did you use a previous version of MacOS, like 11 or 10.15, and if so, did it work then?

It used to work on version 11 with no issues. 

I hope it helps.

**Comment by dpprdan** [comment]
This is probably related to #8147, i.e. the wrong encoding is declared for in the .aff files.

**Comment by baarthur** [comment]
Hi,

I tried doing that and it didn't work for me.  Spellcheck doesn't recognize any word in my document and instead suggests replacing them for other ones, like so:

![image](https://user-images.githubusercontent.com/52869159/185979096-fae88174-6816-45bf-bb94-b3d328f1b77f.png)

This isn't a document-specific error, it happens with every file of mine. 

I'm using:
R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"
Platform: x86_64-w64-mingw32/x64 (64-bit)
Windows 11

**Comment by dpprdan** [comment]
@baarthur The non-ASCII letters (ê, â) look fine in your RStudio screenshot, so the encoding problem (which this issue is about) seems to be solved? 
FWIW, my `pt_BR.dic` file does not contain "inconsistência", but `pt_PT.dic` does. I have no clue, why that is. 

<details>
<summary>RStudio Version</summary>

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

</details>

**Comment by baarthur** [comment]
@dpprdan pardon me. Yes, encoding was solved.

I will post this here because I couldn't find any other issue that would suit it better (though [this one](https://github.com/rstudio/rstudio/issues/7018) is similar, it's closed). If you prefer, I can create a new one.

I just created the following document and tried spellcheck on it. I used pt_BR but I found the same problem with pt_PT.

* Accepted words (11): Introdução, um, todas, as, estão, em, português, objetivo, ele, ou, não.
* Not-recognized words (12): Este, é, **teste**, do, dicionário, **palavras**, o, é, verificar, se, **está**, **funcionando**
    + In **bold** are the words I couldn't find via ctrl+F on `pt_BR.dic`. I did find the others, despite not being recognized by Rstudio's spellcheck. It is very worrying that basic words such as "teste" or "funcionando"/"funcionar" ("working"/"to work") are not in the dictionary!
    + Note: I don't know how this dictionaries works, but I'm assuming "verificar/akYjLÀÃ" is the same as "verificar" and "se/áÝ" means "se".
    + The word "dicionário/D13û" is in the dictionary, but the spellcheck suggests I replace "dicionário" by "dicionario" (without accent).

"Fun" thing is that not a single of the words suggested above is in the dictionary as well, I see a pattern here.
![image](https://user-images.githubusercontent.com/52869159/185992498-4105b786-c306-4d35-8a42-8b4274d534c7.png)

---
title: "Teste"
author: "Arthur"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introdução

Este é um teste do dicionário. Todas as palavras estão em português; o objetivo é verificar se ele está funcionando ou não.

**Comment by dpprdan** [comment]
@baarthur This does seem strange indeed. TBH I don't really know how the dictionaries work either and I am not a RStudio developer, so I am out of my depth here. It seems to me that this a different issue than the original one, but maybe we should give @mikebessuille or @ronblum a chance to chime in first.

**Comment by baarthur** [comment]
@dpprdan I just checked and spellcheck is not working in English as well, so this is not an issue exclusive to Portuguese. Alright then, so I'll wait for them and I'll be happy to help if I can do anything.

**Comment by ronblum** [comment]
@dpprdan Thank you for the suggested workaround! I'm not sure if it's working for me though. In that case:

@baarthur Thank you for the detail! A few questions:
- Is switching the .aff file to `SET UFT-8` helping, and the examples you've provided are for what works and doesn't work as a result?
- Interestingly, `introdução` is getting marked for me as misspelled in Brazilian Portuguese.
- Can you provide examples of success and failure in English? With United States English, I'm not running into an issue, using the default R Markdown file as a test.

**Comment by kevinushey** [comment]
Aside from the encoding issues (which should hopefully be resolved now) the rest of the reported issues appear to be deficiencies in the word lists included in the bundled dictionaries.

There's a repository here maintaining a variety of dictionary files:

https://github.com/wooorm/dictionaries

but I don't know how complete / accurate they are.

**Comment by rll307** [comment]
I just received an email telling me this issue is about to be closed due to lack of activity. However, to my knowledge, it is not solved at all. Rstudio lacks spellchecking capacities in Portuguese in both systems I use (macos and linux). In terms of text production, I dropped Rstudio due to this problem.

**Comment by gbanaggia** [comment]
This issue has not been solved.
