### ISSUE TITLE
Quarto not supporting UNC and network mapping under Windows version

### ISSUE THREAD

**Issue by DRF-TARPA1** [rstudio/rstudio#10968]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.1+461
    OS Version      : W7 & W10 (French Canadian)
    R Version       : 4.1.3 / 4.0.3 / 3.6.3

### Steps to reproduce the problem
1. In RStudio Desktop for Windows only, try to open a new Quarto Project on a network drive \\\\server\\folder or map letter network disk Z:\folder with Z: a mapping to \\\\server. 
2. Leave  default option (Knitr and use Vidual markdown editor) for the project and give a name to the project e.g. QuartoTest 
3. Create a Quarto document with default option (HTML, Knitr) with the demo template and render it for visualize it. The same error will be reported in the Jobs tab.

### Describe the problem in detail
1. Immediatly after the second step, the Quarto Project creation will popup quickly a windows which report 
**CMD does not support UNC paths as current directories**
2. Immediatly after rendering the third step, the Quarto Document will report in the Job Tab
**CMD.EXE does not support UNC paths as current directories, taking the default Windows path**
By the way, a default RStudio path on the network for Quarto product will produce exactly the same problem. also, using \\\\ or // syntax doesn't change the problem

### Describe the behavior you expected
Quarto Project should have exactly the same behavior than RStudio Project and supporting network drive with UNC under Windows. 

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@DRF-TARPA1 Thank you for raising the issue! I'll mark this for review as we continue development of RStudio and Quarto.

**Comment by jjallaire** [comment]
We now have a proper quarto.exe launcher executable. The quarto.cmd file is still bundled and currently RStudio is still using it. We should migrate to using quarto.exe

**Comment by timtmok** [comment]
It sounds like migrating to `quarto.exe` will address the issue. That work is tracked in #11873

**Comment by jgutman** [comment]
@DRF-TARPA1 We think this should be resolved in the latest daily build for Windows, available for download at https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/

Could you install that and try it out and see if it resolves the issue?

**Comment by MirzaCengic** [comment]
@jgutman I had the same issue and was eagerly awaiting news, and I can confirm that qmd compiles from a network drive now! Daily version I've used is 270.

**Comment by mahmudur-data** [comment]
I am still unable to render on the network drive. It gives me "Error in dirname(to) : path too long"
I did not find any solution yet, so I moved to the local directory which renders without any problem.
