### ISSUE TITLE
Default home directory can be incorrectly expanded/understood by windows

### ISSUE THREAD

**Issue by jonvanausdeln** [rstudio/rstudio#11635]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.10.0-68
    OS Version      : Windows11
    R Version       : 

### Steps to reproduce the problem

1. Start IDE with default settings & a default project
2. Create a new R Markdown file
3. Select PDF as default output format
4. Knit the file to PDF
5. Accept default location for file. `C:\Users\<user>\Documents`

### Describe the problem in detail

File is created, but when attempting to open the preview, it fails due to not finding a path. The path is completely incorrect.

![failure-tilde](https://user-images.githubusercontent.com/6433789/179632743-01e0de6c-3c84-4989-8140-d8c35ae31dce.png)

This also happens if you save the file to subdirectory of the default directory (saved to `C:\Users\Jon\Documents\testdir-newproject`):

![failure-tilde-2](https://user-images.githubusercontent.com/6433789/179633200-f344b608-751c-495d-af9e-9ed1a8f8d884.png)

To work around the issue,
* Save to a directory that is not a sub-directory of the default "home" directory 

The IDE seems to be incorrectly substituting the path when using the `C:\Users\<user>\Documents` directory.  As the issue shows up even when changing the "Default Working directory" in global settings, to something above "Documents" (e.g.  `C:\Users\<user>`), and then saving the file in the "Documents" directory.

### Describe the behavior you expected

I expect the file preview to be opened.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
I can't reproduce this on my windows machine. Can you provide any more information about your setup?

**Comment by ronblum** [comment]
@jgutman Do you have the `HOME` environment variable set? I think I got this once I removed it.

**Comment by jgutman** [comment]
It still works for me after unsetting HOME

**Comment by timtmok** [comment]
I'm not able to reproduce this either with a markdown file in my Documents directory.

**Comment by kevinushey** [comment]
@jonvanausdeln: What is the value of the `HOME` environment variable? (What about other variables like `R_USER` or `USERPROFILE`)? I would bet one of these has an unexpected form (e.g. a trailing slash, unexpected separators, or something else)

The output of `Sys.getenv()` from an R session would be helpful (make sure to remove any sensitive information or keys that might be included).

**Comment by jonvanausdeln** [comment]
Here are those pertinent values, and then the whole dump.  I just did notice that the some have `/` and some have `\` which is odd. I'll have to look at that more closely.

HOME                               C:/Users/Jon/Documents
R_USER                             C:/Users/Jon/Documents
USERPROFILE                        C:\Users\Jon

>\> Sys.getenv()
ALLUSERSPROFILE                    C:\ProgramData
APPDATA                            C:\Users\Jon\AppData\Roaming
CHROMEDRIVER_PATH                  C:\Users\Jon\chromedriver.exe
CLICOLOR_FORCE                     1
CommonProgramFiles                 C:\Program Files\Common Files
CommonProgramFiles(x86)            C:\Program Files (x86)\Common Files
CommonProgramW6432                 C:\Program Files\Common Files
COMPUTERNAME                       DESKTOP-JS7J8RJ
ComSpec                            C:\WINDOWS\system32\cmd.exe
CURL_CA_BUNDLE                     C:/PROGRA~1/R/R-42~1.1/etc/curl-ca-bundle.crt
DISPLAY                            :0
DriverData                         C:\Windows\System32\Drivers\DriverData
ELECTRON_PATH                      C:\Program Files\RStudio\rstudio.exe
GFORTRAN_STDERR_UNIT               -1
GFORTRAN_STDOUT_UNIT               -1
HOME                               C:/Users/Jon/Documents
HOMEDRIVE                          C:
HOMEPATH                           \Users\Jon
LOCALAPPDATA                       C:\Users\Jon\AppData\Local
LOGONSERVER                        \\DESKTOP-JS7J8RJ
make                               C:\Program Files (x86)\GnuWin32\bin\make.exe
MPLENGINE                          tkAgg
MSYS2_ENV_CONV_EXCL                R_ARCH
NUMBER_OF_PROCESSORS               16
OneDrive                           C:\Users\Jon\OneDrive
OneDriveConsumer                   C:\Users\Jon\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP       undefined
OS                                 Windows_NT
PATH                               C:\RBuildTools\4.2/x86_64-w64-mingw32.static.posix/bin;C:\RBuildTools\4.2/usr/bin;C:\Program
                                   Files\R\R-4.2.1\bin\x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                                   Files\dotnet\;C:\Program Files\Git\cmd;C:\Program
                                   Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\Jon\AppData\Local\Microsoft\WindowsApps;C:\Users\Jon\AppData\Local\Programs\Microsoft
                                   VS
                                   Code\bin;C:\cygwin64\bin;C:\Users\Jon\AppData\Roaming\TinyTeX\bin\win32;C:/Program
                                   Files/RStudio/resources/app/bin/quarto/bin
PATHEXT                            .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE             AMD64
PROCESSOR_IDENTIFIER               Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
PROCESSOR_LEVEL                    6
PROCESSOR_REVISION                 8d01
ProgramData                        C:\ProgramData
ProgramFiles                       C:\Program Files
ProgramFiles(x86)                  C:\Program Files (x86)
ProgramW6432                       C:\Program Files
PSModulePath                       C:\Program
                                   Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                             C:\Users\Public
PYTHONIOENCODING                   utf-8
PYTHONPATH                         C:\Users\Jon\source_code\rstudio-ide-automation\rstudio_server_pro
QT_BEARER_POLL_TIMEOUT             -1
QT_D3DCREATE_MULTITHREADED         1
R_ARCH                             /x64
R_CLI_HAS_HYPERLINK_IDE_HELP       true
R_CLI_HAS_HYPERLINK_IDE_RUN        true
R_CLI_HAS_HYPERLINK_IDE_VIGNETTE   true
R_COMPILED_BY                      gcc 10.3.0
R_DOC_DIR                          C:/PROGRA~1/R/R-42~1.1/doc
R_HOME                             C:/PROGRA~1/R/R-42~1.1
R_INCLUDE_DIR                      C:/PROGRA~1/R/R-42~1.1/include
R_LIBS_SITE                        C:/PROGRA~1/R/R-42~1.1/site-library
R_LIBS_USER                        C:\Users\Jon\AppData\Local/R/win-library/4.2
R_RTOOLS42_PATH                    C:\RBuildTools\4.2/x86_64-w64-mingw32.static.posix/bin;C:\RBuildTools\4.2/usr/bin
R_RUNTIME                          ucrt
R_SHARE_DIR                        C:/PROGRA~1/R/R-42~1.1/share
R_USER                             C:/Users/Jon/Documents
RMARKDOWN_MATHJAX_PATH             C:/Program Files/RStudio/resources/app/resources/mathjax-27
RS_LOCAL_PEER                      \\.\pipe\27981-rsession
RS_RPOSTBACK_PATH                  C:/Program Files/RStudio/resources/app/bin/rpostback
RS_SHARED_SECRET                   55e11899-b919-40fa-ad1f-907f2fef783b
RSTUDIO                            1
RSTUDIO_CLI_HYPERLINKS             true
RSTUDIO_CONSOLE_COLOR              256
RSTUDIO_CONSOLE_WIDTH              80
RSTUDIO_MSYS_SSH                   C:/Program Files/RStudio/resources/app/bin/msys-ssh-1000-18
RSTUDIO_PANDOC                     C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools
RSTUDIO_PROGRAM_MODE               desktop
RSTUDIO_SESSION_PID                34060
RSTUDIO_SESSION_PORT               27981
RSTUDIO_USER_IDENTITY              Jon
RSTUDIO_WINUTILS                   C:/Program Files/RStudio/resources/app/bin/winutils
RTOOLS42_HOME                      C:\RBuildTools\4.2
SESSIONNAME                        Console
SystemDrive                        C:
SystemRoot                         C:\WINDOWS
TEMP                               C:\Users\Jon\AppData\Local\Temp
TERM                               xterm-256color
TMP                                C:\Users\Jon\AppData\Local\Temp
USERDOMAIN                         DESKTOP-JS7J8RJ
USERDOMAIN_ROAMINGPROFILE          DESKTOP-JS7J8RJ
USERNAME                           Jon
USERPROFILE                        C:\Users\Jon
VBOX_MSI_INSTALL_PATH              C:\Program Files\Oracle\VirtualBox\
windir                             C:\WINDOWS
ZES_ENABLE_SYSMAN                  1

**Comment by kevinushey** [comment]
I was able to reproduce as well. I had to make sure that RStudio was configured to use the system viewer when opening PDFs, e.g.

<img width="605" alt="Screen Shot 2022-07-19 at 12 07 58 PM" src="https://user-images.githubusercontent.com/1976582/179829612-796965f6-58e1-4510-bc9d-e18c3c973a1c.png">

With that set, I can reproduce regardless of `HOME` / `R_USER`.

**Comment by jgutman** [comment]
Thanks. @kevinushey -- I can also reproduce with System Viewer. Works correctly with RStudio Viewer. File is correctly exported and saved, it's just an issue with the path that gets passed on to the system viewer, that helps narrow down the issue.

@gtritchie, I don't seem to be getting a Preview with (No Preview) selected and Preview in Window checked in the gearbox. At least, after switching from (No Preview) to System Viewer and back to (No Preview), my selection in the gearbox seems to be ignored in favor of my global option (No Preview).

**Comment by jonvanausdeln** [comment]
I found another case the exhibits the behavior. In the "files" pane while in the "Home" direcotry, under the "More" dropdown, select "Open Folder in New Window".  It results in this error"

![image](https://user-images.githubusercontent.com/6433789/180086428-0434c8b2-fc72-499e-ab01-af6defd7c1f0.png)

**Comment by jgutman** [comment]
Confirmed that with System Viewer set as the default viewer, this works as expected in 2022.07.2-557 Qt Desktop, but fails as described above in 2022.07.2-557 Electron

**Comment by jgutman** [comment]
Should be resolved in [a341463](https://github.com/rstudio/rstudio/commit/a34146358e3f495a440df987d8db5be843d6686f)

**Comment by jonvanausdeln** [comment]
I'm still seeing a version of the issue if I have the save the file to the user's `Documents` directory.  It now is looking in the `C:\Users\<username>` directory instead of Documents. As before the knitted files are created and saved in the correct location, just fails to preview.

**Comment by jonvanausdeln** [comment]
![image](https://user-images.githubusercontent.com/6433789/184442056-db93d2aa-115c-4ae7-9957-734fa582a3f6.png)

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-173
Windows 11

Checked on various files and folders.
