### ISSUE TITLE
Git/Terminal uses different HOME environment variable than R Console or Git Bash

### ISSUE THREAD

**Issue by jdnewmil** [rstudio/rstudio#12333]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2 Build 576
    OS Version      :  Windows 10 21H2 19044.2251
    R Version       :  4.1.3

### Steps to reproduce the problem

1. Windows menu: Edit environment variables for your account
2. Set a custom HOME=C:\Users\YourUser\Documents
3. Restart Windows
4. Open RStudio
5. In R console: enter `Sys.getenv("HOME")
6. In R Terminal (git bash) enter `echo $HOME`

### Describe the problem in detail

It appears that the terminal window is forcing `HOME=C:\Users\YourUser` regardless, while both R and starting the Git for Windows Git Bash icon lead to processes with the desired `HOME=C:\Users\YourUser\Documents`. This also appears to affect the Git functionality in RStudio, which does not respect the `git config` settings configured with the custom HOME that are used in R and by other shells.

### Describe the behavior you expected

I expected RStudio Terminal and internal Git support to respect the same user HOME variable setting that all other environments (including the R console _in RStudio_) support, or have a setting that controls this override.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Do you have "Enable Python integration" checked here?

<img width="601" alt="Screen Shot 2022-11-15 at 10 48 19 AM" src="https://user-images.githubusercontent.com/1976582/202001122-10a806e3-3348-4ea5-9a3a-3cb8eea10150.png">

When that's test, we set up some terminal hooks that should also ensure the correct HOME directory is propagated to new terminal sessions.

We should probably forward the HOME directory when those hooks are disabled too, though.

**Comment by jdnewmil** [comment]
It is enabled. If I read your response clearly, it should be working. However, neither the enabled nor disabled option seems to affect the HOME variable in the terminal.

What are you doing differently than the installed Git for Windows Git Bash shortcut that causes it to fail to inherit these settings from the process that started RStudio (File Manager)?

**Comment by kevinushey** [comment]
I don't think I'm doing anything differently (other than toggling the preference I mentioned). We do probably need to fix this on the RStudio side regardless, since we're not forwarding the HOME environment variable as expected.

**Comment by gtritchie** [comment]
This problem is still present on current `main`. The cause is `setHomeToUserProfile()` in `src/cpp/core/system/Win32System.cpp:1262`:

```cpp
void setHomeToUserProfile(core::system::Options* pChildEnv)
{
   std::string userProfile = core::system::getenv(*pChildEnv, "USERPROFILE");
   core::system::setenv(pChildEnv, "HOME", userProfile);
}
```

This function overwrites `HOME` every time. It does not look for a value that the user set. The terminal calls this function at `SessionConsoleProcess.cpp:111`. Line 97 first copies the full session environment, which still contains the custom `HOME`.

**The Python integration preference is not the cause.** This explains why the preference made no difference. The override at line 111 is part of `createTerminalProcOptions()`, and this code always runs on Windows. The hooks mechanism is a different function, `augmentTerminalProcess()` at line 1114. The preference `prefs::userPrefs().terminalHooks()` controls that function only. The hooks script (`src/cpp/session/resources/terminal/hooks`) forwards the PATH state for conda and reticulate, and it does not change `HOME`.

**The override is deliberate.** A correction is therefore more than a one-line change. `SessionChat.cpp:5271` gives the reason:

> On Windows, R sets HOME to the user's Documents directory rather than
> %USERPROFILE%. Correct it so child processes (e.g. git) find their expected
> config files.

If you remove the call, the custom `HOME` becomes correct and the default case becomes wrong. The difficulty is that both conditions look the same in the environment. R can set `HOME` to the Documents directory. The user can also set `HOME` to that same directory. The environment does not record which one happened.

**The code shows the difference that the report describes.** The session resolves `HOME` correctly at first. `SessionOptions.cpp:267` calls `userHomePath("R_USER|HOME")`. On Windows (`Win32User.cpp:164`) the environment override is the first strategy, before the Documents known-folder fallback. `SessionOptions.cpp:287` then writes this result into the environment of the session. Line 111 discards that result for terminal child processes.

RStudio makes the same call for the git, SVN, workbench, chat, and assistant child processes (`SessionGit.cpp:147`, `SessionSVN.cpp:140`, `SessionWorkbench.cpp:336`, `SessionChat.cpp:5275`, `SessionAssistant.cpp:1339`). The effect is not limited to the terminal pane.

There is one more result. RStudio never sets `HISTFILE`, and bash derives `HISTFILE` from `HOME`. A user with a custom `HOME` therefore gets two separate history files. The terminal writes its history under `%USERPROFILE%`. A standalone Git Bash writes to the configured home directory. I did not test this on Windows, but it follows from the code.
