### ISSUE TITLE
PDF (and xlsx/ods) files cannot be opened from Files pane when their filenames/paths include non-ASCII characters

### ISSUE THREAD

**Issue by k1-ito** [rstudio/rstudio#12467]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-353 (Elsbeth Geranium)
    OS Version      : Windows 10/11 Pro 22H2
    R Version       : 4.2.2

### Steps to reproduce the problem
1. Update Rstudio Desktop from 2022.07.2-576 (Spotted Wakerobin) to 2022.12.0-353.
1. In Files pane of RStudio, move to a folder where a PDF file is.
1. Click the PDF file in Files pane.

### Describe the problem in detail
When its filename or path includes non-ASCII character(s), the default PDF viewer does not launch and the PDF file is not opened.
In the case below, only `London.pdf` can be opened by clicking it.
(In contrast, any Rmd file is properly shown in Source pane.)
![Files](https://user-images.githubusercontent.com/121043466/208591154-837511cd-17af-449f-915c-5c4a0dfc1d6e.png)

### Describe the behavior you expected
Regardless of its filename or path, a PDF file is opened by clicking it in Files pane.

### Additional information
- Under the identical conditions mentioned above (non-ASCII characters are included in the filename or path), 
  - when clicking an xlsx file and selecting `View File` in Files pane, Excel does not launch and the file is not opened.
  - when clicking an ods file in Files pane, LibreOffice Calc does not launch and the file is not opened.
- In the previous version 2022.07.2-576 (Spotted Wakerobin), all of these files (PDF/xlsx/ods) are opened as expected.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@k1-ito Thank you for raising this! We've run into issues with non-ASCII characters in the past. In this case, do the .Rmd file open, or do they fail to open, as well?

**Comment by k1-ito** [comment]
@ronblum Thank you for your response. I can open all the four Rmd files in the example above by clicking them in Files pane. (`London.Rmd`, `München.Rmd`, `SãoPaulo.Rmd`, `東京.Rmd`)
The contents are shown in Source pane with no problem.

**Comment by k1-ito** [comment]
The situation looks the same in RStudio-2023.03.0+386.

**Comment by k1-ito** [comment]
@ronblum I have updated R to 4.3.0. The situation looks the same.

### Additional information
Fonts of Japanese characters are sans-serif in 2022.07.2+576 and the earlier versions, while they are serif in 2022.12.0+353 and the later ones.

RStudio-2022.07.2+576 (sans-serif)
![スクリーンショット 2023-04-22 155520](https://user-images.githubusercontent.com/121043466/233769848-9107f6d5-3351-4df2-9c70-62045a70754e.jpg)

RStudio-2023.03.0+386 (serif)
![スクリーンショット 2023-04-22 155240](https://user-images.githubusercontent.com/121043466/233769834-8126ab6d-42fb-4737-8d16-afa257ea6856.jpg)

**Comment by k1-ito** [comment]
I've found that the electron version of 2022.07.2+576 has the same problems as 2022.12.0+353 and the later ones (the Qt version of 2022.07.2+576 works fine).

**Comment by gtritchie** [comment]
Yes, this is a path handling bug in RStudio (Electron) so any version 2022.12 or newer has this problem. Should be an easy fix, I'll take a look.

**Comment by gtritchie** [comment]
Never say "should be an easy fix" out loud.

* [shell.openExternal(path) does not work well if there are non-ascii chars in the path #6302](https://github.com/electron/electron/issues/6302)
* [In some places, allow to use URL in addition to URI #85930](https://github.com/microsoft/vscode/issues/85930)

**Comment by gtritchie** [comment]
Investigation notes:

Opening a file that goes to an external program ultimately ends up here. 

https://github.com/rstudio/rstudio/blob/fc1420dbb2d802a1cb8934556b39d09dfc8b431a/src/node/desktop/src/main/gwt-callback.ts#L113-L116

I tried a few things (e.g. `encodeURI`, using `shell.openPath` for local files (after converting to a path instead of a URI) based on comments in the Electron and VSCode issues above, but didn't get this working with a file containing non-ASCII characters. I only tried on macOS, comments suggest behaviour will differ between macOS, Windows, and Linux, so that's fun.

Note that `shell.openItem` became `shell.openPath` in Electron 9 (https://github.com/electron/governance/blob/main/wg-api/spec-documents/shell-openitem.md)

**Comment by gtritchie** [comment]
On macOS, even trying to open such a file from the terminal fails. Preview launches, but doesn't show the file (same thing observed from inside RStudio). For example:

`open ./レシピ.pdf`

Launches Preview, but it doesn't do anything. If I double click that same file in Finder, it opens successfully in Preview.

**Comment by gtritchie** [comment]
I don't have time to dig any deeper right now, put it in backlog-1.

This is a regression so should be seriously considered for the next milestone.

**Comment by kevinushey** [comment]
I'm no longer able to reproduce this in recent builds of RStudio + macOS 13.6. Is it possible this was a bug in Apple's `open` utility that was fixed?

For reference, I tested with 2023.12.0 Build 221.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+262](https://dailies.rstudio.com/version/2023.12.0-daily+262)
Windows 11, MacOS 12.6

.pdf and .xlsx files opened as expected

**Comment by k1-ito** [comment]
Unfortunately, under my environment, it seems the problems remain. The files in question do not open.

Rstudio: 2023.12.0-dayly+262
R: 4.3.2 "Eye Holes"
Windows: 11 Pro 22H2 build 22621.2428

I tried both the installer-less and the exe versions of the daily build.

**Comment by jonvanausdeln** [comment]
@k1-ito , what filename is failing for you?

**Comment by k1-ito** [comment]
The filenames include:
`München.pdf`, `SãoPaulo.pdf`, `東京.pdf`, `München.xlsx`, `SãoPaulo.xlsx`, `東京.xlsx`.

**Comment by kevinushey** [comment]
@k1-ito, what version of macOS do you have installed?

**Comment by kevinushey** [comment]
It does work for me... here's the command I used to test:

```

pdf("hello.pdf")
plot(1)
dev.off()
file.rename("hello.pdf", "東京.pdf")
```

Then, try to open the PDF from the files pane.

Note that the workaround we added requires short path names to be enabled on the filesystem. @k1-ito, can you share the output of:

```
shortPathName("東京.pdf")
```

In this scenario, I see:

```
> shortPathName("東京.pdf")
[1] "7CA8~1.PDF"
```

In addition, you could also check from a Windows Command Prompt (need to start as administrator)

```
C:\Windows\System32>fsutil 8dot3name query C:
The volume state is: 0 (8dot3 name creation is ENABLED)
The registry state is: 2 (Per volume setting - the default)

Based on the above settings, 8dot3 name creation is ENABLED on "C:"
```

**Comment by k1-ito** [comment]
Thank you for your explanation.
The files were saved in a drive in which the 8.3 filename creation is disabled.

I tried your command in the C drive, where the 8.3 filename creation is enabled.
But again, `東京.pdf` did not open. 

I also tried to open other files.
The result is:
**success** `München.xlsx` `SãoPaulo.xlsx`
**fail** `München.pdf` `SãoPaulo.pdf` `東京.pdf` `東京.xlsx`

With regard to the short filename, I have found that the 8.3 rule in my environment seems different from yours, and that all the "failed" files have short filenames with non-ASCII characters.
![daily](https://github.com/rstudio/rstudio/assets/121043466/e6a7099b-f0a3-4d8e-8246-e954b4e3ce1d)

**Comment by kevinushey** [comment]
Thank you, that is very interesting -- perhaps it depends on the default system language or locale?

To resolve this, we would likely need to implement our own file opening utility, since we're effectively working around a bug in Electron itself. We'll try to see if there's some straightforward way to accomplish this.

**Comment by kevinushey** [comment]
I think this may have also been resolved by https://github.com/rstudio/rstudio/pull/13926.

**Comment by jonvanausdeln** [comment]
@k1-ito , can you try with our latest daily build ? [2023.12.0-daily+306](https://dailies.rstudio.com/version/2023.12.0-daily+306)
 I was able to open the files without issue.

**Comment by k1-ito** [comment]
Thank you so much! I could also open the files with this build.

**Comment by kevinushey** [comment]
Great! Thanks for taking the time to confirm.
