### ISSUE TITLE
"Show Folder in New Window" doesn't open the default files app 

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rstudio#12477]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  elementary OS 6.1 Jólnir Built on Ubuntu 20.04.5 LTS  Linux 5.15.0-56-generic
    R Version       :  4.2.1

### Steps to reproduce the problem

In the Files pane go to More -> Show Folder in New Window

### Describe the problem in detail

The project folder is opened in gThumb (the bug probably opens a different app depending on what's installed).

### Describe the behavior you expected

The current folder should be opened in the default files app. (e.g. the one that launches with xdg-open).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment]
Note that this was addressed in the move to Electron for Windows and for Mac, but based on this user's report, is likely incorrect on Linux Desktop specifically

**Comment by eliocamp** [comment]
Hi. Just to update that this issue is still present in the latest version: 

RStudio 2023.09.0+463 "Desert Sunflower" Release (b51c81cc303d4b52b010767e5b30438beb904641, 2023-09-25) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.0+463 Chrome/114.0.5735.289 Electron/25.5.0 Safari/537.36

**Comment by ronblum** [comment]
@eliocamp Thank you for checking!

@jgutman I tried this on both Ubuntu 20.04.6 and Red Hat 9.2, but I'm able to open the directory from the Files Pane as well as `system("xdg-open ~")`. Any suggestions of what to look for?

**Comment by eliocamp** [comment]
Running `system("xdg-open ~")` from RStudio opens up gThumb. Strangely, running that from the terminal in R does open the file browser.
