### ISSUE TITLE
Code browser automatically opening when debugging R Shiny

### ISSUE THREAD

**Issue by vfridkin** [rstudio/rstudio#12505]
Using 2022.07.1 Build 554.pro3

The code browser tab (it has two dots, see below for example) opens every time a line of code is run while debugging in R Shiny using `browser()` statements.  This decreases the joy of debugging significantly due to having to constantly switch off the added tab and find where the debugging got to in the original tab for every code line being run.

Expected behaviour: During debugging, RStudio keeps focus where the user ran the code.
Current behaviour: Opens new tab and/or moves to another tab automatically each time a block of code is executed during debugging.

This issue has been raised here on 2020 and comments made suggested it had been already fixed
https://github.com/rstudio/rstudio/issues/6740

Also raised here
https://github.com/rstudio/rstudio/issues/9943

And I've asked here with no satisfaction
https://stackoverflow.com/questions/69652407/debugging-r-shiny-with-browser-statements-less-painfully

Image shows the unwanted tab that opens automatically.  May this two dotted monster be banished eternally for the unhappiness it has wrought!
![image](https://user-images.githubusercontent.com/16199216/209882910-79ecc020-3c3a-450d-9cca-0413b5154d3b.png)

**Comment by ronblum** [comment]
@vfridkin Thank you for raising this! Rather than reopening one of the existing issues, lets use this issue. Did this behave as you'd like in any previous versions? There's some indication that the behavior changed in a previous release, but that's not consistent. I'm trying to determine if this is a regression or a continuing enhancement.

Triage: Note number of comments and upvotes.

**Comment by vfridkin** [comment]
@ronblum Yes, this behaved as I (and my 100+ team) liked in version 1.1.463
![image](https://user-images.githubusercontent.com/16199216/210024479-5bea5175-65ce-4831-85f9-2690ddf987f6.png)

Please note, it seems that editing the code while debugging triggers the tabs opening - which is what I do 100% of the time when debugging.  

My understanding is that during debugging, RStudio recognizes that the code being edited (edits) is different from the saved code (saved) and keeps opening or moving to the saved tab instead of staying in the edits tab.

**Comment by ronblum** [comment]
@vfridkin Thanks! I tried to run the code in RStudio Desktop 1.1.463 with R 3.3.3. I'm not seeing the same behavior, but I might be following the same steps. However, I did notice that starting with version 1.4.1106, there's a bug in which the cursor loses focus—previously, it remained in the Console Pane.

@kevinushey What is the expected behavior? I might not be replicating the exact steps as @vfridkin which might explain the difference the @vfridkin and I are seeing even in 1.1.463.

FWIW, I used the following code, snatched from the previous issues:
```
a <- function() b()
b <- function() c()
c <- function() {
  x <- 10
  browser()
  x
}
a()

myfun <- function(x) print(x)
debugonce(myfun)
myfun("test")
```

**Comment by vfridkin** [comment]
@ronblum I've used your example in both 2022.07.1 (_new_) and 1.1.463 (_old_).  I was able to generate the issue in _new_ and for the same test, it did not occur in _old_.

Here are the steps:
1. saved your code in a test.R file
2. with the code open, sourced the file
3. now in browse/debug mode, added a line after the browser() like this
![image](https://user-images.githubusercontent.com/16199216/210278143-1bd8cff3-78e6-429b-97a3-c00f2684837c.png)
4. execute the added line while still in browse mode

In _new_ it opened a new tab to the original code without the added line.  

In _old_ it didn't open a new tab - this is the desired behaviour.

**Comment by cm421** [comment]
Linking customer ticket #84078 here because they seem to be experiencing a similar issue on Workbench 2022.07.1+554.pro3

**Comment by kevinushey** [comment]
FWIW, I'm not able to reproduce in the latest RStudio release (2022.12.0).

**Comment by mikebessuille** [comment]
@vfridkin can you please confirm if this problem exists in the latest release, 2022.12.0?   We have been unable to reproduce this.

**Comment by datakid** [comment]
Linking customer ticket #84410

**Comment by itsshubhamsaxena** [comment]
Hi, I am also facing exactly same problem with 2022.12.0+353.pro20 Workbench (Elsbeth Geranium) for RHEL 8

**Comment by rich-rstudio** [comment]
I was able to reproduce on RHEL 8 workbench 2023.03.1 Build 409.pro2 and 2022.12.1+366.pro6

**Comment by datakid** [comment]
Ticket #88232 has this issue as well, this is a reproduction in 2022.12 from ticket #84078 mentioned [in this comment above](https://github.com/rstudio/rstudio/issues/12505#issuecomment-1379323080).

**Comment by jthomasmock** [comment]
@mikebessuille I added this back to triage as we are seeing strong signal that this is disruptive and reproducible across a few versions/end user groups.

**Comment by mikebessuille** [comment]
Now that Rich has been able to repro this using Workbench on RHEL I agree we need to take a look at this urgently.

**Comment by datakid** [comment]
Customer from ticket #84410 ([comment above](https://github.com/rstudio/rstudio/issues/12505#issuecomment-1386392101)) has reproduced in 2022.12 as of today. Details can be found in #88391

**Comment by ronblum** [comment]
@sharon-wang is able to reproduce this in the open source RStudio Desktop 2023.03.0+386 on MacOS 13.1.

**Comment by datakid** [comment]
Ticket #94715 has asked about this issue.

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding, but it looks like this issue has been resolved in the latest daily builds? It's hard to be certain because we don't have a concrete reproducible example for Shiny in this issue. Here's the Shiny application I tried running:

```

library(shiny)

ui <- fluidPage(
  titlePanel("Debugging with Shiny"),
  textOutput("text")
)

server <- function(input, output) {
  output$text <- renderText({
    print(1 + 1)
    browser()
    print(2 + 2)
    browser()
    print(3 + 3)
    "Hello, world!"
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```

When I start the Shiny application, the `browser()` breakpoint is hit. I can then switch to different editors, or run code in the console, and focus is never aggressively shifted back to the original source file. This is true even if I run the script by:

- Highlighting the code and sending to console with Cmd + Enter (but we don't have srcrefs in this case),
- Running the script via the Run App button,
- Running the script with Cmd + Shift + S (to Source the script)

Is this an accurate description of the issue? If so, and if someone is still encountering this issue with the latest [daily builds](https://dailies.rstudio.com), could you please let us know? It could also help if you could share a screen cast of what behavior exactly you're seeing.

**Comment by vfridkin** [comment]
It is still an issue with the version we are using:
RStudio 2023.06.1+524.pro1 "Mountain Hydrangea" Release (7025e95aa1ac86789df08ba007f6ee3dcdbb0c11, 2023-07-06) for RHEL 8
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

Please note, we are using Shiny modules throughout.
If it has been fixed in a subsequent version, please let me know.

**Comment by ronblum** [comment]
@vfridkin We just released a new version of RStudio yesterday, [version 2023.09.0+463](https://posit.co/download/rstudio-desktop/). The problem should be (hopefully!) resolved in it. Can you try it out?

**Comment by jthomasmock** [comment]
Using Kevin's example and "Run App", I'm not able to reproduce the opening of a new View only browser view.

https://github.com/rstudio/rstudio/assets/29187501/b610d159-4609-4af8-be9d-070d86937fad

**Comment by kevinushey** [comment]
@vfridkin, the issue appears to be resolved on our end. If you can, please try testing one of the latest daily builds at https://dailies.rstudio.com. We're going to close this issue as resolved, but please feel free to re-open with more details if you're still having trouble.
