### ISSUE TITLE
Quarto can't be stopped after running Shiny document 

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#12546]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.68
    OS Version      : Windows 10 x64 (build 22621)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

Quarto version used: 1.3.91

### Steps to reproduce the problem

1. Open a new shiny document
2. Run it 
3. Close the document (process still running)
4. Try to Stop the task 

### Describe the problem in detail

It seems it is not possible to stop a Quarto process running a Shiny Document. This means that when opened, it hands and a new version of the document can't be run. I need to kill RStudio and reopen

https://user-images.githubusercontent.com/6791940/211344833-7451fe4d-3440-44be-be7c-a5c1eebe4018.mp4

### Describe the behavior you expected

The process should be closed when the webpage is closed in the viewer, or at least it should be possible to close using the interrupt button of the task. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Triage note: Potentially for Cherry Blossom?

**Comment by melissa-barca** [comment]
@cderv I sent you a dev build with a potential fix for this. I'm hoping you can help test it out since I can't reproduce the original issue. Thanks!

**Comment by melissa-barca** [comment]
@jjallaire I implemented the code you recommended on this branch `bugfix/terminate-quarto-shiny-windows`, and can see it being executed and killing the PID but @cderv still sees the same behavior where quarto doesn't stop. I haven't been able to reproduce the bug so have been struggling to research this further. Do you have another recommendation? 
https://github.com/rstudio/rstudio/blob/784583d15b0a85fd5bf4733a2a5553cae346e0a6/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L805-L825

**Comment by sharon-wang** [comment]
https://github.com/rstudio/rstudio/issues/12836#issuecomment-1525103457 sounds like this issue.

Confirming that the `bugfix/terminate-quarto-shiny-windows` branch doesn't resolve the issue for me either.

Going to try some of the ideas from https://github.com/rstudio/rstudio/issues/12836 (eg. stopping the `deno` process) and see if that works here.

**Comment by sharon-wang** [comment]
I moved the `taskkill` code from `SessionRMarkdown` to `SessionAsyncRProcess`, to more closely match how `SessionQuartoJob` deals with a similar issue. That seemed to do the trick!

**Comment by jonvanausdeln** [comment]
This is working for me on 2023.05.0-daily+358
Windows 11

However, I was not able to reproduce it on cherry blossom build 2023.03.0+386

@cderv , could you verify the latest daily fixes it for you?

**Comment by cderv** [comment]
@jonvanausdeln I can confirm this works now on `2023.05.0-daily+359` 

thanks @sharon-wang for finding the right fix !
