### ISSUE TITLE
New Quarto file options not available if the RStudio path or app has a space

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12902]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386 and 2023.05.0-daily+92
    OS Version      : MacOS 13.2
    R Version       : 4.2.3

### Steps to reproduce the problem

1. Install RStudio Desktop.
2. Change the application's filename so that there's a space in it, e.g. `RStudio Cherry Blossom`
3. Start RStudio Desktop.
4. <kbd>File -> New File</kbd>
    - `Quarto Document` and `Quarto Presentation` are missing
5. In the Console Pane: `quarto::quarto_version()`
    - An error is displayed:
    > Error: invalid version specification ‘ERROR: Cannot determine the Quarto source path. This script must be run from the bin or common folder.’
In addition: Warning message:
In system2(quarto_bin, "--version", stdout = TRUE) :
  running command ''/Applications/RStudio Cherry Blossom.app/Contents/Resources/app/quarto/bin/quarto' --version' had status 1

### Describe the problem in detail

If the name or path of RStudio has a space in it, and hence the same for the path for `quarto`, the Quarto options aren't available in the `File` menu.

### Describe the behavior you expected

Quarto options should be available even if there's a space in the path or file name.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@dragonstyle i believe you already PR'd this issue?

**Comment by dragonstyle** [comment]
We have the PR open for Quarto 1.4 (it isn't going to make 1.3, sadly).

**Comment by cderv** [comment]
FWIW this was possibly solved in two steps: 

* https://github.com/quarto-dev/quarto-cli/pull/4980
* https://github.com/quarto-dev/quarto-cli/issues/7032

I don't know if you are able to test with dev version and RStudio but the error 
```
‘ERROR: Cannot determine the Quarto source path. This script must be run from the bin or common folder.’
```

is fixed on my side when I try with space in path

**Comment by ronblum** [comment]
The file types are now available, but opening a new file results in the following error and the files aren't created,


![Image](https://github.com/rstudio/rstudio/assets/31009952/55d2d6f7-e8c6-4b17-9fd2-d961888128ef)

**Comment by kevinushey** [comment]
Seems to work for me with Quarto 1.4 (which is now distributed with the latest dailies) so I believe this is fixed?

**Comment by ronblum** [comment]
@kevinushey I'm still getting the "State not recoverable" error message and no new file.

**Comment by kevinushey** [comment]
I'm inclined to close this as won't-fix on the RStudio side; this ultimately needs to be resolved on the quarto side.

```
> Sys.which("quarto")
                                                                          quarto 
"/Applications/RStudio With Spaces.app/Contents/Resources/app/quarto/bin/quarto" 
> system("quarto version")
error: Unable to load 'file:///Applications/RStudio' import map

Caused by:
    No such file or directory (os error 2)
```

**Comment by cderv** [comment]
@kevinushey did you try `quarto version` instead of `quarto --version` on purpose ? 

A flag works 
````
$ /home/cderv/Path\ with\ Space/bin/quarto  --version
1.4.550
````

but I can reproduce with any command pass to Quarto, unkown
````
$ /home/cderv/Path\ with\ Space/bin/quarto dummy
error: Unable to load 'file:///home/cderv/Path' import map

Caused by:
    No such file or directory (os error 2)
````

or known 
````
$ /home/cderv/Path\ with\ Space/bin/quarto render test.md
error: Unable to load 'file:///home/cderv/Path' import map

Caused by:
    No such file or directory (os error 2)
````

Just want to be sure it was to illustrate the same thing.

**Comment by kevinushey** [comment]
> @kevinushey did you try quarto version instead of quarto --version on purpose ?

No, I can just never remember which one is the right flag. 😞

**Comment by kevinushey** [comment]
Apparently RStudio _is_ running into the same issue, as we try to run `quarto capabilities` here:

https://github.com/rstudio/rstudio/blob/9c5ad2bacb50a7d285952d8dd4b01044fac1247c/src/cpp/session/modules/quarto/SessionQuarto.cpp#L475-L487

Is that something which used to exist, but no longer does?

**Comment by dragonstyle** [comment]
That does still exist and it seems likely that the space in path issue is a regression of some kind that seems different than the original root cause (which had to do a failure to quote properly in the quarto bash script). This looks to be properly executing the typescript runtime and then failing when resolving imports somehow - I honestly don't fully understand, but it is much different than the original error...

Adding @cscheid who has the possibility to know more...

**Comment by cscheid** [comment]
Yeah, that definitely feels like a bug on our side, but I'm having a hard time reproducing it locally. @kevinushey can we pair over this?

**Comment by ronblum** [comment]
Test this in RStudio once the change is made in Quarto.

**Comment by cscheid** [comment]
We just merged a fix on `main` and a backport to v1.4. It's time for us to make a new v1.4 patch release, so you should be able to test it in quarto v1.4.551 soon.
