### ISSUE TITLE
Error in autocomplete for large dataframes

### ISSUE THREAD

**Issue by jwilliamrozelle** [rstudio/rstudio#13018]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.05.0 Build 264 (but also occurs in 2023.03.0+386)  
    OS Version      :  Windows 10 x64 (build 22621)
    R Version       :  4.2.3 (2023-03-15 ucrt) (seems to happen in earlier versions of R version 4.x)
    RAM: 64 GB
    CPU: 12th Gen Intel(R) Core(TM) i7-12700K   3.60 GHz

### Steps to reproduce the problem

I have real data that I can't share, but the issue seems to be reproduced when I generate a random dataframe of a similar size.

```R
library(dplyr)

generate_dataframe <- function(n_rows, n_columns) {
  set.seed(42) # Setting the seed for reproducibility
  
  random_column_generator <- function(n_rows) {
    col_type <- sample(c("character", "numeric", "boolean", "factor"), 1)
    
    if (col_type == "character") {
      return(sample(c(LETTERS, NA), n_rows, replace = TRUE))
    } else if (col_type == "numeric") {
      return(sample(c(rnorm(n_rows, mean = 0, sd = 1), NA), n_rows, replace = TRUE))
    } else if (col_type == "boolean") {
      return(sample(c(TRUE, FALSE, NA), n_rows, replace = TRUE))
    } else if (col_type == "factor") {
      values <- sample(c(-1:1, NA), n_rows, replace = TRUE)
      labels <- c("Negative", "Neutral", "Positive")
      return(factor(values, levels = c(-1, 0, 1), labels = labels, exclude = NULL))
    }
  }

  random_string <- function(length) {
    return(paste(sample(c(LETTERS, letters), length, replace = TRUE), collapse = ""))
  }
  
  df <- data.frame(matrix(ncol = n_columns, nrow = n_rows))
  
  for (i in 1:n_columns) {
    df[[i]] <- random_column_generator(n_rows)
  }

  colnames(df) <- replicate(n_columns, random_string(sample(1:8, 1)))
  
  return(df)
}


# Generate random large dataframe
generated.df <- generate_dataframe(n_rows = 5e4, n_columns = 4e3)
```

### Describe the problem in detail

Then an error appears during the autocomplete for variable names. Using this, for example, when I type the `$` in `generated.df$`, I get the error:

```
Error in order(typeScores, scores) : argument lengths differ
In addition: Warning message:
In completions$type == .rs.acCompletionTypes$DATAFRAME & !completions$context %in%  :
  longer object length is not a multiple of shorter object length
```
This specifically appears to be a (new) issue for larger dataframes - when I cut down the dataframe columns, the error seems to disappear. It did not occur in previous versions of RStudio.

### Describe the behavior you expected

Just working autocomplete, or at least not an error in the console every time I type `mydataframe$`.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ NA] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! This issue can be reproduced with any `data.frame` containing more than 2000 columns, e.g.

```
library(uuid)
keys <- replicate(2001, uuid::UUIDgenerate())
names(keys) <- keys
df <- as.data.frame(as.list(keys))
```

I'll see if I can figure out what's going on.

**Comment by jwilliamrozelle** [comment]
Awesome!  Thanks @kevinushey

**Comment by kevinushey** [comment]
<img width="857" alt="Screenshot 2023-04-20 at 10 13 37 AM" src="https://user-images.githubusercontent.com/1976582/233439808-bb0c383f-9213-4cec-b21b-c1de13bebdff.png">

**Comment by kevinushey** [comment]
It will be in the next daily builds; those are not yet live. Hopefully within the next couple days (it looks like our build farm is having some trouble that we're going to need to diagnose)

**Comment by dgoekbuget** [comment]
Any news on when this will be fixed? Thanks.

**Comment by jwilliamrozelle** [comment]
I believe it is fixed - at least in the daily builds, and also maybe in the
latest full release.

**Comment by dgoekbuget** [comment]
Still getting this error on Version 2023.03.1+446 (2023.03.1+446)
![Screenshot 2023-06-01 at 10 20 20 AM](https://github.com/rstudio/rstudio/assets/17674138/03d29591-f9c3-4b96-9c68-ce24f59877e5)
![Screenshot 2023-06-01 at 10 20 27 AM](https://github.com/rstudio/rstudio/assets/17674138/8ddaad77-9385-40c3-8d64-b5885326d133)

**Comment by jwilliamrozelle** [comment]
@dgoekbuget, need to update to 2023.05.XX
