### ISSUE TITLE
"An error occurred while attempting to load the selected version of R. Please select a different R installation". Windows 11 R installation.

### ISSUE THREAD

**Issue by fahad-mirza** [rstudio/rstudio#13099]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version: 2023.03.0+386 | Released: 2023-03-16
    OS Version      : Windows 11 Home Single Language build 22621.1635 (Version: 22H2)
    R Version       : 4.3.0

### Steps to reproduce the problem
Completely new installation of R (Version: 4.3.0) followed by an installation of RStudio 2023.03.0+386

### Describe the problem in detail
After downloading [R](https://cran.r-project.org/bin/windows/base/) and installing the latest [RStudio 2023.03.0+386](https://posit.co/download/rstudio-desktop/) , the RStudio asked me to specify the R version that was installed in my machine. However, even though I have tried to point to the R installation path (R 4.3.0), the RStudio still failed to open and give an error failed to load the selected version of R. I am attaching the log file as mentioned in the other [issue](https://github.com/rstudio/rstudio/issues/12452)

[rdesktop.log](https://github.com/rstudio/rstudio/files/11414140/rdesktop.log)
[rsession-Fahad Mirza.log](https://github.com/rstudio/rstudio/files/11414165/rsession-Fahad.Mirza.log)

![Rstudio_Error](https://user-images.githubusercontent.com/73574837/236663522-4d68e74b-a3f2-4509-9b38-3ce652b0af02.png)

### Describe the behavior you expected
Was looking forward to a smooth installation and usage as before.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fahad-mirza Thanks for raising this! This might be addressed in the upcoming RStudio Desktop 2023.03.1 patch. If you'd like to try it, [daily builds for it](https://dailies.rstudio.com/rstudio/cherry-blossom/electron/windows/) are available at https://dailies.rstudio.com/rstudio/cherry-blossom/electron/windows/. Please note that the dailies are only meant for testing purposes, not production work.

**Comment by pikpa** [comment]
**Fatal error: 'R_TempDir" contains space**
I just downloaded R 4.3.0 on windows 11 and it gives the "Fatal error: 'R_TempDir" contains space" when I try to start, does anyone know how to solve this problem? My R studio also failed to open. I have tried creating the TMPDIR environment and it still doesn't work

**Comment by fahad-mirza** [comment]
@pikpa unfortunately my issue has been occurring for a long while now and I wanted to start learning R as I paid a course fee that makes use of it but it seems like I am going to be losing out on it lol. 

@ronblum by when do you feel a solution to this issue will be released?

**Comment by kevinushey** [comment]
Is installing an older release of R (e.g. R 4.2) an option? These are available at https://cran.r-project.org/bin/windows/base/old/.

**Comment by fahad-mirza** [comment]
@kevinushey although the problem seems to be from Rstudio, I just tried your method of installing the older version of R just to check and the problem still persists. The issue seems to be linked with Rstudio

**Comment by jgutman** [comment]
Please let us know if the issue persists for you after updating -- if so we will look into this again.

**Comment by fahad-mirza** [comment]
Hi @jgutman sorry for not getting back on this but yes this is now resolved! thanks so much

**Comment by ronblum** [comment]
@fahad-mirza I'm glad it worked out!

**Comment by kumarakg** [comment]
Hello, I have the same problem, how did you resolve it? please let me know. Looking forward to hearing from you!

**Comment by timtmok** [comment]
@kumarakg this was resolved in 2023.03.1. Which version are you using?

**Comment by sameer-kulkarni121** [comment]
The exact same error still remains for me when i try to run R for the first time. 

R: 4.3.2
RStudio Version: 2023.12.0+369

![Capture](https://github.com/rstudio/rstudio/assets/138465415/06e0805a-7f00-48db-b73d-cff6320eee94)

**Comment by sameer-kulkarni121** [comment]
Okay, I think I found a fix for this (at least it worked for me), the first solution worked and I thought of this because when I tried opening R by itself I got the same "fatal error" as mentioned on this thread.

https://stackoverflow.com/questions/72138987/r-studio-fatal-error-r-tempdircontains-space

> The exact same error still remains for me when i try to run R for the first time.
> 
> R: 4.3.2 RStudio Version: 2023.12.0+369
> 
> ![Capture](https://private-user-images.githubusercontent.com/138465415/300390111-06e0805a-7f00-48db-b73d-cff6320eee94.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTg0MzMsIm5iZiI6MTcwNjUxODEzMywicGF0aCI6Ii8xMzg0NjU0MTUvMzAwMzkwMTExLTA2ZTA4MDVhLTdmMDAtNDhkYi1iNzNkLWNmZjYzMjBlZWU5NC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwODQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjI5OThiZWRmMjlkNDU1MTdlY2EwMzRlMGVhMzhkOTE3ZThhMjkxNWI5ZTliMGJiNDJhMzZjOGJlY2NiZmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YcqwgWRalfecSjOnuA6DPcWiUgUU1KzYH4xXwL0Xr30)
