### ISSUE TITLE
Error accessing PDF file installed in package doc folder

### ISSUE THREAD

**Issue by zivankaraman** [rstudio/rstudio#13886]
I'm having trouble accessing a PDF file that's installed in the package doc folder. For example, I'm trying to access the zoo.pdf file in the "C:\Program Files\R\R-4.2.3\library\zoo\doc\" folder. When I open the package help page and click on "User guides, package vignettes and other documentation" and then click on the zoo::zoo link or the PDF link next to the description, my default browser opens and I get the error message "Access to 127.0.0.1 denied - HTTP ERROR 403". I've tried using different browsers, but the problem persists. However, I can access the file from Windows Explorer. If I click on the "Show in new window" icon at the top of the Help pane and select the same file, everything works perfectly fine. The file also opens correctly from vanilla R (going through help.start() etc.).

### System details
    RStudio Edition : Desktop
    RStudio Version : 2023.09.1+494
    OS Version      : Windows 10
    R Version       : 4.2.3

_RStudio information:_  
RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

_R sessionInfo:_
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
Matrix products: default
locale:
[1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8    LC_MONETARY=French_France.utf8 LC_NUMERIC=C                  
[5] LC_TIME=French_France.utf8    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] compiler_4.2.3 tools_4.2.3   

### Steps to reproduce the problem
1. Open the "zoo" package help page.
2. Click on "User guides, package vignettes and other documentation".
3. Click on the zoo::zoo link or the PDF link next to the description.
 

### Describe the problem in detail
The default browser opens and the error message "Access to 127.0.0.1 denied - HTTP ERROR 403" is displayed.

### Describe the behavior you expected
I would expect the PDF file to open in the browser (or be proposed to download as in vanilla R.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! I believe this has been fixed in the latest [daily builds](https://dailies.rstudio.com) -- would you be able to test and report back?

**Comment by kevinushey** [comment]
Thanks; I'll take a look.

**Comment by kevinushey** [comment]
This should be fixed in the latest daily builds; would you be willing to test once more?

**Comment by zivankaraman** [comment]
It works, but only if the file doesn't have spaces in the name. If you rename "R-lang.pdf" to "R lang.pdf" you still get the error message:

> Error: vignette ‘R%20lang’ not found

**Comment by jonvanausdeln** [comment]
I just checked with [2023.12.0-daily+278](https://dailies.rstudio.com/version/2023.12.0-daily+278) on Windows11 and as @zivankaraman mentioned, it fails with a filename containing spaces.  It also fails for files with non-ascii file names, such as `東京.pdf`. This could be related to #12467

**Comment by kevinushey** [comment]
Thanks @jonvanausdeln: I've decided to side-step the issue in Electron altogether and just use our own native code to open the file on Windows. Hopefully this will resolve the issue once and for all.

**Comment by jonvanausdeln** [comment]
Checked again with [2023.12.0-daily+290](https://dailies.rstudio.com/version/2023.12.0-daily+290)
Windows 11

Now works with spaces and Unicode characters in file name.. e.g. `東京 with a space.pdf`
