### ISSUE TITLE
regression in ggplot2 aesthetics completions (wrong order) when ggplot2 is attached

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15158]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.10.0+125
    OS Version      : Windows
    R Version       : 4.4.1

### Steps to reproduce the problem

Drawback from #13611 

trying to autocomplete this is slightly wrong.
```r

mtcars |> ggplot(aes(<tab>))
```

### Describe the problem in detail

Now 2024.10.0+125
![image](https://github.com/user-attachments/assets/a3eb55eb-b996-4b01-b63d-bc7d4f780614)

### Describe the behavior you expected

Before: (2024.04.2)
![image](https://github.com/user-attachments/assets/4f6e1bb9-49c6-4bba-b466-82d2ae7d65ca)

It seems to be the only regression I noticed so far.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
I wasn't able to reproduce in the most recent daily builds -- is it possible this was already resolved?

**Comment by olivroy** [comment]
@kevinushey I just installed 2024.10.0+163, and I still see it like this.
To repro, I think you need to have ggplot2 attached. `library(ggplot2)`
![image](https://github.com/user-attachments/assets/b1135ed4-eec1-41ff-9800-dc84e1b46712)

It is not an issue when ggplot2 is not attached however.
![image](https://github.com/user-attachments/assets/e17e7f15-ac80-4008-a66a-338f14c6d2a5)

**Comment by kevinushey** [comment]
Note: fix for this was bundled into https://github.com/rstudio/rstudio/pull/15159.

**Comment by olivroy** [comment]
Thanks for the quick! Will test it next week
