### ISSUE TITLE
The build pane can no longer be stopped if clicking on the Stop button

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#15214]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2024.10.0.201
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem

1.In a package repo, run testthat tests Ctrl / Cmd + Shift + T.
2. Click on the Stop button in the build pane (to stop tests running)

### Describe the problem in detail

The button no longer has any effect.

### Describe the behavior you expected

I would expect the interruption to work. I am running a French locale.

In 2024.04.2 (comparing as I have this version installed locally, but it broke more recently), after clicking on the Stop button, I'd get this
![image](https://github.com/user-attachments/assets/640049a6-3358-4768-9f59-f3acedeba010)

But with the last few dailies, it doesn't work..

I get this and there seems to be no way to launch a new build pane process
![image](https://github.com/user-attachments/assets/5ed1aa51-9de1-45d1-acaa-4598c1e3c985)

It may be due to fixing #14564 ?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks -- should be fixed by https://github.com/rstudio/rstudio/commit/2fda0c571ab57785ab5a7610f5e0e212c93503bc.

**Comment by olivroy** [comment]
The stop button works again! Thanks 

However, a tiny issue remains:

Before, the Build Pane process could be terminated if things were not over.

i.e. run tests (ctrl + shift +t), but then make a modification somewhere in codebase (i.e. you realize tests are failing, and you make a quick fix to run it again) and just run again ctrl + shift + t (before the first process was over)

Now, with the latest daily, I need to click on the Stop button for this to work.

**Comment by kevinushey** [comment]
@olivroy can you please file a separate issue?
