### ISSUE TITLE
dragging an image onto the IDE causes it to take over IDE

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1653]
For example:

1. Execute `plot(1)`,
2. Click 'Zoom' in the plot pane, to open that plot in a new window,
3. Drag that image somewhere on the IDE (e.g. onto the Console pane, or on the Environment pane)

The image then 'takes over' the IDE viewport. The only resolution from there is to restart the IDE.

**Comment by kevinushey** [comment]
My next attempt to launch the IDE also fails; I have to explicitly force-kill the frozen IDE instance and then re-launch.

**Comment by trestletech** [comment]
Hit this recently myself. I was trying to resize an image from a zoomed window and accidentally dragged the image onto the IDE. I was able to recover by pressing Backspace ("Delete", technically) but the zoom button ceased to work, and I had to force close to get out.

![img](https://user-images.githubusercontent.com/1593639/33027125-e986fbb4-cdd7-11e7-9544-23e5da1efdf3.gif)

**Comment by gtritchie** [comment]
This seems to have been fixed, likely by the switch over to QtWebEngine (and Qt for Mac desktop). Doesn't repro for me any longer on recent Mac 1.2.x desktop builds.

**Comment by SCTX** [comment]
Thank you to @trestletech for this comment. I'm running Version 1.1.456 on Windows and can confirm that this behavior (plot taking over the IDE and making it unresponsive to commands) still exists. Repeatedly pressing Backspace will close the plot window, and then a right-click will bring up a menu that allows you to get the Rstudio panes back again.

> Hit this recently myself. I was trying to resize an image from a zoomed window and accidentally dragged the image onto the IDE. I was able to recover by pressing Backspace ("Delete", technically) but the zoom button ceased to work, and I had to force close to get out.
> 
> ![img](https://user-images.githubusercontent.com/1593639/33027125-e986fbb4-cdd7-11e7-9544-23e5da1efdf3.gif)

**Comment by BastiHz** [comment]
> I'm running Version 1.1.456 on Windows and can confirm that this behavior (plot taking over the IDE and making it unresponsive to commands) still exists.

Because you are using an outdated version. This was fixed in version 1.2.
