### ISSUE TITLE
Error compiling from source: "error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by zachokeeffe** [rstudio/rstudio#1724]
Using Debian 9.2. Trying to compile from source, but sudo make install fails at Generating ui_DesktopInputDialog.h, giving the error:

error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
src/cpp/desktop/CMakeFiles/rstudio.dir/build.make:208: recipe for target 'src/cpp/desktop/ui_DesktopInputDialog.h' failed
make[2]: *** [src/cpp/desktop/ui_DesktopInputDialog.h] Error 127
CMakeFiles/Makefile2:550: recipe for target 'src/cpp/desktop/CMakeFiles/rstudio.dir/all' failed
make[1]: *** [src/cpp/desktop/CMakeFiles/rstudio.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Installing from .deb works (though there are a ton of issues with it, which is why I'm trying to install from source). I ran ./install-dependencies-debian successfully beforehand.

**Comment by zachokeeffe** [comment]
That was using last night's build, actually. Now I'm getting the issue from sudo make install (after rerunning the dependencies installation),

CMake Error: Parse error in cache file /victor/Downloads/rstudio-master/build/CMakeCache.txt on line 353. Offending entry: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Boost version: 1.63.0
-- Using RStudio-provided Boost 1.63.0
-- Found R: /usr/lib/R
-- Configuring incomplete, errors occurred!
See also "/victor/Downloads/rstudio-master/build/CMakeFiles/CMakeOutput.log".
See also "/victor/Downloads/rstudio-master/build/CMakeFiles/CMakeError.log".
Makefile:358: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

**Comment by jmcphers** [comment]
What are you trying to accomplish? 

You might try building with our Debian 9 Dockerfile: https://github.com/rstudio/rstudio/blob/master/docker/jenkins/Dockerfile.debian9-x86_64

If you're not familiar with Docker, there's also a script which does the work for you -- just run `docker-compile.sh` for instructions.

https://github.com/rstudio/rstudio/blob/master/docker/docker-compile.sh

**Comment by zachokeeffe** [comment]
Hm, don't know about Docker, I'll look into that--thanks. I restarted, and ran make install (omitting sudo), and now it appears to be running.

I'm trying to get RStudio to run properly on my machine. It either takes a minute or two to save a file, or crashes. The constant hanging and crashing is making it virtually unusable.

**Comment by jmcphers** [comment]
Do the dailies work for you? The issue you describe sounds like https://github.com/rstudio/rstudio/issues/1587, which is fixed in the dailies (and will be in an upcoming patch release to 1.1).

https://dailies.rstudio.com/

Not sure about the crashing, though. Can you open an issue with a stack trace if you can capture one?

**Comment by zachokeeffe** [comment]
Oh wow, yes--rstudio-trusty-1.2.158-amd64.deb did the trick, thank you! I'm still encountering the issue with Tools > Global Options... though. It takes 30 seconds to open the dialogue box, if it doesn't crash--though once it loads it works fine. How would I do the stack trace you mentioned?

**Comment by pat-s** [comment]
duplicate of #1871?

**Comment by jmcphers** [comment]
> It takes 30 seconds to open the dialogue box

This is almost always due to lots of installed fonts, and is resolved in the current release (we now cache; see https://github.com/rstudio/rstudio/issues/1889).
