### ISSUE TITLE
file.edit(<UTF-8 path>) fails on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1868]
Consider the following:

    file.edit("你好.R")

If one is working in an English locale (or other locale without a representation for these characters), then the attempt to open the file fails outright.

If one is working in a Chinese locale, the file is created, but the name is garbage characters.

![screen shot 2017-12-18 at 10 37 36 am](https://user-images.githubusercontent.com/1976582/34121907-7fe54b2a-e3df-11e7-8a4f-a8f87bf73e52.png)

**Comment by kevinushey** [comment]
Everything works fine through the regular system dialogs, so this bug is relatively low priority. (However, I often use `file.edit()` just to avoid the overhead of using system UI; I imagine other users do this as well)

**Comment by kevinushey** [comment]
Should be resolved with https://github.com/rstudio/rstudio/commit/2cdd405236e4c09d2de97637f668108e98f98aac.

**Comment by dfalty** [comment]
I actually still see the failure when trying `file.edit("你好.R")` on win 10 1.2.1090. Reopening.
