### ISSUE TITLE
Handle base64 downloads with Qt WebEngine

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2031]
Re: https://github.com/rstudio/rstudio/pull/1720/files#diff-9562ed3ecf90801a6d3b8bdf61c5078eR276

**Comment by kevinushey** [comment]
I investigated this a little bit. It looks like things 'just work' with `QWebEnginePage::download()`, e.g.

https://doc.qt.io/qt-5/qwebenginepage.html#download

We may need to respond to the `downloadRequested()` signal to accept the download request(s) somewhere:

https://doc.qt.io/qt-5/qwebengineprofile.html#downloadRequested

**Comment by jmcphers** [comment]
Is this fixed by https://github.com/rstudio/rstudio/commit/7fb3b4fbf18643b2cd1f38120044049de77ee106?

**Comment by kevinushey** [comment]
Not quite yet. We still have the old base64 download logic here:

https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopWebPage.cpp#L285-L288
https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopWebPage.cpp#L315-L406

But I think that whole code path might be unnecessary now. (You mentioned this might've been added for handling Shiny download buttons, but I'm curious if there's anything else -- maybe downloading of embedded R source in R Markdown documents?)

@jjallaire, do you by any chance recall what the `handleBase64Download()` code path was for (just so we can be sure of how to test this)? It looks like it was added quite a while back:

https://github.com/rstudio/rstudio/commit/e955d757d24c870ca1d3fa368fe17f4880c87cf3

**Comment by jjallaire** [comment]
Believe it or not I believe that was for downloading PNG versions of ggvis visualizations! (they had a standard download as PNG/SVG button in their top right corner).

**Comment by kevinushey** [comment]
It looks like those download attempts do indeed 'just work' with QWebEngine so I think we can remove some of this code.
