### ISSUE TITLE
Opening and saving markdown files results in empty files. RStudio Daily 1.2.353. 

### ISSUE THREAD

**Issue by Nzteb** [rstudio/rstudio#2231]
### System details

    RStudio Edition : Dekstop
    RStudio Version : 1.2.353
    OS Version      :  Windows 10 x64
    R Version       : 3.4.3 (2017-11-30)

### Steps to reproduce the problem
Install RStudio 1.2.353
Open a nonempty markdown file

### Describe the problem in detail
When I open a nonempty markdown file, the corresponding file in RStudio is empty.
On the other hand, when I code into an empty markdown file and save it. The saved file will be an empty markdown file (e. g. when opening with a text editor).

**Comment by ronblum** [comment]
@Nzteb Thank you for raising this. I am able to reproduce the first issue, which means that on Windows, a .Rmd file created by RStudio, closed, then reopened will be blank. 

Note: this is not an issue with .R and .Rnw files.

**Comment by kevinushey** [comment]
I believe this should be resolved in the latest daily builds.

**Comment by majidalzein** [comment]
Hi Everyone,
My .Rmd file is blank and i am unable to reopen it with content.
I tried to re-open with Encoding however i am still unable to see any content...

Any chance someone can help :( this is super important...

Majid

**Comment by kfeinauer** [comment]
@majidalzein What version of RStudio are you using? Have you tried the latest release? (1.2.1335).

**Comment by majidalzein** [comment]
hi Kfeinauer,
Thank you SO MUCH for getting back to me, i am desperate at this point to salvage the file.
The R Studio version used is: 1.2.1335 yes.

I just went back to check some previous files and my entire .rmd files created and saved locally are showing 0KB :(

**Comment by kfeinauer** [comment]
@majidalzein You can attempt to recover them if they are still sitting around in `%LOCALAPPDATA\RStudio-Desktop\sources`. 

If you create new RMD files, save them, and then reopen them, are they empty? Or is this just when you try to open a few older files that you may have worked on in a previous version of RStudio?

**Comment by majidalzein** [comment]
Hi Karl,
I have uninstalled Anaconda environment and did a fresh install of R Studio.
So now i can create, save and open .RMD files. Unfortunately all my previous files created and saved while using Anaconda environment are now 0KB...

checking Sources and will revert back ASAP

**Comment by majidalzein** [comment]
Hi Karl,
All sources have 3bytes files, seems like all the work is gone...
Any other recommendation on how i can salvage files from Anaconda environment after deletion?

**Comment by kfeinauer** [comment]
Unfortunately at this point I think your files are unrecoverable.

**Comment by majidalzein** [comment]
Hi Karl,
I did some digging, i was able to find some more history under /RStudio-Desktop/history_database
This allowed me to put back together some of my latest work, however all other files are gone at this point.

thank you for trying,
Majid
