### ISSUE TITLE
Double-clicking on associated text file (e.g. .R and .Rmd) opens RStudio but not the file

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2238]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.353
    OS Version      : Windows 10
    R Version       : 3.4.3

### Steps to reproduce the problem

Double-click on an file with a known R extension, e.g. .R or .Rmd, that is associated with RStudio.

### Describe the problem in detail

RStudio launches (as long as the file is associated with RStudio). However, the file isn't opened. Instead, RStudio starts up in the last state it was in, with the source pane showing the last tab/window in focus.

### Describe the behavior you expected

The file that was double-clicked should be opened and should be the focus in the source pane.

Note: this worked in 1.1.423, as well on Mac Desktop 1.2.353.

**Comment by ronblum** [comment]
This is only partly working. If RStudio is closed, double-clicking starts RStudio and opens the file. But double-click on files when RStudio is running doesn't open them. Note that clicking on Rproj files does work, though.

Tested on 1.2.894.

**Comment by ronblum** [comment]
Confirmed!

**Comment by Nova-Scotia** [comment]
I'm still having a related issue.

RStudio Edition : Desktop
RStudio Version: Current - RStudio/2023.12.0+369
OS Version      : Windows 10 Professional x64
R Version       :  4.2.3

Works: opening .R or .Rmd file from Windows Explorer when RStudio is closed (this will trigger RStudio to open)
**Doesn't work**: If RStudio is open, then I try to double-click on a .R or .Rmd file to open it from Windows Explorer.

I have checked and those file extensions do have RStudio as the default program to open them. Any ideas? Really frustrating.

**Comment by jlang-311** [comment]
Need to verify if this was fixed in 2024.12.1

**Comment by gtritchie** [comment]
This should be fixed in the 2024.12.1 release; see https://github.com/rstudio/rstudio/issues/15536 for details.

**Comment by Nova-Scotia** [comment]
I'm still seeing this issue unfortunately 😢

RStudio Edition : Desktop
RStudio Version: Current - 2025.05.0 Build 496
OS Version : **Windows** 10 Professional x64
R Version : 4.4.2 (2024-10-31 ucrt)
