### ISSUE TITLE
`library(tidyverse)` makes RStudio crash

### ISSUE THREAD

**Issue by juba** [rstudio/rstudio#2247]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423
    OS Version      : Linux KDE Neon User Edition 5.12
    R Version       : 3.4.3

### Steps to reproduce the problem

With the latest RStudio and `tidyverse` packages installed, launching `library(tidyverse)` makes RStudio crash directly with the message `Floating point exception (core dumped)`.

I believe this is due to the message displayed by `tidyverse` when loading it, more specifically by the checkmark symbols, because : 

- if I load every tidyverse package individually and then run `library(tidyverse)`, everything is working fine (and no message is displayed)
- if I load every tidyverse package individually except one, RStudio crashes when the message must be displayed
- if I change my locale with something like `Sys.setlocale("LC_ALL","C")`, then `library(tidyverse)` works fine, but the message is displayed without the checkmarks (they are replaced by the sequence `<U+221A>`).

Here is my `sessionInfo()` : 

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: KDE neon User Edition 5.12

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    parallel_3.4.3 yaml_2.1.16 
```

Thanks a lot in advance.

**Comment by juba** [comment]
I forgot to mention that everything works fine in R outside of RStudio. But if I launch R in a terminal inside RStudio, running `library(tidyverse)` triggers a crash too.

**Comment by juba** [comment]
That's a RStudio crash, as everything works fine outside of RStudio, and the only message I get when RStudio is launched is, as mentioned, `Floating point exception`.

I tried reinstalling the tidyverse package but that doesn't solve the problem. The only workaround is to load every tidyverse package individually and, then, the tidyverse package itself.

I really think it is linked to the message displayed when tidyverse is loaded, more specifically the checkmate symbol...

**Comment by juba** [comment]
That's a RStudio crash, as everything works fine outside of RStudio, and the only message I get when RStudio is launched is, as mentioned, `Floating point exception`.

I tried reinstalling the tidyverse package but that doesn't solve the problem. The only workaround is to load every tidyverse package individually and, then, the tidyverse package itself.

I really think it is linked to the message displayed when tidyverse is loaded, more specifically the checkmark symbol...

**Comment by kevinushey** [comment]
Sorry, I think I misread and though you said running R in a terminal _outside_ of RStudio caused the crash.

Any chance you could provide us with a stack trace / core dump? I'm not sure whether it's the `rstudio` or `rsession` process that's crashing, but you could try launching RStudio from the terminal with something like:

```sh
sudo gdb rstudio
continue
```

and see if `gdb` is able to catch the crash and provide more information. (You can print the backtrace using `bt` from the gdb REPL)

**Comment by juba** [comment]
Here it is :

```
#0  0x00007fffeab68104 in QFontEngineFT::averageCharWidth() const () from /usr/lib/rstudio/bin/plugins/platforms/libqxcb.so
#1  0x00007ffff6e94f78 in QRawFont::averageCharWidth() const () from /usr/lib/rstudio/bin/libQt5Gui.so.5
#2  0x00007ffff50f378c in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#3  0x00007ffff4f90a27 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#4  0x00007ffff50f2c6c in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#5  0x00007ffff4f77095 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#6  0x00007ffff4fc6836 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#7  0x00007ffff4fc6f96 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#8  0x00007ffff4fcd51b in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#9  0x00007ffff4f91ef4 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#10 0x00007ffff4f8bf45 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#11 0x00007ffff5cb5d3e in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#12 0x00007ffff5cb7ca2 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#13 0x00007ffff5c842f4 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#14 0x00007ffff5c88569 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#15 0x00007ffff5c8951e in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#16 0x00007ffff5c52f4e in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#17 0x00007ffff5c12463 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#18 0x00007ffff5c54635 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#19 0x00007ffff5c89595 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#20 0x00007ffff5c52f4e in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#21 0x00007ffff5cc181a in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#22 0x00007ffff5c12463 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#23 0x00007ffff5c7ef73 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#24 0x00007ffff5c7f92d in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#25 0x00007ffff5c7ffb1 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#26 0x00007ffff5c53e5d in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#27 0x00007ffff5c12463 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#28 0x00007ffff5cefc70 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#29 0x00007ffff5d3f760 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#30 0x00007ffff5ce44d8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#31 0x00007ffff5d17743 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#32 0x00007ffff5d3e12f in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#33 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#34 0x00007ffff5ce44d8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#35 0x00007ffff5d17743 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#36 0x00007ffff5d3e12f in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#37 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#38 0x00007ffff5ce44d8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#39 0x00007ffff5d17743 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#40 0x00007ffff5d3e12f in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#41 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#42 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#43 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#44 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#45 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#46 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#47 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#48 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#49 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#50 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#51 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#52 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#53 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#54 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#55 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#56 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#57 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#58 0x00007ffff5d1aa95 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#59 0x00007ffff5d3dbb4 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#60 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#61 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#62 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#63 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#64 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#65 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#66 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#67 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#68 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#69 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#70 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#71 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#72 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#73 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#74 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#75 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#76 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#77 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#78 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#79 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#80 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#81 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#82 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#83 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#84 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#85 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#86 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#87 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#88 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#89 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#90 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#91 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#92 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#93 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#94 0x00007ffff5d1aa95 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#95 0x00007ffff5d3dbb4 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#96 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#97 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#98 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#99 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#100 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#101 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#102 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#103 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#104 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#105 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#106 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#107 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#108 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#109 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#110 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#111 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#112 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#113 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#114 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#115 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#116 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#117 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#118 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#119 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#120 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#121 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#122 0x00007ffff5cd6ab0 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#123 0x00007ffff5d3dae7 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#124 0x00007ffff5d3e0e8 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#125 0x00007ffff5c6e915 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#126 0x00007ffff5c6f189 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#127 0x00007ffff5cc223a in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#128 0x00007ffff4f3f94b in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#129 0x00007ffff5024f99 in ?? () from /usr/lib/rstudio/bin/libQt5WebKit.so.5
#130 0x00007ffff7baa2f3 in QObject::event(QEvent*) () from /usr/lib/rstudio/bin/libQt5Core.so.5
#131 0x00007ffff735d0fc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/rstudio/bin/libQt5Widgets.so.5
#132 0x00007ffff7362790 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/rstudio/bin/libQt5Widgets.so.5
#133 0x00007ffff7b78ddb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/rstudio/bin/libQt5Core.so.5
#134 0x00007ffff7bcec5d in QTimerInfoList::activateTimers() () from /usr/lib/rstudio/bin/libQt5Core.so.5
#135 0x00007ffff7bcf199 in ?? () from /usr/lib/rstudio/bin/libQt5Core.so.5
#136 0x00007ffff2296197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#137 0x00007ffff22963f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#138 0x00007ffff229649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#139 0x00007ffff7bcfe3f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/rstudio/bin/libQt5Core.so.5
#140 0x00007ffff7b7664a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/rstudio/bin/libQt5Core.so.5
#141 0x00007ffff7b7e17c in QCoreApplication::exec() () from /usr/lib/rstudio/bin/libQt5Core.so.5
#142 0x00000000005ab5bb in main ()
```

**Comment by kevinushey** [comment]
Thanks for the stack trace! It looks like Qt is not handling your font correctly (if I understand correctly, it's effectively crashing while determining the character width of the default system font).

Would you be willing to test the latest daily builds, from https://dailies.rstudio.com?

**Comment by juba** [comment]
Yes, this is definitely a font related problem. Most Editor fonts trigger a crash, but if I switch to `Menlo`, for example, the issue doesn't appear.

I just tried with the daily build 1.2.243, but unfortunately the problem is still there...

**Comment by juba** [comment]
Hi,

I think this has been fixed in a recent Qt update. Anyway I can't reproduce it anymore on my system. So it may be safe to close the issue.

Thanks !

**Comment by jcpsantiago** [comment]
rstudio is still crashing for me, version 1.1.453 on Arch Linux and Gnome. Hasklig and Fira Code trigger this, but not Monospace.

**Comment by jmcphers** [comment]
This crash is in QtWebKit, which we no longer use. RStudio now uses QtWebEngine.
