### ISSUE TITLE
No output from system() in the R console (only in certain cases)

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#2248]
### System details

```
> devtools::session_info()
Session info ------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2018-02-21                  

Packages ----------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.3   2017-12-07 local         
 compiler    3.4.3   2017-12-07 local         
 datasets  * 3.4.3   2017-12-07 local         
 devtools    1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)
 graphics  * 3.4.3   2017-12-07 local         
 grDevices * 3.4.3   2017-12-07 local         
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods   * 3.4.3   2017-12-07 local         
 stats     * 3.4.3   2017-12-07 local         
 tools       3.4.3   2017-12-07 local         
 utils     * 3.4.3   2017-12-07 local         
 withr       2.1.1   2017-12-19 CRAN (R 3.4.3)
 yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)
```

### Steps to reproduce the problem

```r
# blogdown::install_hugo() if Hugo was not installed
# cd to an empty directory (doesn't have to be tempdir)
setwd(tempdir())
dir.create('test-hugo')
setwd('test-hugo')

# a minimal hugo site
writeLines('baseurl = "/"', 'config.toml')
dir.create('content')

system('hugo')  # if hugo not on PATH, run blogdown::hugo_build() instead
```

### Describe the problem in detail

No output in the R console.

### Describe the behavior you expected

If I run `hugo` in a terminal, I can see output:

```
$ hugo

                   | EN
+------------------+----+
  Pages            |  3
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 16 ms
```

If I `file.remove('config.toml')` and run hugo again, I can see the error message:

```
> system('hugo')
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Config File "config" Not Found in "[....]")
```

This might be related to #1916. I'm not sure if the output (stdout or stderr) contains special characters that confused RStudio.

Originally reported at https://github.com/rstudio/blogdown/issues/257, in which case the Hugo errors should have been displayed in the console, but for some reason, they were not.

**Comment by kevinushey** [comment]
I can reproduce this as well. For what it's worth, input is captured with `intern = TRUE`, and I see:

```R
> system('hugo', intern = TRUE)
 [1] "\033[?25lBuilding sites … \033[?25h\r\033[K" "                   | EN  "                  
 [3] "+------------------+----+"                   "  Pages            |  3  "                  
 [5] "  Paginator pages  |  0  "                   "  Non-page files   |  0  "                  
 [7] "  Static files     |  0  "                   "  Processed images |  0  "                  
 [9] "  Aliases          |  0  "                   "  Sitemaps         |  1  "                  
[11] "  Cleaned          |  0  "                   ""                                           
[13] "Total in 11 ms"        
```

I think the escape sequences are confusing our console:

```R
> output <- paste(system('hugo', intern = TRUE), collapse = "\n")
> cat(output)
> 
```

since even attempting to write out the captured output fails.

**Comment by kevinushey** [comment]
Output is shown in v1.0, so it appears this is a regression (although the escape codes are not shown correctly)

```R
> system('hugo')  # if hugo not on PATH, run blogdown::hugo_build() instead
[K25lBuilding sites … [?25h
                   | EN  
+------------------+----+
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 12 ms
```

**Comment by gtritchie** [comment]
Confirmed this is related to escape-sequence handling added in RStudio 1.1. Will look at fixing; in the meantime there is a partial workaround; set the console `ANSI Escape Codes` mode to Ignore ANSI codes (1.0 behavior) as shown in screenshot. The raw escape codes will still be shown, but at least the text renders.

![2018-03-07_20-08-14](https://user-images.githubusercontent.com/10569626/37132656-a06d8446-2243-11e8-88b0-7f0ebdf0eeff.png)

![2018-03-07_20-09-05](https://user-images.githubusercontent.com/10569626/37132672-b7b13378-2243-11e8-8fc9-ab4fa9cb64c9.png)

**Comment by gtritchie** [comment]
As I suspected, the problem is that the console support for ANSI codes in 1.1 (which I wrote) is limited to color and font-related sequences. Those are of the form: **ESC[...m**. 

The console does not support (and gets confused by) any other ANSI codes, including the ones being output by hugo (**ESC[?25l** to hide the cursor, **ESC[?25h** to show the cursor, and **ESC[K** to erase line).

The console parser sees the opening ESC, and uses a regular expression to match valid ANSI codes, then tries to find a color code. The regex matches all ANSI codes, not just the ones the console supports, so console ends up waiting for more input, trying to find the end of a color sequence. This never arrives and all the output is treated as an unsupported ANSI code and discarded.

**Comment by jananiravi** [comment]
I have installed Hugo/blogdown but when I run `hugo -v` in the RStudio terminal, I get the error:

> bash: hugo: command not found

Any suggestions on how I can fix this? I would like this command to work so that I can view any hidden errors that aren't allowing update of my webpage created locally using Hugo-academic. thanks!

**Comment by yihui** [comment]
@jananiravi The issue was fixed in the daily build of RStudio: https://dailies.rstudio.com

If you don't wan to test the daily build, you will need to start a separate R session and use `blogdown::serve_site()` there. You didn't say it, but you are probably using Windows, in which case you can probably find R from the Start menu.

**Comment by jananiravi** [comment]
Thanks, @yihui I am using RStudio on Mac.
I still see the following error with the new RStudio.

> Building sites … ERROR 2018/05/08 11:58:13 Failed to render "theme/publication/single.html": runtime error: invalid memory address or nil pointer dereference
Serving the directory /Users/janani/Google_Drive/Personal/AJ/jananiravi at http://127.0.0.1:4321
To stop the server, run servr::daemon_stop("140699771731016") or restart your R session

And I see the ftp-like rendering of the webpage:
![image](https://user-images.githubusercontent.com/8397074/39768492-70dadb12-52b7-11e8-8e0e-99abc3f06fdf.png)

**Comment by yihui** [comment]
@jananiravi That became a Hugo issue. Honestly I don't understand the error message. Perhaps you can ask on the Hugo forum https://discourse.gohugo.io or ask the theme author.

The ftp-like page was due to the failure for Hugo to render the site. There was no `index.html` under `public/`, so the list of files/dirs is displayed instead.

**Comment by jananiravi** [comment]
Thanks again @yihui I don't understand these missing files issue as well. The instructions suggested that I clear the public folder out before rendering again using build_site() and serve_site() to have a clean start, especially when there are issues like these. I have posted my concern on discourse.gohugo.io now as well. I will also approach the hugo-academic author @gcushen regarding this. Hopefully, there will be resolution soon.

Also, I followed your suggestion from the [other thread on serve_site](https://github.com/rstudio/blogdown/issues/292). If I uninstall the command line homebrew installed version of hugo, build_site() results in an errror since `sh hugo` fails (`sh: hugo: command not found`). I've reinstalled using `brew install hugo` and it seems fine, barring the usual missing files 'failed to render runtime' errors.

**Comment by yihui** [comment]
@jananiravi For the error message `sh: hugo: command not found`, it indicates that you need to restart R after you followed the suggestion from https://github.com/rstudio/blogdown/issues/292 (but you probably don't have to install Hugo that way, since your issue appears to be different).

**Comment by jananiravi** [comment]
OK, I thought it did that, but will keep that in mind for next time! As you said, Hugo installation isn't my problem area for the time being. I will post the serve_site() solution once it's been fixed. thanks again.

**Comment by jananiravi** [comment]
@yihui here's the fix: https://github.com/gcushen/hugo-academic/issues/534 Now it works!
