### ISSUE TITLE
'Save file' message box always shows on main window

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2516]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.473
    OS Version      : macOS 10.13.3
    R Version       : 3.4.4

### Steps to reproduce the problem

Within a popped-out source window, attempt to quit while an open file contains unsaved changes.

### Describe the problem in detail

The dialog informing the user of unsaved files is displayed on the main window, rather than the satellite window.

### Describe the behavior you expected

The dialog should show on the window associated with the unsaved document.

![screen shot 2018-03-27 at 10 51 00 am](https://user-images.githubusercontent.com/1976582/37985096-c4d9b354-31ac-11e8-802a-e6e6cc046e02.png)

**Comment by kevinushey** [comment]
Fixed via https://github.com/rstudio/rstudio/pull/2518.

**Comment by vnijs** [comment]
Seems this may be related to https://github.com/rstudio/rstudioapi/issues/91. Still seeing this issue with 1.2.502 in Windows 10

**Comment by ronblum** [comment]
Verified RStudio Desktop 1.2.914 on MacOS 10.14 Mojave and Windows 10, RStudio Server 1.2.915 on Ubuntu 16.0.4.5 with Chrome 68 from MacOS.
