### ISSUE TITLE
R will not open properly after Windows Update

### ISSUE THREAD

**Issue by ruimikec** [rstudio/rstudio#2802]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1423

### Describe the problem in detail
Opening Rstudio leads to a blank R program window and a "Download File" window, which tries to save a blank file on your computer. The file has nothing on it. I have reinstalled RStudio and I have tried past versions as well. Nothing seems to work. Windows update is [Windows 10, version 1803].

If you do save a file or if you cancel - the entire program closes. Rinse and repeat.

I appreciate any feedback

**Comment by YourBrain** [comment]
Same here - RStudio 1.1.423 on Windows Pro, version 1803  
Installed via Anaconda. problem exists even after complete uninstall/reinstall of RStudio & Anaconda.
R v3.4.3 launches find via command line.

**Comment by JayKay0104** [comment]
I encountered the same issue right now.

Using Anaconda - RStudio 1.1.423
OS Name	Microsoft Windows 10 Home
Version 10.0.17134 Build 17134

downgrading RStudio version does not help.

**Comment by jmcphers** [comment]
Does upgrading help? We're now on RStudio 1.1.453. 

https://www.rstudio.com/products/rstudio/download/

**Comment by Andreas-Born** [comment]
Same problem here, installed the newest version over the link from jmcphers above - doesnt make a difference unfortunately

**Comment by PabRod** [comment]
Same problem here.

Using Anaconda 1.8.5 - RStudio 1.1.423
Windows 10 Home. Version 1803. Build 17134.48.

**Comment by Andreas-Born** [comment]
I could solve the problem by changing the version of R RStudio is using from 64 to 32 bit.

**Comment by PabRod** [comment]
I've just tried @Andreas-Born solution. Unsuccessfully. I experience the same problem with the 32 bit version.

**Comment by jmcphers** [comment]
We think this might be an issue introduced with Windows 1803, and that we have a fix in the daily builds of RStudio. Would any of you who are still experiencing this issue be willing to try a daily build to see if it fixes the problem for you?

https://dailies.rstudio.com/

**Comment by Andreas-Born** [comment]
Can confirm that the issue came up after updating to Windows 1803. Can also confirm @PabRod. Something else must have fixed it, i can switch back to 64bit and run RStudio no probs...

**Comment by ruimikec** [comment]
@jmcphers The daily build that you linked worked for me. It's separate from using anaconda, but it still holds my temp files from the other Rstudio I have so I don't mind. @Andreas-Born switching to 32-bit doesn't work for me, still in limbo currently but I guess I'm fine for now.

Thanks everyone for your help!

**Comment by mingwandroid** [comment]
Hi,

Ray from the Anaconda Distribution here. Can someone provide a reference to the fixing commit in the 1.1 branch and also the 1.2 branch please?

**Comment by mingwandroid** [comment]
Thanks a lot. I'll look into getting rebuilds done with this applied. BTW is there anyb tentative date for the 1.2 release?

**Comment by gtritchie** [comment]
1.2 is still a ways out for official release, no date set. Lots of testing still to do, and still have some feature work happening. Would expect within this calendar year, though.

**Comment by mingwandroid** [comment]
Thanks for the info.

**Comment by waisman86** [comment]
Hi everyone! I am experencing the same problem. Rstudio installed via Anaconda won´t launch, I only get the pop up window "download file". Has anyone been able to solve this? Thanks a lot

**Comment by muba1** [comment]
same issue with windows 10 , anaconda but not in the mac.

**Comment by pesobreiro** [comment]
I have the same issue. There is a solution or the option is working in Linux? :-) Windows version 1803.

**Comment by waisman86** [comment]
I just uninstalled the package from the Anaconda navigator and then downloaded and installed RStudio from its homepage and it worked. Hope that helps

**Comment by pesobreiro** [comment]
Tried to remove from anaconda navigator and doesn't remove. Then executed conda uninstall rstudio, and installed as suggested and worked. Thanks.

**Comment by kevinushey** [comment]
FWIW, we're planning to drop support for 32-bit versions of R in the next release of RStudio.

**Comment by ronblum** [comment]
@mingwandroid There's a [new release, 1.1.456](https://www.rstudio.com/products/rstudio/download/), available which includes a fix for this issue. Are you able to use it and confirm that the problem is fixed?

**Comment by mohansran** [comment]
Rstudio installed via Anaconda won´t launch, I only get the pop up window "download file".
Rstudio v1.1.423
Anaconda Navigator 1.8.7

Does anybody able to fix this issue?

**Comment by suebose012** [comment]
Ran into same problem. I then did a conda update to RStudio v1.1.423, issue persists.
I have Anaconda Navigator 1.6.2.

**Comment by ttmmghmm** [comment]
Hi,

I tried installing 1.2.909 and have a blank black screen when Rstudio startsup.
The drop down menu seem to be working 
e.g. Help - check for updates pops up a window 'you are using the newest version of Rstudio.

Help - Help Diagnostics - Write Diagnostics Report contains the error

17 Aug 2018 15:23:51 [rdesktop] ERROR system error 3 (The system cannot find the path specified) [path=C:/etc/RStudio_1.2.909/bin/resources/stylesheets/rstudio-windows-light.qss]; OCCURRED AT: auto __cdecl rstudio::core::FilePath::open_r::<lambda_d4246793555dd4e209de8cc0cf7ef3ce>::operator ()(void) const c:\jenkins\workspace\ide\windows\src\cpp\core\filepath.cpp:1072; LOGGED FROM: void __cdecl rstudio::desktop::applyDesktopTheme(class QWidget *,bool) c:\jenkins\workspace\ide\windows\src\cpp\desktop\desktoputils.cpp:145
17 Aug 2018 15:23:51 [rdesktop] ERROR system error 3 (The system cannot find the path specified) [path=C:/etc/RStudio_1.2.909/bin/resources/stylesheets/rstudio-windows-light.qss]; OCCURRED AT: auto __cdecl rstudio::core::FilePath::open_r::<lambda_d4246793555dd4e209de8cc0cf7ef3ce>::operator ()(void) const c:\jenkins\workspace\ide\windows\src\cpp\core\filepath.cpp:1072; LOGGED FROM: void __cdecl rstudio::desktop::applyDesktopTheme(class QWidget *,bool) c:\jenkins\workspace\ide\windows\src\cpp\desktop\desktoputils.cpp:145

C:/etc/RStudio_1.2.909/bin/resources exists
C:\etc\RStudio_1.2.909\bin\resources\stylesheets did not exist, so I copied it from 
C:\etc\RStudio_1.2.909\resources\stylesheets

Now C:/etc/RStudio_1.2.909/bin/resources/stylesheets/rstudio-windows-light.qss exists,
to address the error in the Diagnostic report 
but regenerating the report still leaves the same error message (and Rstudio is still blank (all black).)

I tried replacing the contents of rstudio-windows-light.qss (which is empty to pickup the default)
with the contents of some the other qss files in that folder
e.g. rstudio-gnome-dark.qss
But again no change.

I also tried some of the suggestions above 
e.g. switching (by pressing control after starting Rstudio) to 32-bit R
Again no change.

Other suggestions welcome.

John.

**Comment by ronblum** [comment]
@ttmmghmm This is a separate issue. The problem being discussed in this ticket is specific to RStudio 1.1 with Anaconda. The problem you've run into appears to be a different with the daily 1.2 builds that are currently in development. Could you open a new ticket, including your system details (such as version of Windows and R), so that we can review it? Thanks!

**Comment by andystats** [comment]
> We think this might be an issue introduced with Windows 1803, and that we have a fix in the daily builds of RStudio. Would any of you who are still experiencing this issue be willing to try a daily build to see if it fixes the problem for you?
> 
> https://dailies.rstudio.com/

This completely worked for me!

**Comment by william3031** [comment]
I have had the same issue today. Downloading the daily build fixed it. https://dailies.rstudio.com/

**Comment by mohdshooqur** [comment]
had same issue any permanent solution ?

**Comment by ronblum** [comment]
@mohansran The current version of RStudio is 1.2.5001 which is available [here: https://www.rstudio.com/products/rstudio/download](https://www.rstudio.com/products/rstudio/download) . The Anaconda installation is using version 1.1.456, although that works when installed on its own.

That said: @mingwandroid Ray, the current RStudio version is 1.2.5001. Both the installers and zip files are available at https://www.rstudio.com/products/rstudio/download .

**Comment by mdugule** [comment]
When I try to open Rstudio it opens an infinite number of Rstudio windows. How can I solve this? I tried uninstalling and reinstalling RStudio.
