### ISSUE TITLE
Text scaling on Windows 10 doesn't seem to work at 125%

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2914]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.679
    OS Version      : Windows 10
    R Version       : 3.5.0

### Steps to reproduce the problem

When changing system-level display scaling from 100% to 125% to 150%, RStudio seems to use the same text zooming at 100% and 125%, even though other apps change.

This is the dialog that sets the zoom:

![image](https://user-images.githubusercontent.com/86978/40940769-774e63f8-680e-11e8-9943-7958ec2198a5.png)

Here are screenshots at different zoom levels. Note that you might need to open up each image and scale to 100% to get a good feel for it. When I changed zoom levels, Windows also resized some windows, so the screenshots don't have the same pixel dimensions and therefore are scaled differently in the Github issue tracker.

Here it is at 100% (Chrome on the left, RStudio on the right):

![image](https://user-images.githubusercontent.com/86978/40940752-6a171b12-680e-11e8-8138-fc4646532891.png)

125%:

![image](https://user-images.githubusercontent.com/86978/40940802-901b8ea6-680e-11e8-9291-c0315db2092c.png)

150%:

![image](https://user-images.githubusercontent.com/86978/40940831-a2108b0c-680e-11e8-968b-bb982502a9ee.png)

My desired zoom ratio is 125%, but the text in RStudio is too small. at 150% it's too big.

**Comment by ronblum** [comment]
Reproduced with RStudio 1.2.679-1 and 1.1.453. Note that the menu items (File, Session, etc.) do increase size at 125.%.

**Comment by tlmcmurry** [comment]
I am also having RStudio scaling issues.  Currently using
Rstudio: 1.2.5033
R: 3.6.2
Windows 10
1080p Resolution
150% System Scaling

With Rstudio version < 1.2, the resolution looked reasonable.  Now 75% zoom is too much and 50% is too little. 

Rstudio also reacts very strangely to system scaling.  Here is 100% Rstudio zoom and 150% system scaling:
![Screenshot (5)](https://user-images.githubusercontent.com/49213784/71538085-f5d42200-28ea-11ea-9c8d-5742c8d5defb.png)

Here is 100% Rstudio zoom and 125% system scaling
![Screenshot (6)](https://user-images.githubusercontent.com/49213784/71538093-18663b00-28eb-11ea-816c-51c8ee373af4.png)

**Comment by woodwards** [comment]
I'm having the same problem? No one interested in fixing accessibility issues?

**Comment by MariaSemple** [comment]
@wch Confirmed this is still an issue.

**Comment by ronblum** [comment]
Verified fixed by Electron in RStudio Desktop 2022.11.0+101 on Windows 11. Everything works correctly at 100%, 125%, 150%, and 175%.

**Comment by alohacocoa** [comment]
> Verified fixed by Electron in RStudio Desktop 2022.11.0+101 on Windows 11. Everything works correctly at 100%, 125%, 150%, and 175%.

I am still having this issue on Windows 10. Does the fix only work on the newer OS?

**Comment by mcarauta** [comment]
I am still having this issue as well. Windows 10 (OS build 19044.2130) and RStudio Version 1.4.1717
