### ISSUE TITLE
Error in as.POSIXct.default(time2): do not know how to convert 'time2' to class “POSIXct”

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#3305]
RStudio Server will produce the following error messages if the session is left idle for a while:

```r
Error in as.POSIXct.default(time2) : 
  do not know how to convert 'time2' to class “POSIXct”
```

### System details

    RStudio Edition : RStudio Server
    RStudio Version : 1.2.867
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.1

**Comment by kevinushey** [comment]
This should already be fixed in the latest daily builds.

**Comment by ronblum** [comment]
@renkun-ken Is the problem still occurring, or does it appear to be resolved?

**Comment by renkun-ken** [comment]
In 1.2.907, this error no longer appears any more. Thanks!

**Comment by ronblum** [comment]
Great—glad to hear it, and thank you for the update!
