### ISSUE TITLE
Cursor offset when using tabs

### ISSUE THREAD

**Issue by etiennebr** [rstudio/rstudio#4295]
### System details

    RStudio Edition : All
    RStudio Version : 1.1.463
    OS Version      : Ubuntu 18.04.1
    R Version       : 3.5.2 

### Steps to reproduce the problem
In a project using 4-space-width `tab` i.e. unchecked `Insert spaces for tab` option in the project options > Code editing thumb. I'll use `sf` as an example:

* Clone the project
```
git clone https://github.com/r-spatial/sf.git
```
* Open `sf.Rproj`
* `ctrl+.` and open the `geos_op2_geom` function (or any function using tabs).
* On line 878, go to the end of the line (`End`)
* The cursor does not reach the end of line. 
* Type letters and they do not appear right after the cursor, but at the end of line (where the cursor should be). 

### Describe the problem in detail
* The cursor doesn't seem to account for the 4-space width of the tabs.
![peek_rstudio](https://user-images.githubusercontent.com/393576/52608486-2b455d80-2e48-11e9-81b9-28a4e4285f24.gif)

### Describe the behavior you expected
The cursor should be after the last character of the line (when at the end of the line) and right before the first character when at the beginning of the line.

**Comment by pascaloettli** [comment]
I can reproduce in version `1.1.463` on Ubuntu `18.04.1` when the option _Show whitespace characters_ is selected. It doesn't occur in the preview version `1.2.1268`, even with this option. So I guess version `1.2` solves this problem.

**Comment by ronblum** [comment]
@pascaloettli Thank you for reporting this and confirmed that it's fixed in 1.2.1268. I'll closed the issue as resolved, but having this issue available will help with anyone else who runs into this issue.

**Comment by etiennebr** [comment]
I still observe the behavior in version 1.2.1511 (`Build 15 (8add310b, 2019-04-23)`) when *Show whitespace characters* is selected. It's fine when the option is not selected or in projects that use spaces.

**Comment by pascaloettli** [comment]
Sorry to hear you still face this problem. Using the same version (`1.2.1511, Build 15 (8add310b, 2019-04-23)`), I can reproduce this behaviour. If I go to the start of the line `message_longlat(paste0("st_", op))` and hit the <kbd>End</kbd> key, the cursor goes to the right place.

![Peek 2019-06-03 11-20](https://user-images.githubusercontent.com/6613954/58771977-fc6b1700-85f1-11e9-86cb-ccbabc39a9fe.gif)

![Screenshot from 2019-06-03 11-26-12](https://user-images.githubusercontent.com/6613954/58772105-74394180-85f2-11e9-8876-e8947c2693d8.png)

**Comment by kevinushey** [comment]
@etiennebr what font are you using? Can you reproduce with other fonts / themes?

**Comment by etiennebr** [comment]
Ah, it seems to only be related to *ubuntu mono* font, for any size and zoom. But I could not reproduce with any other font available on my system. I've added a few tabs for a more dramatic effect, since the offset is smaller than in the previous 1.1 version.
![Peek 2019-06-03 20-40](https://user-images.githubusercontent.com/393576/58843347-1a5f6880-8640-11e9-90b7-1e9193973a6c.gif)

**Comment by pascaloettli** [comment]
I reproduce with the same font, _ubuntu mono_.

**Comment by kevinushey** [comment]
Thanks. It looks like this issue is resolved in the [daily builds](https://dailies.rstudio.com) of RStudio, and since the issue only manifests when the user is requesting whitespace characters be shown, I think it's okay to close this.
