### ISSUE TITLE
shinytest does not run or load the Shiny app on RStudio Server

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4555]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335-1
    OS Version      : Red Hat 7.6, Ubuntu 18.04
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create a Shiny app
2. Record it using either 
    - `recordTest("path/to/app")`
    - Little drop down arrow next to "Run App" -> Record Test
### Describe the problem in detail

On Ubuntu 18.04, the following error appears in the console:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 127.0.0.1 port 4808: Connection refused
```

On Red Hat 7.6, the window opens with the test control panel, but the main panel with the Shiny app has a sad face and the message `127.0.0.1 refused to connect.`

<img width="841" alt="sad_shinytest" src="https://user-images.githubusercontent.com/31009952/55366480-ef795c80-54b6-11e9-98f8-81b18fec300d.png">

I don't know if the difference is due to the OS or something else, but in both cases they fail trying to connect to a port on 127.0.0.1.

### Describe the behavior you expected

The Shiny app test controls and the app should load.

Note: this works on Desktop. It's only a Server issue.

**Comment by jmcphers** [comment]
What version of shinytest are you using? This looks like https://github.com/rstudio/rstudio/issues/4054, which was fixed in https://github.com/rstudio/shinytest/pull/231 on the Shinytest side.

**Comment by ronblum** [comment]
It looks like the behavior on Red Hat is the same, and the dev version of `shinytest` took care of that (so that's a duplicate). But it didn't fix it on the Ubuntu instance. Javier and I took a look, we debugged `sd_initialize` in `shinytest`, the error that triggered was `private$web$go(private$getShinyUrl())`.

Then we tried debugging and somehow using the public URL was fixing the problem, as in:

```
debug: private$web$go(private$getShinyUrl())
Browse[2]> rstudioapi::translateLocalUrl(private$getShinyUrl(), absolute = TRUE) [1] "http://MASKED_URL/"
Browse[2]> private$web$go("http://MASKED_URL/")
Browse[2]> private$web$go(private$getShinyUrl()) Error in curl::curl_fetch_memory(url, handle = handle) :    Failed to connect to 127.0.0.1 port 8966: Connection refused
```

It suddenly once or twice and then went back to failing. It might be a timing issue.

(Using screensharing, @javierluraschi wrote half of this, and I wrote the other.)

**Comment by jmcphers** [comment]
Interesting. There's nothing very distro-specific about this code, so probably just lucky timing. Maybe now the problem is that shinytest is attempting to connect to the port before Shiny is actually up and running? 

I can probably help debug tomorrow afternoon if it isn't clear, but I'd be very surprised if this turns out to be a bug on our end.

**Comment by ronblum** [comment]
Just a little more information: with the dev version of `shinytest`:

1) It works on SLES 12 SP3
2) On Ubuntu 16.04.2 with R 3.4.2, the window opens and immediate closes. In the console:

```
> shinytest::recordTest("~/testy")

Listening on http://127.0.0.1:6084
Warning: Error in eval: object 'ShinyDriver' not found
  61: eval
  60: eval
  59: match.arg
  48: app$getDebugLog
  47: <observer> [/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4/shinytest/recorder/app.R#399]
   4: shiny::runApp
   1: shinytest::recordTest
```

**Comment by jmcphers** [comment]
That console error is occurring entirely inside of shinytest, so I'd be very surprised if it was an RStudio issue. @ronblum Can you try running that R command in a terminal on the server?

**Comment by ronblum** [comment]
@jmcphers The problem occurs on Ubuntu in standalone R 3.4.4, so it's not RStudio specific. This isn't an issue with 3.6.0. Also, R was installed with the installer using `apt-get`, not built it from source, though it had failed in those builds, too.

It works on openSUSE 42.3 with R 3.5.3. I believe it failed on R 3.5.3 in an Ubuntu environment, though; I can retest, if necessary.

In any case, this isn't a problem with RStudio, per se.

(I'm sorry it took so long to rule out the variables and to confirm this)

**Comment by jmcphers** [comment]
Okay, closing since it's not an RStudio issue. Thanks for closing the loop!
