### ISSUE TITLE
Paste a file from Windows Explorer

### ISSUE THREAD

**Issue by dicorynia** [rstudio/rstudio#4572]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1327
    OS Version      : Win7 SP1 x64
    R Version       :  3.5.1

### Steps to reproduce the problem

1. In the Windows file manager, copy a file (focus a file icon, `ctrl + c`)
2. Paste in a string in the RStudio editor (`ctrl + v` or `Edit / paste` or `right click / paste`)
3. Nothing is pasted

### Describe the problem in detail

This is different than just pasting a filename (focus a file icon, `F2`, `ctrl + a`, then in RStudio `ctrl + v`), which works as expected.

### Describe the behavior you expected

In previous versions when pasting the file, the full path was pasted in the string (including a "file://" prefix). That was handy because the backslashes were replaced by slashes so the file path was both a valid string and a valid filename (minus the "file://" prefix).

We could `shift + right click` and `Copy as path` in the Windows Explorer, however the antislashes remain and must be edited to have a valid R string.

**Comment by kevinushey** [comment]
Worth noting that this works as expected on Ubuntu + macOS -- only Windows doesn't seem to work by default.

**Comment by jannikbuhr** [comment]
I can confirm this bug for Windows 10 (Version 10.0.17758 Build 17758)

**Comment by dschlaep** [comment]
I can confirm (or a similar version of) this bug for RStudio Desktop v1.2.1335 (Build 1351 (f1ac3452)) under macOS X10.13.6 and R v3.5.3:

* Similar to the behavior with `Terminal`, I was able to drag-and-drop a file from Finder into `""`-marks in the Console of previous versions of RStudio. This would generate a complete file path. This no longer works. No text appears; the new RStudio is silent.
* Also, I was able to drag-and-drop a file from Finder into a window of previous versions of RStudio and RStudio would open the file according to its file type, e.g., a `.R` script file would be opened inside RStudio. This no longer works; no file is opened; the new RStudio is silent.

If I copy a file in Finder and paste it into the console, then only the filename, but not the entire file path, is copied into the console of RStudio.

**Comment by chasemc** [comment]
Can confirm it also doesn't work for the following:
```
> Sys.info()
          sysname           release           version          nodename           machine 
        "Windows"          "10 x64"     "build 17763" "DESKTOP-5LBAL80"          "x86-64" 
```

```
Version 1.2.1335
© 2009-2019 RStudio, Inc.
Build 1379 (f1ac3452)
```

**Comment by leandromarino** [comment]
the same here.

https://github.com/rstudio/rstudio/issues/4572
```
     sysname        release        version       nodename        machine    
     "Windows"       "10 x64"  "build 17763"        "TRI14"       "x86-64"
```

Version 1.2.1335
© 2009-2019 RStudio, Inc.
Build 1379 (f1ac3452)

**Comment by DanOlner** [comment]
Same here still. This is a REALLY useful massively timesaving feature. Version 1.2.5001

**Comment by mirt001** [comment]
Still an issue in RStudio Version 1.2.5001 Build 1468 (7b3fe265, 2019-09-18)

```
"Windows" "10 x64" "build 17134"
```

**Comment by jmcphers** [comment]
This appears to be a bug in QtWebEngine. I have filed it there: 

https://bugreports.qt.io/browse/QTBUG-80573

**Comment by mirt001** [comment]
@jmcphers people at qt seem to think the issue is not there, since they closed the ticket you opened with the resolution "out of scope". Could you perhaps investigate a bit more, and if the issue will never be resolved in qt, maybe it can be implemented in RStudio independently.

**Comment by mirt001** [comment]
I also submitted the bug to Chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=1115505
I have a feeling that it is upstream for Chromium as well though. Possibly coming from all the way upstream.

**Comment by ronblum** [comment]
Thanks for the checking, @dicorynia! Just to confirm, was this the stable (Qt) version of RStudio Desktop or the experimental Electron version?

**Comment by dicorynia** [comment]
Both versions (*Desktop Electron Version* and *Desktop Version* on https://www.rstudio.com/products/rstudio/download/preview/)

**Comment by ronblum** [comment]
Darn, we were hoping that this would be resolved by Electron, but it possibly is still not working because of the Chromium issue, on which Electron depends.

@jonvanausdeln Could you try this and check whether or not you see the same behavior on Windows?

**Comment by jonvanausdeln** [comment]
I just tried 2022.11.0-82 on Win11, and I see the behavior in the original repro. Nothing is pasted.

**Comment by ronblum** [comment]
Thanks @jonvanausdeln for confirming!

**Comment by youngdjn** [comment]
I have the same problem with this setup:

```> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS
```

```
RStudio
2023.03.0 Build 386
© 2009-2023 Posit Software, PBC
"Cherry Blossom" Release (3c53477a, 2023-03-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
```

I saw this was also an issue in VS Code and was partially fixed: https://github.com/microsoft/vscode/issues/146770

**Comment by little-ear** [comment]
I have the same issue with 

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.0                         
year           2023                        
month          04                          
day            21                          
svn rev        84292                       
language       R                           
version.string R version 4.3.0 (2023-04-21)
nickname       Already Tomorrow 

RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

Very demanding work around: 
Copy path in nautilus (ctrl+c) - paste it in a text editor (e.g. gedit; ctrl+v) - recopy again (ctrl+a, ctrl+x) - copy to RStudio (copy+v)

**Comment by eauleaf** [comment]
Because I needed this functionality and didn't want to wait anymore, I implemented it in package `xlr`. It's key-chord: "ctrl + alt + shift +v", which calls the function `paste_from_xl()`.  `paste_from_xl()` recognizes when you have paths in your clipboard memory and pastes them formatted as a char vector in your RStudio editor. Testing whether it works on other machines would be helpful. See the documentation here: [xlr](https://eauleaf.github.io/xlr/articles/xlr.html)

**Comment by DamienFr** [comment]
This is still an issue ...

RStudio Version : 2023.09.1 Build 494
OS Version      : Linux Mint 21.2 Victoria"
R Version       :  3.5.1

**Comment by jonvanausdeln** [comment]
Verified on [2023.12.0-daily+302](https://dailies.rstudio.com/version/2023.12.0-daily+302)
Windows 11

Copy and Paste into R Console and a source file pastes the full path to the file with `\` converted to `/`.  Note that it does not prepend a `file://` as mentioned in the original repro case.

**Comment by DamienFr** [comment]
Many thanks jonvanausdeln, you're wonderful ! I'm truly grateful you implemented this. I use this feature a lot as it saves me time.

**Comment by DesiQuintans** [comment]
Any chance of an extension to this where copying *n* files pastes their paths on *n* new lines? Would pair nicely with multiple cursors.

**Comment by kevinushey** [comment]
@DesiQuintans can you please file a separate issue to track that?

**Comment by DamienFr** [comment]
This issue seems to have came back

(ctrl + c on a file in the file browser, then ctrl + v in rtudio rscript, and nothing gets pasted). Am i alone having this behavior ?

RStudio Version : 2026.08.1 Build 195

**Comment by dicorynia** [comment]
I'm still on 2026.06.0 build 242 (windows) and it works. So maybe a recent regression.

**Comment by jonvanausdeln** [comment]
> This issue seems to have came back
> 
> (ctrl + c on a file in the file browser, then ctrl + v in rtudio rscript, and nothing gets pasted). Am i alone having this behavior ?
> 
> RStudio Version : 2026.08.1 Build 195

@DamienFr , since this issue was closed out would you mind opening a new issue with what you are experiencing?

**Comment by kevinushey** [comment]
We can re-open and re-investigate in this issue -- thanks for reporting.

**Comment by kevinushey** [comment]
@DamienFr: can you please confirm your operating system / other system information?

**Comment by DamienFr** [comment]
Hi,

First, Thank you to all, you contributors of RStudio, for your work.
Then, should i open a new issue or not ?

R version 4.6.1 (2026-06-24)
RStudio Version : 2026.08.1 Build 195
Kernel: 7.0.0-28-generic
Linux Mint 22.3

**Comment by kevinushey** [comment]
@DamienFr no need to open a new issue -- we'll keep tracking it here.

I tried to reproduce this with RStudio 2026.08.1 on Ubuntu 24.04, which Mint 22.3 is based on. I put a file on the clipboard the same way Nemo does, and pasting into both the Console and an R script inserted the quoted file path as expected, on both X11 and Wayland. So there's probably something about your setup that we're missing. Could you help us narrow it down?

1. Are you running an X11 or Wayland session? (`echo $XDG_SESSION_TYPE`)
2. Which file manager are you copying from (Nemo?), and are you running a clipboard manager (e.g. a Cinnamon clipboard applet, CopyQ, Diodon, GPaste)?
3. After copying the file, what does `xclip -selection clipboard -o -t TARGETS` print? (`sudo apt install xclip` if needed; on Wayland, use `wl-paste --list-types` instead.)
4. Does pasting into the Console work? What about a plain text file (File > New File > Text File)?
5. Do you know the last RStudio version where this worked for you, and did anything else change around then (e.g. upgrading to Mint 22.3)?

If you're comfortable with it, this would also show exactly what RStudio receives. Open Help > Diagnostics > Toggle Developer Tools, go to the Console tab, and paste in the snippet below (Chrome may ask you to type `allow pasting` first):

```js
document.addEventListener("paste", function(e) {
  var cd = e.clipboardData, files = [];
  for (var i = 0; i < cd.files.length; i++)
    files.push(cd.files[i].name + " -> " + JSON.stringify(window.desktop.getPathForFile(cd.files[i])));
  console.log("paste types:", JSON.stringify(Array.from(cd.types)), "files:", JSON.stringify(files));
}, true);
```

Then copy a file in the file manager, paste it into an R script, and share the line that gets logged, plus any errors shown in red.

**Comment by dicorynia** [comment]
FWIW, it also works fine for me on Linux Mint 22.3 kernel 7.0.0-31-generic - Cinnamon  6.6.9 64-bit on X11
From Nemo
To RStudio 2026.06.0

**Comment by DamienFr** [comment]
Woups, so indeed the problem is on my side. I didn't expect that ... 

1. x11
2. `xdg-mime query default inode/directory`
nemo.desktop
`ps aux | grep -iE "clipit|copyq|diodon|gpaste|clipman|parcellite"`
user      9191  0.0  0.0  11864  2512 pts/4    S+   09:29   0:00 grep --color=auto -iE clipit|copyq|diodon|gpaste|clipman|parcellite
3. `xclip -selection clipboard -o -t TARGETS`
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
x-special/gnome-copied-files
text/uri-list
application/vnd.portal.filetransfer
application/vnd.portal.files
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
text/plain

>Does pasting into the Console work?
If i copy a file and i ctrl+v into the console, nothing happens, but if i ctrl+c text from a text file i can ctrl+v into the console

>What about a plain text file (File > New File > Text File)?
Same behavior

>Do you know the last RStudio version where this worked for you, and did anything else change around then (e.g. upgrading to Mint 22.3)?
This is the weird part, i have not changed neither R, Rstudio or Mint recently.
I did however install numerous packages i would not be able to list.

Thank you,

**Comment by kevinushey** [comment]
@DamienFr thanks, that's helpful. Everything you posted looks normal: an X11 session, no clipboard manager, and the clipboard targets Nemo advertises (`text/uri-list`, `x-special/gnome-copied-files`, etc.) are exactly what a working setup shows too. So Nemo is putting the file on the clipboard correctly, and the paste is getting lost somewhere between the clipboard and the editor. Since it fails the same way in the Console, an R script, and a plain text file, it isn't specific to R code handling.

Two more things would pin it down:

1. The DevTools snippet from my earlier comment. That's the one measurement that shows what RStudio actually receives. Open Help > Diagnostics > Toggle Developer Tools, switch to the Console tab, paste the snippet below (type `allow pasting` first if Chrome asks), then copy a file in Nemo and paste it into an R script. Please share the `paste types:` line that gets logged, and any errors shown in red.

   ```js
   document.addEventListener("paste", function(e) {
     var cd = e.clipboardData, files = [];
     for (var i = 0; i < cd.files.length; i++)
       files.push(cd.files[i].name + " -> " + JSON.stringify(window.desktop.getPathForFile(cd.files[i])));
     console.log("paste types:", JSON.stringify(Array.from(cd.types)), "files:", JSON.stringify(files));
   }, true);
   ```

2. The actual contents of the copied-file entries, right after copying a file in Nemo:

   ```sh
   xclip -selection clipboard -o -t text/uri-list
   xclip -selection clipboard -o -t x-special/gnome-copied-files
   ```

   In particular: where does the file you're copying live? If it's on a network share, a mounted drive, or anything that shows up under `/run/user/<uid>/gvfs/`, the URI won't be a plain `file:///...` URI, and Chromium (which RStudio Desktop is built on) silently drops those. If that's the case, could you check whether copying a file from your home directory pastes correctly?

**Comment by DamienFr** [comment]
0. i opened the dev console, as a header it shows `rstudio-0.js:25631 Failed load Ace snippets for mode 'text'`
Perhaps the bug is linked to this ?

1. i get : 
`paste types: ["text/uri-list"] files: []`

2. `xclip -selection clipboard -o -t text/uri-list`
i get `file:///home/user/Downloads/file.ab1`

`xclip -selection clipboard -o -t x-special/gnome-copied-files`

i get : 
`copy
file:///home/user/Downloads/file.ab1`
