### ISSUE TITLE
Mouse-over column index in Data Viewer

### ISSUE THREAD

**Issue by kixt** [rstudio/rstudio#4611]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS 10.14.4
    R Version       : 3.5.3

### Steps to reproduce the problem

```{r}
View(plyr::ozone)
```

In Data Viewer, go to 
```{r}
Cols: << < 51-100 > >>
```

### Describe the problem in detail

In the Data Viewer the numeric column index is available when moving the cursor over the column name. For columns 1 to 50 this is the correct index. For higher ranges of columns, the index is off by $50 \cdot \frac{range_start - 1}{50}$.

### Describe the behavior you expected

The correct column number in the mouse-over.

**Comment by dracodoc** [comment]
Same on me, windows 7, R 3.6.1, RStudio 1.2.1335.

**Comment by Famondir** [comment]
Have same problem. Imported a dataset via read_sav (via haven lib) with more than 500 columns. Buth the index doesn't seem to be off by 50 in any case. Its off by two times the minimal viewed row number. So by 50 for column 50-99 (which are viewed as 101-150) by 100 for column 100-149 (which are viewed as 201-250) ... till 1672-1721 (which are viewed as 3342-3392).

Windows 10, x64 R 3.6.1, 1.2.5033

**Comment by adamconroy** [comment]
@Famondir are you able to test this on the latest daily? This bug appears to be a dupe of #5484 which was fixed recently.

**Comment by Famondir** [comment]
Just tested it again. Now with an empty dataframe (test <- data.frame(matrix(ncol = 120, nrow = 3)) ) and the bug is still there.

Sincerely Simon

**Comment by adamconroy** [comment]
Hi @Famondir can you give a little more detail about your bug (RStudio version, maybe a screenshot of it)? I can't replicate it on the latest daily using your dataframe. 
![QinthC2](https://user-images.githubusercontent.com/136863/74048264-e7742e00-499f-11ea-9d5d-05be2815e546.png)

**Comment by Famondir** [comment]
As stated above: Windows 10, x64 R 3.6.1, 1.2.5033

Have the same bug at two independent computers.

![Screenshot (6)](https://user-images.githubusercontent.com/43599267/74321268-465feb80-4d82-11ea-8382-e99b950c6ad2.png)

**Comment by kjalcock** [comment]
I am getting this problem today.
R version 3.6.2 
RStudio Version 1.2.1335
Windows 10, X64

**Comment by adamconroy** [comment]
Hi @Famondir and @kjalcock this is fixed as of version 1.3.822-1

This issue is a dupe of #5484 so it caused me to miss circling back here.

You will need to update to a daily or wait for the full 1.3 release to see this fix in the app, thank you for your patience.
https://dailies.rstudio.com/

**Comment by kjalcock** [comment]
Thanks, none of the daily builds are downloadable for me so I guess I'm waiting for 1.3.

**Comment by adamconroy** [comment]
Interesting, which version do you need @kjalcock ? I can look into it.

**Comment by adamconroy** [comment]
Interesting, which version do you need @kjalcock ? I can look into it.

**Comment by kjalcock** [comment]
Anything that will work with this issue - all of the downloads seem to fail.

**Comment by kjalcock** [comment]
I also checked the "preview" page https://rstudio.com/products/rstudio/download/preview/
This is ALSO coming up with "download - failed".

**Comment by adamconroy** [comment]
@kjalcock I think there is something wrong with your internet/browser settings. I just clicked the download link and was able to download them. I tried both windows x64 and linux. Please try a different browser/internet connection/computer if possible. This link worked for me on 2 different computers: https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.3.929.exe

**Comment by CJelleyman** [comment]
@adamconroy I had the same issue. I updated R to V 3.6.3 (Holding the Windsock) and R studio to V1.2.5003 available on the [R Studio](https://rstudio.com/products/rstudio/download/#download) site, and it persisted. Issue was only fixed when I followed your link above to DL V1.3.029.

**Comment by kjalcock** [comment]
I have also managed to download from your link but not (several times) from the R Studio link.

**Comment by adamconroy** [comment]
@CJelleyman please download a 1.3 daily as mentioned in the comments for a fix.

**Comment by adamconroy** [comment]
@CJelleyman correct, the fix is not in a 1.2 download.

**Comment by vanagpau** [comment]
I have the same problem - the hover over is giving for example "column 526" when my data frame only has 312 columns.
![Picture1](https://user-images.githubusercontent.com/58073695/83852827-49556200-a70c-11ea-932b-14653deadff5.png)

**Comment by adamconroy** [comment]
@vanagpau which version of RStudio are you on? You will need to upgrade to v1.3 for the fix.
