### ISSUE TITLE
At startup: "there is no package called Rcpp"

### ISSUE THREAD

**Issue by jimhester** [rstudio/rstudio#4873]
### System details

    RStudio Edition : Any
    RStudio Version :  Any
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem

`remove.packages("Rcpp")` then open a RStudio project with a package that uses Rcpp. One other easy way to reproduce this is to use rstudio.cloud and create a new project from git, with a package that uses Rcpp, e.g. https://github.com/r-lib/vroom. You should get repeated cases of the following until you install Rcpp.

```
Error in (function (package = NULL, lib.loc = NULL, quiet = FALSE, verbose = getOption("verbose"))  : 
  there is no package called ‘Rcpp’
```

### Describe the problem in detail

This seems to be a similar issue to https://github.com/rstudio/rstudio/issues/4092. The ideal fix for both issues would be a prompt asking if you would like to install the missing package. But at least silencing the errors would be a good stop-gap.

**Comment by kevinushey** [comment]
I even see a crash with `dplyr`:

![Screen Shot 2019-05-30 at 4 20 26 PM](https://user-images.githubusercontent.com/1976582/58671294-f83fb080-82f6-11e9-8768-f3930ebcba07.png)

**Comment by kevinushey** [comment]
I believe this should be fixed via https://github.com/rstudio/rstudio/pull/4875.

**Comment by rich-rstudio** [comment]
@kevinushey im still seeing this issue on version 1.3.706 (MacOS desktop)

**Comment by rich-rstudio** [comment]
@kevinushey im seeing this error in the console now (MacOS Version 1.3.885)
<img width="542" alt="Screen Shot 2020-03-04 at 10 30 06 AM" src="https://user-images.githubusercontent.com/43964690/75900847-2c567d80-5e03-11ea-97ab-7a205256a4dd.png">

**Comment by kevinushey** [comment]
The error is okay -- as long as the IDE is not crashing.

**Comment by rich-rstudio** [comment]
@kevinushey sounds good, thanks!
