### ISSUE TITLE
Escape key restarts Rstudio Server

### ISSUE THREAD

**Issue by raubreywhite** [rstudio/rstudio#5108]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335
    OS Version      : Rocker (Debian inside of Docker container)
    R Version       : 3.6.1

### Steps to reproduce the problem

https://github.com/rocker-org/rocker/issues/316#issuecomment-511802074

I am using a Rocker image (i.e. RStudio Server inside a docker container)

I enter this in the terminal (i.e. starting up RStudio Server):

```
docker run --rm -p 8789:8787 -e PASSWORD=rstudio1 rocker/rstudio
```

I then type `docker ps` to get the name of my container (blissful_benz). I then enter the container as a root user:

```
docker exec -it blissful_benz bash
```

And I install the linux package `tk`

```
root@5caea91f596a:/# apt-get update && apt-get install -y tk
```

I then go to RStudio Server and install `sm`:

```
install.packages("sm")
```

And get the following output:

```
> install.packages("sm")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2019-07-15/src/contrib/sm_2.2-5.6.tar.gz'
Content type 'application/octet-stream' length 256355 bytes (250 KB)
==================================================
downloaded 250 KB

* installing *source* package ‘sm’ ...
** package ‘sm’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fgamma.c -o fgamma.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gfortran  -fpic  -g -O2  -c  variogram.f90 -o variogram.o
gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o sm.so fgamma.o init.o variogram.o -lgfortran -lm -lquadmath -L/usr/local/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-sm/00new/sm/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning in fun(libname, pkgname) : couldn't connect to display ":0"
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning in fun(libname, pkgname) : couldn't connect to display ":0"
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Warning in fun(libname, pkgname) : couldn't connect to display ":0"
** testing if installed package keeps a record of temporary installation path
* DONE (sm)

The downloaded source packages are in
	‘/tmp/Rtmpclxt09/downloaded_packages’
```

HOWEVER, here is the interesting thing:

```

> library(sm) 
Package 'sm', version 2.2-5.6: type help(sm) for summary information 
Warning message: In fun(libname, pkgname) : couldn't connect to display ":0"

```

If I now press the "escape" key on my keyboard after loading 'sm', RStudio Server restarts!

So if I do `library(sm) [enter] [escape]` then my RStudio Server will restart.

If I do `library(stats) [enter] [escape]` then my RStudio Server will NOT restart.

Any ideas?? It makes it very difficult to write any code when I am afraid to use the escape key!

### Describe the problem in detail

When using RStudio Server on a headless linux machine, after running `library(sm)` using the "escape" key will make RStudio Server restart.

### Describe the behavior you expected

Escape key should never make RStudio Server restart.

**Comment by kevinushey** [comment]
This can be reproduced much more simply:

```
library(tcltk)
# press escape
```

I can reproduce with RStudio Desktop on macOS.

---

Here's the call stack when `Rf_onintr()` is called in RStudio:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
  * frame #0: 0x000000010d0ec1d4 libR.dylib`Rf_onintr at errors.c:177:18 [opt]
    frame #1: 0x000000010d233ee5 libR.dylib`R_checkActivityEx(usec=0, ignore_stdin=1, intr=0x0000000000000000) at sys-std.c:342:7 [opt]
    frame #2: 0x0000000111d70330 tcltk.so`RTcl_checkProc + 16
    frame #3: 0x0000000115fae7d6 libtcl8.6.dylib`Tcl_DoOneEvent + 317
    frame #4: 0x0000000111d706ba tcltk.so`TclSpinLoop + 26
    frame #5: 0x000000010d0aef1c libR.dylib`R_ToplevelExec(fun=(tcltk.so`TclSpinLoop), data=0x0000000000000000) at context.c:757:2 [opt]
    frame #6: 0x0000000111d70687 tcltk.so`TclHandler + 55
    frame #7: 0x000000010d2373f7 libR.dylib`R_ProcessEvents at sys-unix.c:880:5 [opt]
    frame #8: 0x000000010d0ec1ad libR.dylib`R_CheckUserInterrupt at errors.c:131:5 [opt]
    frame #9: 0x000000010cd4ce95 rsession`rstudio::r::session::RReadConsole(pmt=<unavailable>, buf=<unavailable>, buflen=<unavailable>, hist=1) at RStdCallbacks.cpp:381:7 [opt]
    frame #10: 0x000000010d143e36 libR.dylib`Rf_ReplIteration(rho=0x00007ff4af044390, savestack=0, browselevel=0, state=0x00007ffee3703f30) at main.c:208:10 [opt]
    frame #11: 0x000000010d14561f libR.dylib`run_Rmainloop [inlined] R_ReplConsole(rho=<unavailable>, savestack=0, browselevel=0) at main.c:310:11 [opt]
    frame #12: 0x000000010d1455b6 libR.dylib`run_Rmainloop at main.c:1086 [opt]
    frame #13: 0x000000010cd6f320 rsession`rstudio::r::session::runEmbeddedR((null)=<unavailable>, (null)=<unavailable>, quiet=false, loadInitFile=true, defaultSaveAction=SA_NOSAVE, callbacks=0x00007ffee3705210, pInternal=0x000000010cfd9d18) at REmbeddedPosix.cpp:152:4 [opt]
    frame #14: 0x000000010cd4a3a4 rsession`rstudio::r::session::run(options=0x00007ffee3705530, callbacks=<unavailable>) at RSession.cpp:370:4 [opt]
    frame #15: 0x000000010c623860 rsession`main(argc=<unavailable>, argv=<unavailable>) at SessionMain.cpp:2036:15 [opt]
    frame #16: 0x00007fff6114a3d5 libdyld.dylib`start + 1
    frame #17: 0x00007fff6114a3d5 libdyld.dylib`start + 1
```

This reminds me of an old Windows issue where the process would crash if the first thing you did in the session was press Escape...

**Comment by henri9813** [comment]
Hello, 

Somebody have a workaround for this issue? 

Best regard

**Comment by kevinushey** [comment]
The issue should already be fixed in the latest version of RStudio.

**Comment by lausanne22** [comment]
Hey, I am still not managing to download 'vioplot' due to this issue... 
is it supposed to be fixed ? 
if so - what can I do ?
