### ISSUE TITLE
Rstudio hangs when debugging code or calling "stop", rsession at 100% CPU

### ISSUE THREAD

**Issue by slhck** [rstudio/rstudio#5158]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1564
    OS Version      : macOS 10.14
    R Version       : 3.6.1 (Homebrew)

### Steps to reproduce the problem

I am loading a few large data files and running some computations on them. I would like to debug one of the computation steps, so I naively set a `stop("foo")` within the function that is called.

### Describe the problem in detail

Once the `stop` point is hit, I see in the console:

```
Error in (function (.df, .kpi_col, .user_segments, .lower_is_better = TRUE,  : 
    foo
```

And the R session is still doing… something. I see the 🛑button, which indicates that something is computing, I see the CPU for `rsession` at 100%, and I can't terminate or restart R from Rstudio.

Hitting _Session » Interrupt R_ or _Session » Terminate R…_ is doing nothing. Hitting _Session » Restart R_ is showing the *Restarting R…* info window, but it's not actually restarting R. I've waited for minutes, and nothing is happening.

So somehow it seems like Rstudio has lost the connection with the R session. The worst part is when the UI is unresponsive; I cannot save changes to the file I have open, and the only thing that works is completely killing Rstudio.

The same happens when I set a breakpoint at the same location. I see the "Browse" message in the console, but the debug buttons never appear, and the code editor never switches to the debug view (the one where the affected code is highlighted). The CPU goes to 100%, nothing happens for minutes.

sessionInfo():

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.6_1/lib/libopenblasp-r0.3.6.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] nortest_1.0-4      optparse_1.6.2     tidylog_0.1.0     
 [4] digest_0.6.19      modelr_0.1.4       broom_0.5.2       
 [7] ggrepel_0.8.1      geosphere_1.5-7    ggmap_3.0.0       
[10] ggforce_0.2.2      snakecase_0.10.0   jsonlite_1.6      
[13] yaml_2.2.0         openssl_1.3        psych_1.8.12      
[16] stringi_1.4.3      magrittr_1.5       lubridate_1.7.4   
[19] forcats_0.4.0      stringr_1.4.0      dplyr_0.8.1       
[22] purrr_0.3.2        readr_1.3.1        tidyr_0.8.3       
[25] tibble_2.1.1       tidyverse_1.2.1    Hmisc_4.2-0       
[28] ggplot2_3.1.1      Formula_1.2-3      survival_2.44-1.1 
[31] lattice_0.20-38    matrixStats_0.54.0 conflicted_1.0.3  
[34] packrat_0.5.0-5   

loaded via a namespace (and not attached):
 [1] nlme_3.1-140        bitops_1.0-6        RColorBrewer_1.1-2 
 [4] httr_1.4.0          tools_3.6.1         backports_1.1.4    
 [7] R6_2.4.0            rpart_4.1-15        lazyeval_0.2.2     
[10] colorspace_1.4-1    nnet_7.3-12         withr_2.1.2        
[13] sp_1.3-1            tidyselect_0.2.5    gridExtra_2.3      
[16] mnormt_1.5-5        compiler_3.6.1      cli_1.1.0          
[19] rvest_0.3.4         htmlTable_1.13.1    xml2_1.2.0         
[22] scales_1.0.0        checkmate_1.9.3     askpass_1.1        
[25] foreign_0.8-71      base64enc_0.1-3     jpeg_0.1-8         
[28] pkgconfig_2.0.2     htmltools_0.3.6     highr_0.8          
[31] htmlwidgets_1.3     rlang_0.3.4         readxl_1.3.1       
[34] rstudioapi_0.10     farver_1.1.0        generics_0.0.2     
[37] acepack_1.4.1       Matrix_1.2-17       Rcpp_1.0.1         
[40] munsell_0.5.0       MASS_7.3-51.4       plyr_1.8.4         
[43] grid_3.6.1          crayon_1.3.4        semver_0.2.0       
[46] haven_2.1.0         splines_3.6.1       hms_0.4.2          
[49] knitr_1.23          pillar_1.4.0        rjson_0.2.20       
[52] glue_1.3.1          latticeExtra_0.6-28 data.table_1.12.2  
[55] png_0.1-7           tweenr_1.0.1        RgoogleMaps_1.4.3  
[58] cellranger_1.1.0    gtable_0.3.0        getopt_1.20.3      
[61] polyclip_1.10-0     assertthat_0.2.1    xfun_0.7           
[64] memoise_1.1.0       cluster_2.1.0  
```

<details>
<summary>Diagnostics report</summary>
<pre>
<code>
[1] "1.2.1564"

$R
[1] "/usr/local/bin/R"

$pdflatex
[1] "/Library/TeX/texbin/pdflatex"

$bibtex
[1] "/Library/TeX/texbin/bibtex"

$gcc
[1] "/usr/bin/gcc"

$git
[1] "/usr/local/bin/git"

$svn
[1] "/usr/local/bin/svn"

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.6_1/lib/libopenblasp-r0.3.6.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1   

SysInfo:
                                                                                           sysname 
                                                                                          "Darwin" 
                                                                                           release 
                                                                                          "18.6.0" 
                                                                                           version 
"Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64" 
                                                                                          nodename 
                                                                         "vpn242.rz.tu-ilmenau.de" 
                                                                                           machine 
                                                                                          "x86_64" 
                                                                                             login 
                                                                                          "werner" 
                                                                                              user 
                                                                                          "werner" 
                                                                                    effective_user 
                                                                                          "werner" 

R Version:
               _                           
platform       x86_64-apple-darwin18.6.0   
arch           x86_64                      
os             darwin18.6.0                
system         x86_64, darwin18.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes          
$`_`
[1] "/Applications/RStudio.app/Contents/MacOS/RStudio"

$`__CF_USER_TEXT_ENCODING`
[1] "0x1F5:0x0:0x0"

$Apple_PubSub_Socket_Render
[1] "/private/tmp/com.apple.launchd.e0zTEkkS4U/Render"

$AUTOJUMP_ERROR_PATH
[1] "/Users/werner/Library/autojump/errors.log"

$AUTOJUMP_SOURCED
[1] "1"

$CLICOLOR
[1] "1"

$CLICOLOR_FORCE
[1] "1"

$COLORFGBG
[1] "15;0"

$COLORTERM
[1] "yes"

$DYLD_FALLBACK_LIBRARY_PATH
[1] "/usr/local/Cellar/r/3.6.1/lib/R/lib:/Users/werner/lib:/usr/local/lib:/usr/lib:::/lib"

$EDITOR
[1] "vim"

$GIT_ASKPASS
[1] "rpostback-askpass"

$HISTFILE
[1] "/Users/werner/.zshhistory"

$HISTSIZE
[1] "50000"

$HOME
[1] "/Users/werner"

$ITERM_PROFILE
[1] "Default"

$ITERM_SESSION_ID
[1] "w0t4p0:AB48A083-6B57-4BE6-8D90-08B7092FF15E"

$LANG
[1] "en_US.UTF-8"

$LC_ALL
[1] "en_US.UTF-8"

$LC_CTYPE
[1] "en_US.UTF-8"

$LESS
[1] "-R"

$LN_S
[1] "ln -s"

$LOGNAME
[1] "werner"

$LS_COLORS
[1] "no=00:fi=00:di=00;36:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.bz2=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.sit=01;31:*.hqx=01;31:*.jpg=01;35:*.png=01;35:*.gif=01;35:*.bmp=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mpg=01;35:*.avi=01;35:*.mov=01;35:*.app=01;33:*.c=00;33:*.php=00;33:*.pl=00;33:*.cgi=00;33:"

$LSCOLORS
[1] "gxfxbEaEBxxEhEhBaDaCaD"

$MAKE
[1] "make"

$NVM_CD_FLAGS
[1] "-q"

$NVM_DIR
[1] "/usr/local/opt/nvm"

$NVM_RC_VERSION
[1] ""

$OLDPWD
[1] "/Users/werner/Documents/Projects/"

$PAGER
[1] "less"

$PATH
[1] "/Library/TeX/texbin:/Users/werner/.rbenv/shims:/Users/werner/.rbenv/bin:/Users/werner/.rbenv/plugins/ruby-build/bin:/Users/werner/bin:/usr/local/bin:/usr/local/sbin:/usr/texbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/opt/fzf/bin:/Users/werner/bin"

$PWD
[1] "/Users/werner"

$R_BROWSER
[1] "/usr/bin/open"

$R_BZIPCMD
[1] "/usr/bin/bzip2"

$R_DOC_DIR
[1] "/usr/local/Cellar/r/3.6.1/lib/R/doc"

$R_GZIPCMD
[1] "/usr/bin/gzip"

$R_HOME
[1] "/usr/local/Cellar/r/3.6.1/lib/R"

$R_INCLUDE_DIR
[1] "/usr/local/Cellar/r/3.6.1/lib/R/include"

$R_LIBS_SITE
[1] ""

$R_LIBS_USER
[1] "~/Library/R/3.6/library"

$R_PAPERSIZE
[1] "a4"

$R_PDFVIEWER
[1] "/usr/bin/open"

$R_PLATFORM
[1] "x86_64-apple-darwin18.6.0"

$R_PRINTCMD
[1] "lpr"

$R_RD4PDF
[1] "times,inconsolata,hyper"

$R_SESSION_TMPDIR
[1] "/var/folders/xr/f7sr_4_x33q4d51k3bh995080000gn/T//RtmpZ3jxXU"

$R_SHARE_DIR
[1] "/usr/local/Cellar/r/3.6.1/lib/R/share"

$R_STRIP_SHARED_LIB
[1] "strip -x"

$R_STRIP_STATIC_LIB
[1] "strip -S"

$R_SYSTEM_ABI
[1] "osx,gcc,gxx,gfortran,gfortran"

$R_TEXI2DVICMD
[1] "/usr/bin/texi2dvi"

$R_UNZIPCMD
[1] "/usr/bin/unzip"

$R_ZIPCMD
[1] "/usr/bin/zip"

$RBENV_SHELL
[1] "zsh"

$RMARKDOWN_MATHJAX_PATH
[1] "/Applications/RStudio.app/Contents/Resources/resources/mathjax-26"

$RS_PPM_FD_READ
[1] "5"

$RS_PPM_FD_WRITE
[1] "13"

$RS_RPOSTBACK_PATH
[1] "/Applications/RStudio.app/Contents/MacOS/rpostback"

$RS_SHARED_SECRET
[1] "14587779232007237709823564440"

$RSTUDIO
[1] "1"

$RSTUDIO_CONSOLE_COLOR
[1] "256"

$RSTUDIO_CONSOLE_WIDTH
[1] "80"

$RSTUDIO_PANDOC
[1] "/Applications/RStudio.app/Contents/MacOS/pandoc"

$RSTUDIO_SESSION_PORT
[1] "36806"

$RSTUDIO_USER_IDENTITY
[1] "werner"

$RSTUDIO_WINUTILS
[1] "bin/winutils"

$SAVEHIST
[1] "10000"

$SED
[1] "/usr/bin/sed"

$SHELL
[1] "/bin/zsh"

$SHLVL
[1] "1"

$SPACESHIP_ROOT
[1] "/Users/werner/.oh-my-zsh/custom/themes/spaceship-prompt"

$SPACESHIP_VERSION
[1] "3.11.0"

$SSH_ASKPASS
[1] "rpostback-askpass"

$SSH_AUTH_SOCK
[1] "/private/tmp/com.apple.launchd.T8xYgl4tjA/Listeners"

$TAR
[1] "/usr/bin/tar"

$TERM
[1] "xterm-256color"

$TERM_PROGRAM
[1] "iTerm.app"

$TERM_PROGRAM_VERSION
[1] "3.2.9"

$TERM_SESSION_ID
[1] "w0t4p0:AB48A083-6B57-4BE6-8D90-08B7092FF15E"

$TMPDIR
[1] "/var/folders/xr/f7sr_4_x33q4d51k3bh995080000gn/T/"

$USER
[1] "werner"

$VIRTUAL_ENV_DISABLE_PROMPT
[1] "true"

$XPC_FLAGS
[1] "0x0"

$XPC_SERVICE_NAME
[1] "0"

 [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"    
 [4] "package:graphics"  "package:grDevices" "package:utils"    
 [7] "package:datasets"  "package:methods"   "Autoloads"        
[10] "package:base"     
Log file: rdesktop.log
--------------------------------------------------

24 Jul 2019 07:33:07 [rdesktop] ERROR Main window closed unexpectedly; LOGGED FROM: auto rstudio::desktop::MainWindow::closeEvent(QCloseEvent *)::(anonymous class)::operator()(QVariant) const /Users/vagrant/workspace/IDE/macos-v1.2/src/cpp/desktop/DesktopMainWindow.cpp:281

Log file: rsession-werner.log
--------------------------------------------------

15 Jul 2019 12:28:21 [rsession-werner] WARNING Process supervisor did not terminate within 1 second; LOGGED FROM: void (anonymous namespace)::rCleanup(bool) /Users/vagrant/workspace/IDE/macos-v1.2/src/cpp/session/SessionMain.cpp:1193
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 69, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 70, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 71, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 85, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 89, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 90, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 91, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
15 Jul 2019 14:24:42 [rsession-werner] CLIENT EXCEPTION (rsession-werner): Row index: 92, Row size: 3;|||rstudio-0.js#-1::new njd|||com/google/gwt/user/cellview/client/AbstractHasData.java#1022::checkRowBounds|||com/google/gwt/user/cellview/client/AbstractCellTable.java#2283::getSubRowElement|||com/google/gwt/user/cellview/client/AbstractCellTable.java#1195::getRowElement|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::lambda$0|||org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java#155::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#236::apply|||com/google/gwt/core/client/impl/Impl.java#275::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36
</code>
</pre>
</details>

**Comment by ronblum** [comment]
@slhck Thank you for raising the issue! Could you provide an example of code that we could use to try to reproduce the issue?

**Comment by slhck** [comment]
I wish I could, but it's proprietary code, and I can't share the data or the functions. I'll have to check if I can generate some fake data that and function calls, but that's going to be complicated.

Is there nothing that I could do with, e.g., sampling the process, which could show you where exactly the whole process “hangs”?

**Comment by slhck** [comment]
Here is some code that reproduces the issue:

```r
library(tidyverse)

foo <- function(.df) {
  print(nrow(.df))
}

args = list(
  .df = do.call(data.frame, replicate(60000, rep(FALSE, 10000), simplify=FALSE))
)

exec(foo, !!!args)
```

The created data frame is somewhat large (~ 2 GB). But the whole program exits in finite time. When I set a breakpoint in `print(nrow(.df))`, I see in the console:

```
Browse[1]> 
```

The CPU spikes at 100%, and I never get to actually debug the call. I can wait for minutes, but it won't show the debug tools or allow me to do anything. All I can do is force-quit RStudio.

When instead of `exec(foo, !!!args)`, I call `foo(args$.df)`, I can debug just fine; the debug tools appear within seconds.

So the issue seems to be related to `exec`.

**Comment by slhck** [comment]
Further debugging shows that replacing `exec(foo, !!!args)` with `do.call(foo, args)` also causes the same problem, so it's not `rlang::exec` at fault, but the base function.

**Comment by Patrick330** [comment]
I am also having this issue, in both R 3.5.1 and R 4.0.1, but only in Rstudio (1.3.1056, server and desktop(linux)). The example below crashes in Rstudio but not in base R run at the terminal. 

```
options(deparse.max.lines = 2)

library(data.table)
this_big_dataset <- fread(file.path('data', 'some_150mb_file.csv'))

some_function <- function(big_dataset) {
  browser()
  print(summary(big_dataset))
}

do.call('some_function', list(this_big_dataset))
```

It doesn't matter what file you use - any dataset of sufficiently large size will cause the crash. In this case my data is about 150mb, 

In Rstudio the console enters browser mode but is unresponsive. The R session hangs. In contrast, in base R run at the terminal the console enters browser mode as expected.

It seems very likely that Rstudio is attempting the deparse the call in order to produce the traceback window, but it is not responding to `options(deparse.max.lines)` as expected. This results in a call that includes the entire dataset, causing the R session to hang. The likely fix is to correct the traceback call to limit lines to only those necessary for the traceback window.

See related discussion here for additional context related to the implementation of `options(traceback.max.lines)` for R v4.0: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17580

If I were guessing, I would look on line 73 of *src/cpp/session/modules/SessionErrors.R* where the call stack is deparsed. I am not familiar with the Rstudio code, but if this function does not use options set by the user, then deparse may be returning a very long string. Otherwise, the issue may be occuring elsewhere in Rstudio's processing of the call stack when entering browser mode.

**Comment by Patrick330** [comment]
Here's a more complete reprex:

```
options(deparse.max.lines = 2)
#options(traceback.max.lines = 2)


this_little_dataset <- data.frame(list( col1 = 'some',
                                        col2 = 'body',
                                        col3 = 'once',
                                        col4 = 'told',
                                        col5 = 'me',
                                        col6 = 'the',
                                        col7 = 'world',
                                        col8 = 'was',
                                        col9 = 'gonna',
                                        col10 = 'roll',
                                        col11 = 'me'))
this_big_dataset <- this_little_dataset[rep(1, times=2500000),]

some_function <- function(big_dataset) {
  browser()
  print(summary(big_dataset))
}

do.call('some_function', list(this_big_dataset))
```

**Comment by kevinushey** [comment]
Thanks @Patrick330: you are indeed correct that the issue here is in deparse.

```
> summaryRprof("~/scratch/rstudio.Rprof")
$by.self
                        self.time self.pct total.time total.pct
"deparse"                   50.96    92.39      50.96     92.39
"make.unique"                1.94     3.52       1.94      3.52
"[.data.frame"               1.20     2.18       3.18      5.77
"structure"                  1.02     1.85       1.02      1.85
"[["                         0.02     0.04       0.02      0.04
"anyDuplicated.default"      0.02     0.04       0.02      0.04

$by.total
                        total.time total.pct self.time self.pct
"<Anonymous>"                51.98     94.23      0.00     0.00
"deparse"                    50.96     92.39     50.96    92.39
"browser"                    50.96     92.39      0.00     0.00
"do.call"                    50.96     92.39      0.00     0.00
"paste"                      50.96     92.39      0.00     0.00
"some_function"              50.96     92.39      0.00     0.00
"[.data.frame"                3.18      5.77      1.20     2.18
"["                           3.18      5.77      0.00     0.00
"make.unique"                 1.94      3.52      1.94     3.52
"structure"                   1.02      1.85      1.02     1.85
"object.size"                 1.02      1.85      0.00     0.00
"[["                          0.02      0.04      0.02     0.04
"anyDuplicated.default"       0.02      0.04      0.02     0.04
"anyDuplicated"               0.02      0.04      0.00     0.00

$sample.interval
[1] 0.02

$sampling.time
[1] 55.16
```

**Comment by mikebessuille** [comment]
Should investigate for 1.4-Juliet-Rose.  It probably doesn't gate the patch release so will fix depending on the nature and risk of the fix.

**Comment by astayleraz** [comment]
Verified in Version 1.4.1534 on Mac and R 4.0.3 I was able to run the 2 sample code examples and set a breakpoint and debug. I was not seeing R hang on me. Closing as fixed.

**Comment by jwarren1984** [comment]
This is still an issue with R 4.1.0 and Rstudio 1.4.1106.

**Comment by kevinushey** [comment]
@jwarren1984: The issue is fixed in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by jwarren1984** [comment]
@kevinushey I'm now running Rstudio Pro RStudio Pro 1.4.1716-3 - Windows 10 (64-bit) on top of 4.1.0 and still experiencing the problem. Any ideas?

**Comment by jwarren1984** [comment]
@kevinushey Actually it seems to be working a little better; i.e., the console eventually responds (in maybe a minute or so). But if I call the function directly it responds immediately. And to be clear, I'm running the exact example you referenced.

**Comment by kevinushey** [comment]
@jwarren1984 Thanks -- I've reproduced this locally again.

I think it might actually depend on how the example is run. If I run the example in https://github.com/rstudio/rstudio/issues/5158#issuecomment-763326223 by saving that code to a file, and then source-ing it, it runs fine.

However, if I try to run it line-by-line (e.g. via Ctrl + Enter), then the session hangs.

Does that match your experience?

**Comment by kevinushey** [comment]
FWIW, the root of this problem is that we're trying to deparse a very large call object, and deparsing of large calls is very slow. For example:

```
> options(deparse.max.lines = 2)
> big <- mtcars[rep(1, 250000), ]
> x <- call("test", x = big)
> system.time(deparse(x))
   user  system elapsed
  3.065   0.014   3.093
```

I'm not yet sure what the most appropriate fix here is.

**Comment by jwarren1984** [comment]
Yep, if I have the "do.call()" in the file and source it, then when it enters the browser the console seems to behave normally. But if I execute the "do.call()" with ctrl+enter or in the console itself, it hangs up. Good catch, although I have no idea what it means.

Also, there's something weird going on with the timing. For example, this output of a single character string shows up as having zero elapsed time, but in fact it took about 30 seconds or so.

```
Browse[1]> system.time("bummer")
   user  system elapsed 
      0       0       0 
```

**Comment by jwarren1984** [comment]
@astayleraz Can we reopen this since it appears to still be an issue on at least some platforms?

**Comment by astayleraz** [comment]
Verified fixed in Version 1.5.73 on Mac 10.15.7, Win 10, and ubuntu 20 I was not seeing R hang on me. Closing as fixed but please let us know if you are still having issues with this.
