### ISSUE TITLE
Appearance pane (in Options) takes a long time to load

### ISSUE THREAD

**Issue by ntthung** [rstudio/rstudio#6268]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.3.820
    OS Version      :  Windows 10
    R Version       :  3.6.2

### Steps to reproduce the problem
Go to Tools/Global Options, click Code, then click Appearance
### Describe the problem in detail
The left hand side of the Appearance setting is loaded but the right hand side (the preview) takes a long time (1-10s) to load. This results in two overlapping panes (see picture below).
### Describe the behavior you expected
It should load automatically.

![image](https://user-images.githubusercontent.com/22501446/74941807-a6aff680-542e-11ea-905a-fe5e1065b5ac.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ntthung Thank you for raising the issue! In order to reproduce, how many new themes have been added? I'd like to figure out if this is because there are many custom themes, or if it happens regardless of the number.

**Comment by ntthung** [comment]
Hi Ron, I have only one custom theme, the [panda](https://github.com/bradlindblad/rstudio-panda) theme. Btw I installed that theme but didn't use its fonts.

This problem only occurs as I upgraded to the dev version of Rstudio (1.3x). I didn't have this problem with the stable versions (1.2x).

**Comment by ronblum** [comment]
I see a similar delay, though shorter, when using RStudio Desktop 1.3.842 on MacOS 10.15. This is not an issue RStudio Server. In addition, this is a regression, as it the pane shows up instantaneously in RStudio Desktop 1.2.5033.

**Comment by BartJanvanRossum** [comment]
I was going to file this same issue myself (RStudio 1.3.878, Windows 10 desktop). I have no custom themes installed at all.       
Something additional I observed was that the moment I hover over the left hand side of the appearance pane the right hand side appears. If I don't hover over the left hand side the right hand side doesn't seem to appear at all.

**Comment by ntthung** [comment]
@BartJanvanRossum Indeed, the right hand side appears quickly with mouse movement!

**Comment by hhmacedo** [comment]
I have the same issue.
RStudio 1.3.938 - Windows 10/8/7 (64-bit)
Windows 10 Home 1909

I would add that if I click Appearance again (a second time in sequence), the right side appears immediately.

**Comment by calpan** [comment]
I have the same issue, and have also observed that the preview appears to update when the mouse is moved either into or out of the left-hand side of the appearance pane.  In addition, when scrolling through the theme selector with the keyboard, the last update to the preview seems to be deferred until the mouse is similarly moved, and sometimes no theme seems to be previewed at all until the scrolling direction has been reversed.  This is more easily shown than described; see below:

![lagging](https://user-images.githubusercontent.com/806424/82858049-9db84080-9ec7-11ea-8452-8068adc5d67a.gif)

This is on RStudio Version 1.3.959 ("Middlemist Red" (3a09be39, 2020-05-18) for Windows) on Windows 10 version 1803 (build 17134.1304)

**Comment by jmcphers** [comment]
I reproduced this on Windows 10 on 1.4.479 (so certainly not fixed with any recent change). It feels like this can take an unbounded amount of time if you don't do something to invalidate the region (have seen it fail to repaint for several minutes). 

It isn't a matter of something being slow or expensive to run; in fact CPU usage is virtually none in this state. This appears to be a QtWebEngine paint bug specific to software rendering; the region covered by the iframe that hosts the preview is just not getting invalidated or painted. Doing anything that causes a repaint causes the iframe to appear.

I doubt we can get Qt to fix the paint bug, so the fix here is probably going to be to jostle the layout once the frame is loaded to force a repaint.

**Comment by jmcphers** [comment]
QA note: The fix dramatically speeds up the "load" time but does not eliminate it (Qt still takes a split second to redraw the frame, but it should take < 1s).

**Comment by R-Hannibal** [comment]
Verified Not Fixed on: RStudio Version - 1.3.1045, R Version - 4.0.2, Windows 10 - Desktop

I'm still seeing long 'load' times on the latest preview. Mousing over the preview area loads it instantly, but without some interaction it's taking easily upwards of 30 seconds to paint on it's own.

**Comment by jmcphers** [comment]
Fixed in 1.3 via #7226.

**Comment by R-Hannibal** [comment]
Verified Not Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows/Mac - Desktop

@jmcphers - After doing some further comparison testing between 1.3.1045 / 1.3.1054 / as well as the pre-check-in build from the other day, this issue still appears to be persistent in all 3 builds. Gif below is from 1.3.1054 (but I have also seen the load take multiple minutes/not pop-in until mouse over):

![LongPaintTime](https://user-images.githubusercontent.com/62304541/85972229-ff6f3d00-b994-11ea-9d35-8f9df6ae6ad2.gif)

**Comment by calpan** [comment]
The same behavior is still present in 1.3.1056, with the exception that the initial load of the preview is now fixed.
![2020-07-10_14-27-02](https://user-images.githubusercontent.com/806424/87205469-5c83c080-c2bc-11ea-9375-b991fbb34cbd.gif)

**Comment by R-Hannibal** [comment]
@calpan - thanks for checking this on the latest preview and providing the update.

This issue is proving difficult to fix due to the current limitations of QT. We decided to move it out of of the 1.3 waterlily patch (current build up on preview) so that we can get that release out to the community as quickly as possible. 

We'll try to address this again in a future release, apologies for the inconvenience.

**Comment by jmcphers** [comment]
This issue is very difficult to address as it doesn't repro 100% of the time and is due to a paint bug in QtWebEngine/Chromium. Stuff I've tried so far:

- Laying out the Appearances pane using *flex-layout* instead of nested tables, on the theory that deeply nested tables are part of the problem (no difference)
- Laying out all of the options panes in Global Options using *flex-layout* instead of nested tables, on the same theory (no difference)
- Positioning the preview frame absolutely/explicitly, using `position: absolute`, etc. (no difference)
- Using tools like `getBoundingClientRect()` to force a relayout/redraw, as suggested in [What forces layout/reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a) (no difference)
- Adding a load handler to the `<link>` element that loads the theme CSS, and trying to force repaint when the theme CSS loads (no difference)
- Using `z-index` instead of `transform` to trigger a repaint (no difference)

I'm taking this out of Goldenrod as we just don't have a bead on a solution.

**Comment by gtritchie** [comment]
I have been unable to reproduce this issue with the Electron builds on Windows-10 or 11 so believe this is fixed (as hoped) by the move to Electron (and thus use of a very current version of Chromium).
