### ISSUE TITLE
No scrollbar in source editor on Mac desktop

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#6432]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.898 (repros with all 1.3 builds)
    OS Version      : macOS 10.15.3
    R Version       : Any

### Steps to reproduce the problem
- Using RStudio Desktop for Mac, and the TextMate (default) theme, open a long source file
- In Mac system settings, under General, for "Show Scroll Bars", select either "Automatically" or "When Scrolling"
- On a Macbook with trackpad, or an iMac with Magic Trackpad 2, scroll around the document (e.g. two-finger scrolling)
- Alternatively, scroll around the document with keyboard (arrows, PgUp/PgDn, fn+up/fn+down, etc)

### Describe the problem in detail
- No scrollbar appears in the source editor

### Describe the behavior you expected
- Scrollbar appears

### Other notes
- Using macOS setting of "Always" for "Show Scroll Bars" does make scrollbar appear when scrolling (though not always as the setting is supposed to do)
- Using an external mouse with a mouse-wheel (I tried a USB mouse, not an Apple Magic Mouse), the mouse-wheel scrolling causes scrollbars to appear
- RStudio 1.2 works as expected
- RStudio 1.3 Server in Chrome or Safari works as expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Also tried with a build using Qt 5.14.1 (for other reasons), and confirmed this problem still happens.

**Comment by felixradtke** [comment]
I can confirm that I also encounter this bug after upgrading from 1.2.5042-1 to 1.3.959-1 (stable release). I am running macOS 10.15.5 and I use the trackpad and a magic mouse 2.

**Comment by retorquere** [comment]
Same here, with magic mouse.

**Comment by felixradtke** [comment]
Is there an official way to submit bugs to the team? I am encounting this bug and one other bug since one specific build and am wondering if the team pays attention to the issues listed here. If have posted the issues in the RStudio forum (https://community.rstudio.com/t/sections-dont-work-in-1-3-959/67707 ; https://community.rstudio.com/t/scrollbars-missing-in-1-3-959/67189/5) but haven't received a response.

**Comment by gtritchie** [comment]
@felixradtke Yes, this is the correct place to submit bugs, and to add comments to existing bugs. We do monitor all issues and read all the comments. It takes time to make fixes in some cases, and we can't comment on every response.

**Comment by gtritchie** [comment]
Initial test with Qt 5.15.0 shows this as fixed.

**Comment by gtritchie** [comment]
Putting in 1.4 milestone for further discussion.

**Comment by gtritchie** [comment]
Fixing this would require us to update to Qt 5.15; updating to a new Qt major build (we are currently on 5.12.8).

Ask @kevinushey or @jmcphers how this has gone in the past. :-) Very expensive (though ultimately unavoidable so long as we're using QtWebengine).

That said, 5.15 would bump us up to a much newer Chromium engine. We are currently using version 69 from 2018-09-04, whereas 5.15 uses v80 from 2020-02-04; so we could benefit from improved performance and HTML/CSS/JS updates in the newer Chromium.

There have been some fixes to accessibility since Qt 5.12; none of them seem sufficient to really move the dial, but I am going to produce a private build of RStudio for Windows Desktop using 5.15 and have @jooyoungseo try it out via JAWS and get his take on it, as another data point.

**Comment by retorquere** [comment]
Isn't this a Mac-specific bug? Does windows also show this problem?

**Comment by kevinushey** [comment]
It is indeed a macOS-specific issue.

**Comment by mikebessuille** [comment]
Consider uprading QT version early in 1.5

**Comment by gtritchie** [comment]
This is fixed by Qt 5.15.1+ on macOS.

**Comment by gtritchie** [comment]
Moving back out of 1.4; no longer looks like we'll need to update Qt for 1.4.

**Comment by luispuerto** [comment]
I just realized about this bug… It's not incredible problematic, but slightly annoying. Is this going to be fixed on 1.5 version, then?

**Comment by gtritchie** [comment]
Confirmed fixed by Electron (via testing of prototype, so keeping open until fixed in production code).

**Comment by henrique-andrade** [comment]
> Isn't this a Mac-specific bug? Does windows also show this problem?

I'm experimenting same problem on elementary OS 5.1 (Ubuntu-based Linux distro)

**Comment by waterlineee** [comment]
System Preferences >> General >> Show scroll bars: Always

**Comment by hzs2589** [comment]
Hi dear sir, I encountered this issue today after I upgraded my RStudio to version 2021.09.1+372 . So is there anything I can do to fix this? Should I install and update this QT thing? Sry I'm only a coder and know very few about developing.

My OS: macOS Catalina (10.15.7)
RStudio version: 2021.09.1+372 
R version: newest

Thx a lot.

**Comment by gtritchie** [comment]
There is nothing you can do until we release a new version with a fix. That should happen sometime in 2022. Sorry for the problem.

**Comment by jmcphers** [comment]
Just got another report of this, glad to hear it's fixed in Electron!

**Comment by gtritchie** [comment]
Verified working in Electron build 2022.06.0-daily+244 on macOS 12.3.

**Comment by asalavaty** [comment]
> Verified working in Electron build 2022.06.0-daily+244 on macOS 12.3.

I have the latest version of 2022.07.1 Build 554 and R 4.2.1 (on M1 Silicon mac), and the scroll bar is still missing!

**Comment by kevinushey** [comment]
@asalavaty the fix isn't in the current release; you'll have to find it within the Electron development builds (currently experimental and available at https://dailies.rstudio.com)
