### ISSUE TITLE
R starts twice when opening Rstudio

### ISSUE THREAD

**Issue by szimmer** [rstudio/rstudio#6907]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042 and 1.3.958
    OS Version      :  Windows 10 (64 bit)
    R Version       : 4.0.0

### Steps to reproduce the problem
1. Open Rstudio
### Describe the problem in detail
R starts twice when opening Rstudio. I've tried re-installing Rstudio and installing a preview version. I always see the start-up text twice

```
R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
```
This doesn't happen when opening the standard RGui from CRAN.

Discussed on Rstudio community as well: https://community.rstudio.com/t/r-starts-twice-when-opening-rstudio/66535 

### Describe the behavior you expected
I expect to only see the start-up message for R once.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
See https://github.com/rstudio/rstudio/issues/3439, https://github.com/rstudio/rstudio/issues/4085. We have occasional reports of this but have never been able to reliably reproduce in-house.

**Comment by jmcphers** [comment]
Also, for what it's worth, this isn't R starting twice but just the banner printing twice -- R is only starting once, so this is totally harmless!

**Comment by kevinushey** [comment]
I believe this should be fixed via https://github.com/rstudio/rstudio/commit/874cf926be99466cd1f78d515a1ac166f84abe34 (https://github.com/rstudio/rstudio-pro/pull/1675 in Pro repository)

**Comment by tentacles-from-outer-space** [comment]
I still have this issue. R-4.0.2 and RStudio Desktop 1.3.1073 on Win10. It happens on old rstudio projects (but not on new created ones).

If I close all open files then banner is duplicated rarely, when some files are open then duplicated always.

Event logs for "no files open" scenario looks the same (graph) regardless of whether banner is duplicated or not. But in details the third `get_events` call one return list with ids 11-12 vs 1-12 (duplicated from first `get_events`).

**Comment by R-Hannibal** [comment]
@tentacles-from-outer-space - thanks for checking in and letting us know that this issue is still impacting you.

The ticket that @kevinushey mentioned as potentially fixing this issue (it has not been verified yet, but the thought is that it will fix it) is currently live in our daily build of the upcoming 1.4 release (available for download [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is still present in that build?

**Comment by tentacles-from-outer-space** [comment]
Well, on 1.4.722 still happens. For my old project definitely less often (like one out of ten? almost never), but seems like it loading faster. But I got another old project on a network share, which loads slower (reading times?) and duplicate banner every time.

**Comment by jmcphers** [comment]
Closing since we can't reproduce this and don't have any other leads.

**Comment by tentacles-from-outer-space** [comment]
I checked this with newest version (1.4.1103) and it is still happening. I  was able to reproduce it by makinnng project on network share (to slow down access time) and under heavy load (top cpu usage). 
Not deterministic enough.

**Comment by helske** [comment]
I noticed this for the first time today as well, with the version 1.4.1548. Happened multiple times after closing and starting Rstudio, and then it dissappeared.

**Comment by sclewis23** [comment]
I'm also seeing this on RStudio server v 1.4.1106-5, only with R versions 4.0.0 and above.  If I open a session with R version 3.6.3 no issue.  Also notice loading wheels in the Environment and Files panes when second R banner is waiting to be loaded.

**Comment by kevinushey** [comment]
Also reported in Pro ticket #63358.

**Comment by kevinushey** [comment]
It seems like this happens when:

1. We receive an initial get_events RPC response, containing the R banner as output;
2. A subsequent get_events RPC call gets canceled for some reason;
3. The following get_events RPC then re-requests the last set of events, and so any associated console output is then duplicated.

The underlying question, I think, is why that subsequent get_events RPC is being canceled.

**Comment by kevinushey** [comment]
I have some hints as to why this is happening, at least on master. Basically, the "ep" field on async_completion RPCs is not sent. If the most recent RPC happens to be an async completion RPC, then this will trigger a restart of the get_events stream.

If this happens during startup, this will imply the initial set of events via get_events will be re-retrieved and replayed, leading to the console banner being duplicated.

The solution, I think, is to mark "ep" = "false" on async completions here:

https://github.com/rstudio/rstudio/blob/17118e06102c978494ae3f7b85728ba1016300c4/src/cpp/session/SessionRpc.cpp#L265-L269

And here:

https://github.com/rstudio/rstudio/blob/17118e06102c978494ae3f7b85728ba1016300c4/src/cpp/session/SessionModuleContext.cpp#L2346-L2350

I think now that we're using async RPCs by default, this is going to be a lot more common with 1.5 in high-latency environments, so I think it's worth fixing for 1.5.

**Comment by kevinushey** [comment]
For posterity, an example where we get a seemingly spurious cancellation of get_events:

<img width="244" alt="Screen Shot 2021-07-15 at 5 22 09 PM" src="https://user-images.githubusercontent.com/1976582/125873663-2b01b23d-e035-49f7-acec-7d198497886c.png">

**Comment by sjackson1997** [comment]
I currently have the "banner" showing up three times when I open RStudio, and I came here seeking answers.  I'm running RStudio 1.4.1717 on Windows 10 64-bit, with R 4.1.0 "Camp Pontanezen".  I've noticed the banner sometimes repeats just once or not at all.  Since previous posters indicate this isn't a real problem, I feel better -- just need the reassurance nothing is wrong.
![image](https://user-images.githubusercontent.com/29808605/127588697-0cdf3d71-d498-4b0e-abb2-1ef54a03c31f.png)

**Comment by kevinushey** [comment]
@sjackson1997, would you be willing to test the latest [daily builds](https://dailies.rstudio.com) to see if the issue is resolved there?

**Comment by sjackson1997** [comment]
@kevinushey Sure, I'll give it a shot.  I do real work on this machine, so hopefully I can keep current version installed in parallel (?).  Sorry for the newb question.  I just usually avoid  daily builds, but I want to help and contribute, so I'm willing to try.

**Comment by ronblum** [comment]
@sjackson1997 That's a valid concern! You can get an installer-less build at https://dailies.rstudio.com/rstudio/oss/windows/xcopy/ which when unzipped contains a copy of RStudio Desktop which you can use for testing, without installing over your current version of RStudio.

**Comment by sjackson1997** [comment]
So far, when I've run a daily build, I've not see the issue repeated using the same computer as my "stable" build which has the issue.  I haven't run it much, though, because I'm usually doing regular work.

**Comment by ronblum** [comment]
@sjackson1997 That's good to hear! I'll mark this issue as closed, then. If you run into any more issues, please let us know.

**Comment by tentacles-from-outer-space** [comment]
I still run into this issue

![image](https://user-images.githubusercontent.com/1562600/141933152-b787e681-e688-4593-aede-7ed3916c321f.png)

**Comment by tentacles-from-outer-space** [comment]
And on server pro
![image](https://user-images.githubusercontent.com/1562600/144243152-ef8d3096-967c-4225-a505-44161502522d.png)

**Comment by kevinushey** [comment]
@tentacles-from-outer-space -- the next time the issue occurs, can you please use `Help -> Diagnostics -> Request Log` and send a screenshot of the output you see? My expectation is you'll see something similar to https://github.com/rstudio/rstudio/issues/6907#issuecomment-881090793.

**Comment by tentacles-from-outer-space** [comment]
On

    RStudio 2021.09.0+351.pro6 "Ghost Orchid" Release (50423e45af21f7b8d57c1937d66cceade58de01a, 2021-09-23) for CentOS 7
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

![image](https://user-images.githubusercontent.com/1562600/145003526-2ca535ef-a0d7-48f7-b22e-015d533c5694.png)

I cannot test on this server but on another I didn't seen it with R-4.1.2

**Comment by kevinushey** [comment]
@tentacles-from-outer-space, thank you -- this is helpful. It looks like, for some reason, the `client_init` event is being sent twice, even though (as far as I can see) the initial `client_init` event request was successfully sent.

There is also an (apparently spurious?) cancellation of the first `get_events` call which has been implicated in other incantations of this issue. We'll have to investigate further.

**Comment by tentacles-from-outer-space** [comment]
And for newest environment.

    RStudio 2021.09.1+372.pro1 "Ghost Orchid" Release (8d64c2e021020e42f0637b056ee9ee5375df9d0e, 2021-11-08) for CentOS 7
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

![image](https://user-images.githubusercontent.com/1562600/145202066-cbf11223-df6e-4c21-a74c-5f6ea8385b93.png)

![image](https://user-images.githubusercontent.com/1562600/145202100-7743393d-0f7c-4c36-a4fe-1e69910c2806.png)

[log.txt](https://github.com/rstudio/rstudio/files/7675729/log.txt)

**Comment by BartJanvanRossum** [comment]
For what it's worth. I had this issue for a long time (see #4085), but with the latest version of RStudio (RStudio 2022.02.0+443) it seems completely gone and only one banner is printed when opening a project.

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you very much! This is good to know—I'm glad to hear that the problem is resolved, at least in your case.

**Comment by astayleraz** [comment]
I ran into this issue with rhel8 and version 2022.06.0-daily+437.pro2

**Comment by kevinushey** [comment]
A somewhat similar issue reported and fixed on the Pro repository: https://github.com/rstudio/rstudio-pro/pull/1675

**Comment by janlimbeck** [comment]
Same problem here. Happens quite regularly with R version 4.3.0 and 
```
RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
```

**Comment by kevinushey** [comment]
@janlimbeck can you share any other details about how you're using RStudio? Is there anything unique about the environment or machine in which you're using R / RStudio?

**Comment by BartJanvanRossum** [comment]
For me the issue was suddenly back yesterday with R 4.3.1 and 

```
RStudio 2023.09.2+508 "Desert Sunflower" Release (8696d2abcc811420a0253f0c9ff8b53cf697f110, 2023-11-16) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.2+508 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
```

Today it is gone again. In principle I'm working on the same pc as yesterday, but yesterday for the first time in quite a long time I was accessing it from home using VPN and today I'm back in the office. Not sure if this is relevant at all, but I thought it might be worth mentioning

**Comment by janlimbeck** [comment]
> @janlimbeck can you share any other details about how you're using RStudio? Is there anything unique about the environment or machine in which you're using R / RStudio?

Let me know what kind of info you need. I do have multiple installations of R on my machine but only one 4.3.0 installation to which R-Studio is pointing. 
I have made some additions to Rprofile.site in the installation folder of R 4.3.0. 
I am calling the checkpoint package and then I am changing the package mirror to `https://packagemanager.posit.co/cran/2023-02-01`.

**Comment by ronblum** [comment]
Closing this issue as fixed. If anyone is still running into this issue, please let us know.

**Comment by janlimbeck** [comment]
Still seeing the same behaviour after startup with the latest version of RStudio.
RStudio 2024.12.1+563 "Kousa Dogwood" Release (27771613951643d8987af2b2fb0c752081a3a853, 2025-02-02) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.12.1+563 Chrome/126.0.6478.234 Electron/31.7.7 Safari/537.36, Quarto 1.5.57

![Image](https://github.com/user-attachments/assets/e33506da-d2bc-41ec-a7b1-2a850a1bc22f)

**Comment by ronblum** [comment]
@janlimbeck This is fixed in Mariposa Orchid, the release currently in development (2025.04). You can test this out if you're interested by downloading on of [the daily builds](https://dailies.rstudio.com/). Please note, though, that these are only for testing purposes, not production.
