### ISSUE TITLE
Fatal Error when switching projects

### ISSUE THREAD

**Issue by pike00** [rstudio/rstudio#7077]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959 [Also replicated in 1.3.1014 Preview]
    OS Version      :  Windows 10 Home 10.0.18363 Build 18363
    R Version       :  4.0.1

### Steps to reproduce the problem

1. Open RStudio to "Project (None)" (i.e .the default)
2. File > "Open Project" > navigate to .RProj file
3. Error pops up, Rstudio says "Cannot Connect to R"

### Describe the problem in detail

When I Open Rstudio and go to open a new project, I get the following error:
![error](https://user-images.githubusercontent.com/6687499/84190392-dda12b00-aa64-11ea-852a-faed6f7a8d9a.png). When I click OK, RStudio says "Cannot Connect to R". I have not been able to find a workaround. 

I am using renv in this project, and have ensured that is updated. [Here](https://github.com/rstudio/rstudio/files/4754377/Rproj.txt) is what my .Rproj looks like (I know it's not supposed to be .txt, I  did that so I can upload it to github). The issue doesn't occur with a new/different project, only with this one specifically. 

In this project, I am utilizing dbplyr and Microsoft SQL to access a remote database and manipulate it in R. I am also using git and RMarkdown to produce my output. 

I have been working on this project for several months. I did have this problem previously, but I fixed it by updated to the latest R (I was on version ~3.6 at that time) and RStudio. 

I've also attached the [Diagnostics Report](https://github.com/rstudio/rstudio/files/4754421/diagnostics-report.txt)

### Describe the behavior you expected

Change/Open Projects as expected.

[x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
[x] I have installed the latest version of RStudio and confirmed that the issue still persists.
[x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
[x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- this should be fixed in the current [preview release](https://www.rstudio.com/products/rstudio/download/preview/). Alternatively, you can update to the latest development version of `renv` with:

```
renv::upgrade(version = "master")
```

**Comment by pike00** [comment]
@kevinushey I tried it with the preview release (1.3.1014) and it did not work. 

How is the renv (Dev version or not) related to the preview release? I tried updating in any case and I still get the error.

What other diagnostics can I supply to help you out?

**Comment by kevinushey** [comment]
Backported a commit that should fix this: https://github.com/rstudio/rstudio/commit/c1343ac0edbf97d324a648bdec96a137a31f34f8

It will also be resolved in the next release of `renv` (hopefully coming soon).

**Comment by R-Hannibal** [comment]
@pike00 , thanks again for finding and reporting this issue. 

We have a fix in place in our latest preview build 1.3.1054 (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by kevinushey** [comment]
QA note: the most recent version of `renv` (0.11.0) also has its own workaround for this issue. However, you should be able to reproduce the crash by creating a file at `~/.Rprofile` with the contents:

```
readline("oh no")
```

If you do this, you should see RStudio crash on startup. (Windows only; "weird" behavior instead on other platforms)

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 x64 - Desktop 

The original reproduction steps were no longer causing the crash and error as originally reported due to an update to the `renv` package. 

Was able to reproduce successfully with the [QA Note provided](https://github.com/rstudio/rstudio/issues/7077#issuecomment-654424312) and confirmed via comparison test that the error does occur in 1.3.959, but not in 1.3.1054 (project opens cleanly either by opening within the IDE or directly from the .Rproj file).
