### ISSUE TITLE
Cursor focuses on History pane's search bar after run in python script

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#7621]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.724
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.2

### Steps to reproduce the problem
Running current line or multiple lines of codes in python script

### Describe the problem in detail
After running codes, cursor jumps to History pane's search bar no matter where the pane is located or whether the current showing pane is History or not. 

### Describe the behavior you expected
Cursor should move to the next line in python script and able to continue to type in the script.

**Comment by ronblum** [comment]
@Fred-Wu Thank you for filing the issue! I'm unable to reproduce it, though, with the same environment. A few questions:
- What desktop are you using? I'm using Gnome.
- Did you see this in RStudio Desktop 1.3.x, or is it new in 1.4?

For what it's worth, I'm running something very simple, from the Source pane:
```
x = 1
print(x) # Format for Python 3
```

**Comment by kevinushey** [comment]
Seems to be a duplicate of https://github.com/rstudio/rstudio/issues/5984?

**Comment by Fred-Wu** [comment]
> @Fred-Wu Thank you for filing the issue! I'm unable to reproduce it, though, with the same environment. A few questions:
> 
> * What desktop are you using? I'm using Gnome.
> * Did you see this in RStudio Desktop 1.3.x, or is it new in 1.4?
> 
> For what it's worth, I'm running something very simple, from the Source pane:
> 
> ```
> x = 1
> print(x) # Format for Python 3
> ```

@ronblum I am using GNOME too. Yes it only happens in 1.4, not in 1.3.x.

**Comment by Fred-Wu** [comment]
> Seems to be a duplicate of #5984?

As in my latest reply in #5984, even no tab in the bottom left quadrant, the NULL window will still raise, and plus the cursor jumps to History search bar when the History is acturally placed in bottom right quadrant.

**Comment by ronblum** [comment]
@kevinushey Since updating `reticulate` should've fixed #5984, should it fix this as well?

**Comment by kevinushey** [comment]
Yes, I believe so. Thanks! (Should be fixed with `reticulate 1.18`)

**Comment by melissa-barca** [comment]
Verified this is fixed with `reticulate 1.18` in 1.4.1013

**Comment by melissa-barca** [comment]
@kevinushey I have reticulate 1.18 installed and am still seeing this behavior in 1.4.1017 Desktop. I can step through a script with `Ctrl + Enter` without issue, but looking closer the History search bar has focus, and when I start typing it the text appears there. This only happens when executing the first python line and when typing `quit` in the `>>>` prompt.

**Comment by melissa-barca** [comment]
Verified in 1.4.1028
