### ISSUE TITLE
error when performing search + replace

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7736]
I have a similar issue. The first two images show output for a search and replace that failed completely. The errors reported are rather cryptic. The overall count of successes vs fails seems totally random: 64 vs 11, when actually nothing seems to have been replaced. Replacement didn't happen in the first file, either, although it reports no error.

When I tried a really small and simple test with just two fake files and one word to be replaced, the whole replacing got stuck. See third image below.

Running version 1.3.1073 on Ubuntu 18.04.4

1
![image](https://user-images.githubusercontent.com/26325512/92189398-e2c61880-eea1-11ea-9221-df826092b0cb.png)
2
![image](https://user-images.githubusercontent.com/26325512/92189427-f7a2ac00-eea1-11ea-9f05-6b10259a21af.png)
3
![image](https://user-images.githubusercontent.com/26325512/92189819-faea6780-eea2-11ea-91fe-4b0bfccb4fc3.png)

_Originally posted by @AltfunsMA in https://github.com/rstudio/rstudio/issues/2066#issuecomment-686894213_

**Comment by Robinlovelace** [comment]
In case it's useful I tried to reproduce the issue in a random project I had open on the latest release of RStudio. I can reproduce the issue reported above, as shown in the gif below.

![Peek 2020-09-04 20-21](https://user-images.githubusercontent.com/1825120/92278167-876d4800-eeec-11ea-9635-219b0feae1f7.gif)

Test undertaken on the following version of RStudio:

```
RStudio
Version 1.3.1073
© 2009-2020 RStudio, PBC
"Giant Goldenrod" (718e6d75, 2020-07-29) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

on Ubuntu 18.04.

**Comment by mikebessuille** [comment]
@melissa-barca , we need to figure out how frequent this problem is.

**Comment by melissa-barca** [comment]
I am able to reproduce this, looking into a fix.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.3.1093, R Version - 4.0.2, Windows 10 x64 - Desktop

Global find and replace across multiple files is completing successfully, tested with a variety of different 'Default text encoding's set, server/Desktop, and multiple supported OSs (thanks @rich-rstudio for the assist in testing out this fix 👍).

**Comment by AltfunsMA** [comment]
Just FYI, this is still crashing my RStudio Server: Version 1.3.1093. R version 3.6.3 (2020-02-29). Ubuntu 18.04

**Comment by Robinlovelace** [comment]
I can see the reported bug in the latest stable release (Version 1.3.1073) but I think it's fixed on the preview version.

**Comment by AltfunsMA** [comment]
Not sure I understand, @Robinlovelace , I'm on stable release 10_93_ already, and it's still crashing my R session? do you mean a preview version after 1093?

**Comment by Robinlovelace** [comment]
Yes, you can download daily builds here I think but would double check with people from the RStudio team such as @kevinushey before confirming: https://dailies.rstudio.com/

**Comment by kevinushey** [comment]
That's correct -- this should be fixed in the 1.4 builds; in particular, you can download the preview release if you'd like to test:

https://rstudio.com/products/rstudio/download/preview/

You can also test via the daily builds, but those should normally be considered unstable and for testing -- they may have bugs from build to build.

**Comment by Robinlovelace** [comment]
Hi @kevinushey I can still reproduce the bug in the latest version, as shown below.

![Peek 2020-10-22 09-11](https://user-images.githubusercontent.com/1825120/96843918-c75d9f80-1446-11eb-879d-fdfa1603f873.gif)

**Comment by Robinlovelace** [comment]
One possibility: using different disks/partitions, I have my OS on an SSD and many projects on a slower but larger hard disk.

**Comment by melissa-barca** [comment]
Hi @Robinlovelace in your example was the first instance of applied properly replaced? The bug fix here was for data loss that was occuring where RStudio displayed a change as correct but did not actually update the file or changed the file in an undesired way. When you see an error message like in the second line it means the calls RStudio made to your system failed at some point and we are displaying the error message the system sent us. Usually I would expect this to be a permissions error (e.g. you have read access but not write). I'm not sure what is causing the `file exists` error, but it looks worth opening another issue for. You may be right that this has to do with RStudio accessing the slower disk. 

@R-Hannibal is this the error you noticed while testing? Were we able to come up with a consistent repro?

**Comment by Robinlovelace** [comment]
> Hi @Robinlovelace in your example was the first instance of applied properly replaced?

Hi @melissa-barca, no the file didn't change. Sounds like one that's tricky to debug, hope my example helps with that.

**Comment by melissa-barca** [comment]
@Robinlovelace Yes your examples do help, we truly appreciate you taking the time to reach out and being so responsive. As I'm struggling to reproduce this, I just want to be sure you're saying `index.Rmd` didn't change in this example? Are you able to provide a video of 1.4 where RStudio shows the text was successfully changed but isn't changed in the file? Thank you.

**Comment by Robinlovelace** [comment]
> As I'm struggling to reproduce this, I just want to be sure you're saying `index.Rmd` didn't change in this example? Are you able to provide a video of 1.4 where RStudio shows the text was successfully changed but isn't changed in the file?

Yes, I'm sure the file didn't change. I think that's what the gif shows. Will give it another spin when I next try out RStudio 1.4 but that may not be for a little while. Worth trying in a Docker container?

**Comment by melissa-barca** [comment]
@Robinlovelace Shortly after I commented I got a repro working with a VM. Don't worry about sending a gif. Thanks!

**Comment by melissa-barca** [comment]
Hi @Robinlovelace and @AltfunsMA Thank you for the clue about your setup, I believe the issue should be fixed for you in the latest daily 1.4.966 available here: https://dailies.rstudio.com/. Please try it out and let us know if it works!

**Comment by Robinlovelace** [comment]
Confirmed: works. On this version of RStudio Server at least:

```
RStudio Server
Version 1.4.966
© 2009-2020 RStudio, PBC
"Wax Begonia" (202ed8d5, 2020-10-23) for Ubuntu Bionic
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
```

![Peek 2020-10-23 15-29](https://user-images.githubusercontent.com/1825120/97016887-302b4180-1545-11eb-8058-1f3f4611d2ce.gif)

**Comment by Robinlovelace** [comment]
Fun fact, that change led to this PR: https://github.com/saferactive/saferactive/pull/51

**Comment by Robinlovelace** [comment]
Does not seem to be fixed on RStudio Server Pro:


![Peek 2020-10-23 15-37](https://user-images.githubusercontent.com/1825120/97017499-e5f69000-1545-11eb-8e67-4b83b6782a12.gif)

**Comment by Robinlovelace** [comment]
Is fixed on RStudio Desktop though :tada: 

![Peek 2020-10-23 15-42](https://user-images.githubusercontent.com/1825120/97017951-7339e480-1546-11eb-9a00-f5d19f903070.gif)

**Comment by melissa-barca** [comment]
Great! We appreciate your patience and clues for getting this figured out. I just merged the code into pro so it will be in a future build by this afternoon or tomorrow.

**Comment by kfeinauer** [comment]
@Robinlocelace Can you check to see if this is fixed in the latest daily for RSP?

**Comment by Robinlovelace** [comment]
Seems to have worked for most replacements:

![image](https://user-images.githubusercontent.com/1825120/97729827-ff11ba80-1aca-11eb-8021-b3dbaa9cab27.png)

**Comment by Robinlovelace** [comment]
Here are some failing lines, in the RStudio pane:

![image](https://user-images.githubusercontent.com/1825120/97729959-236d9700-1acb-11eb-848b-7f675797440c.png)

**Comment by kfeinauer** [comment]
@melissa-barca any ideas on the above errors?

**Comment by Robinlovelace** [comment]
Associated character string in associated .bib file (such long strings are quite common in bibliography files):

```
  abstract = {We show how to route on very large public transportation networks (up to half a billion arcs) with average query times of a few milliseconds. We take into account many realistic features like: traffic days, walking between stations, queries between geographic locations instead of a source and a target station, and multi-criteria cost functions. Our algorithm is based on two key observations: (1) many shortry paths share the same transfer pattern, i.e., the sequence of stations where a change of vehicle occurs; (2) direct connections without change of vehicle can be looked up quickly. We precompute the respective data; in practice, this can be done in time linear in the network size, at the expense of a small fraction of non-optimal results. We have accelerated public transportation routing on Google Maps with a system based on our ideas. We report experimental results for three data sets of various kinds and sizes.},
```

Strange thing: although the red message said it failed, it seemed to have succeeded as you will see by searching for 'shortry' above.

**Comment by Robinlovelace** [comment]
Update: I used the command line utility `rg` to identify failing lines and they all seem to be pretty long. Hope this helps with debugging this one:

```
rg test
vignettes/refs_training.bib
46:  abstract = {This article examines the conditions required for using Internet search data as measures of aggregate issue salience. Internet data have clear advantages over survey data in terms of cost, availability and frequency. These advantages have led the media and some researchers to use Internet search data as proxies for public opinion. However, these analyses do not present systematic evidence that search data tell us about the general public's views rather than those of an unrepresentative subset. This article outlines a general method for assessing the validity of search data against existing measures, including content validity and criterion validity. To this end, weekly Google search data are tested against Gallup's “most important problem” question. The article finds the salience of four issues, fuel prices, the economy, immigration and terrorism, can be measured in the United States using search data. Weekly measures of issue salience are generated for these issues, from 2004 to 2010, for empirical analysis. The search indices performed less well outside of these domains.},
314:  abstract = {There has been much excitement among quantitative geographers about newly available data sets, characterized by high volume, velocity, and variety. This phenomenon is often labeled as “Big Data” and has contributed to methodological and empirical advances, particularly in the areas of visualization and analysis of social networks. However, a fourth v—veracity (or lack thereof)—has been conspicuously lacking from the literature. This article sets out to test the potential for verifying large data sets. It does this by cross-comparing three unrelated estimates of retail flows—human movements from home locations to shopping centers—derived from the following geo-coded sources: (1) a major mobile telephone service provider; (2) a commercial consumer survey; and (3) geotagged Twitter messages. Three spatial interaction models also provided estimates of flow: constrained and unconstrained versions of the “gravity model” and the recently developed “radiation model.” We found positive relationships between all data-based and theoretical sources of estimated retail flows. Based on the analysis, the mobile telephone data fitted the modeled flows and consumer survey data closely, while flows obtained directly from the Twitter data diverged from other sources. The research highlights the importance of verification in flow data derived from new sources and demonstrates methods for achieving this.},
801:  abstract = {Transport planning, infrastructure project evaluation and policy making, particularly at the urban level, continue to be important issues in the 21st century. Transport modelling requires mathematical techniques in order to make predictions, which can then be utilised in planning and design. This is the basis for improved decision-making and planning in the transport arena. Building on the tremendous success of the previous editions, the new Modelling Transport continues to be the state of the art text in its field. As before, this third edition provides comprehensive and rigorous information and guidance, enabling readers to make practical use of every available technique. Presenting the following features: * A substantially updated section on data collection techniques * An examination of the latest topical modelling approaches, including new material on Probit Model estimation (now possible in practice) and Mixed Logit specification and estimation * New treatment of joint time-of-travel and assignment modelling * Significant new material on Stated Preferences * Added coverage of travel time valuation and, importantly, of the valuation of externalities such as accidents and environmental effects This book is the leader in its subject area, and gives the reader a unique contemporary account of key transport modelling techniques and applications. As before, each subject is approached as a modelling exercise with discussion of the roles of theory, data, model specification, estimation, validation and application. Techniques are included for selecting the right level of analysis and detail for modelling purposes, as well as how to adapt existing tools to serve the needs of regular updating of models and plans. Graduate and postgraduate students in transport engineering and planning, practicing transport engineers, consultants, planners and professional societies, as well as government agencies and district and city councils will find this an essential and valuable text.},
```

**Comment by kevinushey** [comment]
Looks like we have a hard-coded limit of 1000 characters here:

https://github.com/rstudio/rstudio/blob/fce9ebe0c2a87c8c29f944418a2be158ca9f2440/src/cpp/session/modules/SessionFind.cpp#L1010-L1022

https://github.com/rstudio/rstudio/blob/fce9ebe0c2a87c8c29f944418a2be158ca9f2440/src/cpp/session/modules/SessionFind.cpp#L68

I think it would be reasonable to bump that up.

**Comment by mikebessuille** [comment]
@Robinlovelace , just wanted to say Thank You for your tremendous support.   The detail and diligence you put into your bug reports and analysis is outstanding, and really helps my team.   Thank you!
