### ISSUE TITLE
Stack near-overflow when installing package

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8537]
I see this message very often when I'm working on a package project and click `Install and Restart` in the build pane:
```
Error: C stack usage  7969312 is too close to the limit
Error saving session (options): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.

Restarting R session...
```

**Steps to reproduce:** (not very sure)
* Use an R package project.
* Use R normally, creating lots of variables, filling the console, and so on.
* Click "Install and Restart"

**Setup:** RStudio 1.4.1056, running on debian linux, R 4.0.3.

**Comment by kevinushey** [comment]
This sounds like a bug that should be resolved either in the latest preview releases or by ensuring `readr` + `cpp11` are all up-to-date.

**Comment by david-cortes** [comment]
@kevinushey : still seeing it in RStudio 1.4.1078 and readr 1.4.0.

**Comment by kevinushey** [comment]
Darn. If that's the case then I'm not sure what's going on; it's likely something unique to your project and without more information / a reproducible example there's likely not much we can do to help.

**Comment by dagola** [comment]
@kevinushey I encountered the same error today.

I build a reproducible example which is available here: https://github.com/dagola/readr_build_install_bug.
Just check out the repo, open the project and hit `Ctrl+Shift+B` two times. The second time it should give the error.

You can invert comments here to circumvent this error: https://github.com/dagola/readr_build_install_bug/blob/1670e03c9695020406149cef77ad4f48489b22bf/R/hello.R#L3-L9. 

Using `read.csv` instead of `read_csv` does not result in this error leading to the assumption that `readr` is the root cause?

----------------------------------------

My system:
```
> Sys.info()
                                      sysname                                       release 
                                      "Linux"                            "5.4.0-56-generic" 
                                      version                                      nodename 
"#62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020"                                            "" 
                                      machine                                         login 
                                     "x86_64"                                            "" 
                                         user                                effective_user 
                                           ""                                            "" 

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] rbib_0.1.0

loaded via a namespace (and not attached):
 [1] fansi_0.4.1       withr_2.3.0       assertthat_0.2.1  crayon_1.3.4      R6_2.5.0         
 [6] lifecycle_0.2.0   magrittr_2.0.1    pillar_1.4.7      cli_2.2.0         rlang_0.4.9      
[11] renv_0.12.3       rstudioapi_0.13   vctrs_0.3.5       ellipsis_0.3.1    tools_4.0.2      
[16] readr_1.4.0       glue_1.4.2        hms_0.5.3         compiler_4.0.2    pkgconfig_2.0.3  
[21] sessioninfo_1.1.1 tibble_3.0.4  
```
`cpp11` is installed and `@v0.2.4`. RStudio is Version 1.3.1073.

----------------------------------------

My second system:
```
> Sys.info()
                                                                                             sysname 
                                                                                            "Darwin" 
                                                                                             release 
                                                                                            "19.6.0" 
                                                                                             version 
"Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64" 
                                                                                            nodename 
                                                                                                  "" 
                                                                                             machine 
                                                                                            "x86_64" 
                                                                                               login 
                                                                                              "root" 
                                                                                                user 
                                                                                                  "" 
                                                                                      effective_user 
                                                                                                  "" 

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] rbib_0.1.0

loaded via a namespace (and not attached):
 [1] readr_1.4.0     compiler_3.6.1  magrittr_2.0.1  ellipsis_0.3.1  R6_2.5.0        hms_0.5.3       tools_3.6.1    
 [8] pillar_1.4.7    rstudioapi_0.13 tibble_3.0.4    crayon_1.3.4    vctrs_0.3.5     lifecycle_0.2.0 pkgconfig_2.0.3
[15] rlang_0.4.9     renv_0.12.3   
```
RStudio Version 1.3.1093

**Comment by dagola** [comment]
Using RStudio Version 1.4.1078 the error is **not** reproducible.

**Comment by kevinushey** [comment]
Thanks @dagola: that's what I would expect, as the latest preview release contains mitigations for exactly this bug.

**Comment by ronblum** [comment]
@david-cortes Is the problem resolved in 1.4.1081, by chance?

**Comment by david-cortes** [comment]
@ronblum I'm unfortunately done with this project I was doing which implied `readr` calls. I tried it a few times again with 1.4.1081 and didn't experience the issue, but that was only a few minutes of usage.

**Comment by david-cortes** [comment]
@ronblum  correction: I'm still seeing this message sometimes with 1.4.1081.

**Comment by ronblum** [comment]
@david-cortes Darn it. @kevinushey Is there anything in the environment that we might need to adjust to try to reproduce/make it go away?

**Comment by kevinushey** [comment]
I think unfortunately at this point we'd need a reproducible example to say more.
