### ISSUE TITLE
After recover(), the code window browses to the top of file after every evaluation

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#8789]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4
    OS Version      : Windows 10
    R Version       :  3.6.1

### Steps to reproduce the problem
Video capture attached:
https://user-images.githubusercontent.com/73080/105606439-2d3d2880-5da2-11eb-9a20-c59431859a7f.mp4

In short:
1) Type `options(error=recover)`
2) `stop` inside a function
3) Choose anything in the recover menu
4) The code editor focuses on the `stop` line.
5) Evaluate any statement at the console
6) --> The code editor jumps to the top of the current file.

This can get annoying while debugging..

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by OfekShilon** [comment]
Similar to: https://github.com/rstudio/rstudio/issues/7220

**Comment by OfekShilon** [comment]
It should be said that this occasionally happens without `recover` - just stopping at a breakpoint and evaluating expressions at the console.  The `recover` just makes it consistent for me.

Are you able to reproduce this?

**Comment by ronblum** [comment]
@OfekShilon Thank you for raising this! I can reproduce it with the code in your movie, in both
- RStudio Desktop 1.4.1507 on MacOS 11.1
- RStudio Server 1.4.1103 on Red Hat 8.3

We'll review this as we continue development of RStudio.

Note: code used to test is
````
morethanonepage <- " a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
"

f <- function(x) {
    stop("error")   #invoke recover
    return(x + 3)
}
````

**Comment by kevinushey** [comment]
Note: reproduces in 1.3.1093 and 1.2.5042 so it's not a regression (but it is quite annoying).

**Comment by OfekShilon** [comment]
This one is really hurting productivity :(
Any word on the fix?

**Comment by OfekShilon** [comment]
Any chance of fixing this?

**Comment by jmcphers** [comment]
I made a fix that might have addressed this. Have you tried a daily build recently?

https://dailies.rstudio.com/

**Comment by OfekShilon** [comment]
@jmcphers I just reproduced with the most recent daily build:
RStudio 2022.01.0-daily+183 "Prairie Trillium" Daily (bcc8655ba3676e3155d80296c421362881340a0f, 2021-11-01) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by jmcphers** [comment]
Urgh, sorry to hear that! :-(

**Comment by kevinushey** [comment]
Here's (I think) a similar reproducible example:

```
debug(stats::rnorm)
stats::rnorm(1)
```

This opens the debugger. Then, try to execute:

```
.rs.api.documentOpen(tempfile(fileext = ".R"))
```

The new tab is opened, but then focus is immediately returned to the debugged tab. Similarly, trying to type and execute any code in the newly-opened temporary file also causes focus to return to the debugged tab.

With older versions of RStudio (e.g. 1.4.1106), focus is not returned to the debugged tab so eagerly.

**Comment by kevinushey** [comment]
Sorry; the issue I described is indeed resolved in the latest daily builds.

**Comment by OfekShilon** [comment]
Still around, still annoying

**Comment by mikebessuille** [comment]
@OfekShilon we fixed something similar recently; could you please try the latest daily of Spotted Wakerobin from https://dailies.rstudio.com/ and see if it's fixed?

**Comment by OfekShilon** [comment]
@mikebessuille  I'm afraid this is still present in Spotted Wakerobin, 2022.06.0 Build 443

**Comment by OfekShilon** [comment]
It needs to be clarified: while at `browser` (invoked from `recover`), if I'm at an entirely different file and evaluate something at the console -  the focus returns to the file that initially invoked `stop`, not the current file (as my original bug phrasing said)

**Comment by kevinushey** [comment]
Thanks for clarifying. From what I can see, debug contexts created via `browser()` (or explicit breakpoints) now work as expected -- that is, I don't see any issue with this code:

```
f <- function(x) {
    browser()
    return(x + 3)
}
```

However, I do see it with this code:

```
f <- function(x) {
    recover()
    return(x + 3)
}
```

So it seems like this is something specific to how the debugger context is initialized when `recover()` is used.

Internal note: one potentially related factoid is that we have extra "stuff" on the call stack when `recover()` is used; e.g.

<img width="1036" alt="Screen Shot 2022-05-25 at 10 16 12 AM" src="https://user-images.githubusercontent.com/1976582/170323248-bf2d977f-b3f6-4815-9553-e1ceb9aba860.png">

For what it's worth, `recover()`s job is to basically call `browser()` within a loop, e.g. its definition has

```
        repeat {
            which <- menu(calls, title = "\nEnter a frame number, or 0 to exit  ")
            if (which) 
                eval(substitute(browser(skipCalls = skip), list(skip = 7 - 
                  which)), envir = sys.frame(which))
            else break
        }
```

The way `browser()` is evaluated here might be confusing RStudio.

**Comment by OfekShilon** [comment]
This report has been here for ~2Y, the actual bug probably much much longer, and it's still maddening... Any chance of looking into it?

**Comment by OfekShilon** [comment]
@kevinushey  here's a simpler `recover` version that still reproduces the problem:
```r
options(error=browser)      # As you noted, rstudio stays in place when commands are evaluated on the console
my_recover <- function()  { eval(substitute(browser())) }
options(error=my_recover)   # rstudio jumps between files 
```

**Comment by kevinushey** [comment]
Thanks -- sorry, I don't have the bandwidth to investigate further right now.

**Comment by Ezoorp** [comment]
I have encountered this issue as well on R version 4.4.1 (2024-06-14)

**Comment by kevinushey** [comment]
@Ezoorp this should be fixed in the latest daily builds, if you're able to download and test: https://dailies.rstudio.com
