### ISSUE TITLE
Sweave .Rnw -> .tex `Compile PDF` runs into error `...pdflatex (exit code -1073740791)`

### ISSUE THREAD

**Issue by gwd999** [rstudio/rstudio#9019]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103 and 1.4.1106-4 
    OS Version      :  Windows 10 PRO 20H2 Build 19042
    R Version       :  R-3.6.3 and R-4.0.4 and pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.2)

### Steps to reproduce the problem
File -> New File -> R Sweave 
Content of example file 'test_miktex_sweave.Rnw':  
```
\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

some text 

\end{document}
```
### Describe the problem in detail
Compile PDF output: 
```
Writing to file test_miktex_sweave.tex
Processing code chunks with options ...

You can now run (pdf)latex on 'test_miktex_sweave.tex'
Running pdflatex.exe on test_miktex_sweave.tex...failed
Error running C:/Users/USER/AppData/Local/Programs/MiKTeX/miktex/bin/x64/pdflatex.exe (exit code -1073740791)
```
### Describe the behavior you expected
.pdf file created from within RStudio 

Remark: switching to Terminal in working directory and issuing command 
`pdflatex test_miktex_sweave.tex` will produce the .pdf, since execution (exit code -1073740791) stops only AFTER 'test_miktex_sweave.tex' has been created in the document directory. 

```
$ pdflatex test_miktex_sweave.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.2)
entering extended mode
(test_miktex_sweave.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18> xparse <2020-03-03>
(C:\Users\USER\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
...
....
```

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

=== ORIGINAL PART OF ISSUE ==================

Just my 2ct on this - it does not seem to be linked to "tinytex" exclusively - at least if you deselect `Use tinytex when compiling` (or even remove the package completely) `Compile PDF` runs into error `...pdflatex (exit code -1073740791)`

_Originally posted by @gwd999 in https://github.com/rstudio/rstudio/issues/8725#issuecomment-785409033_

pdflatex.log
```
2021-02-24 23:29:31,150+0100 INFO  pdflatex - this process (2188) started by 'rsession' with command line: C:/Users/USER/AppData/Local/Programs/MiKTeX/miktex/bin/x64/pdflatex.exe --version
2021-02-24 23:29:31,163+0100 INFO  pdflatex - allowing known shell commands
2021-02-24 23:29:31,181+0100 INFO  pdflatex - this process (2188) finishes with exit code 0
```
Error is also present in 1.4.1106-4 preview. 

There was a post on Stackoverflow that mentions this behaviour with a workaround ["solution":](https://tex.stackexchange.com/questions/582041/r-sweave-does-not-compile-to-pdf/582528#582528) to uninstall MikTex and install an older version (MiKTeX64-2.9.7269-basic) and not update Miktex or the packages, which is not the most sustainable/promising strategy imho.

**Comment by ronblum** [comment]
@gwd999 Thank you for raising that the issue is more broad! Do you have the same environment and code as in the original issue?

**Comment by gwd999** [comment]
@ronblum - I have beefed the info in my issue

**Comment by dbrookswr** [comment]
Just to add this also occurs for knitr. I just installed RStudio and MikTeX and also getting the same error for knitr. Works fine on older installations these and the TeX file created by RStudio did compile into a pdf in TeXworks with pdfLaTeX+MakeIndex+BibTeX.

**Comment by ClaudiusL** [comment]
I can confirm that this also occurs for MikTeX + knitr. Not being aware of this bug and the related posts on Stackoverflow, I summarized the issue here: https://community.rstudio.com/t/rnw-file-compile-pdf-button-fails-after-miktex-update/99482

**Comment by cderv** [comment]
@dbrookswr @ClaudiusL if you found an issue with **knitr** + **MikTeX** that you can reproduce in the R Console, please open an issue in https://github.com/yihui/knitr so that we look into your reproducible example. 

If this is only when clicking on `Compile PDF`, then it is related to the IDE probably. 

Thank you

**Comment by ClaudiusL** [comment]
@cderv It's only the "Compile PDF" button.

**Comment by ClaudiusL** [comment]
Short update: In the [RStudio community thread](https://community.rstudio.com/t/rnw-file-compile-pdf-button-fails-after-miktex-update/99482/2), @cderv recommended to use the RStudio option "Use tinytex when compiling .tex files", which makes RStudio use the tinytex package without installing the TinyTeX distribution globally. 

This works for me (although [currently only in the RStudio daily build](https://community.rstudio.com/t/rnw-file-compile-pdf-button-fails-after-miktex-update/99482/5?u=claudiusl)).

**Comment by dbrookswr** [comment]
Thanks, I will try that if I go back to RStudio.

**Comment by gwd999** [comment]
not sure - had no time to verify yet - but could it be that this issue is solved as well by #2788

**Comment by dbrookswr** [comment]
Thanks for that. I use MiKTeX for a  few things, and from the name
tinytex I had assumed with was a more limited version, but I might try it.
Right now I just compile into TeX in RStudio and compile elsewhere into pdf.

Dan

**Comment by fego1290** [comment]
I am having the same problem. Using tinytex doesn't solve it. I write the .tex-file in RStudio and compile it elsewhere. Annoying.

**Comment by dbrookswr** [comment]
That's what I have been doing. It also means that I can't suggest using
this for my students.

**Comment by fego1290** [comment]
Sometimes solutions can be simple: I updated both RStudio and MikTeX (incl. all packages I use) to the newest version and now it works.

**Comment by gwd999** [comment]
@fego1290 so you have the impression (as well) that potentially #2788 or one of the other closed tickets for RStudio release 1.4 fixed this? Although 2788 was very tinytex related and this bug was more of a general knitr (w/o tiniytex, tinytex even being the potential workaround for it) issue that also somehow seemed to be heavily linked to the knit GUI element button itself ...

**Comment by fego1290** [comment]
I think so. If there is an issue, it seems to be related to knitr and not to RStudio.

**Comment by kevinushey** [comment]
My only other guess could be that some environment variables you have set in RStudio are causing this issue. (Maybe something set in the `PATH` that is interfering?)

**Comment by ClaudiusL** [comment]
I think what happened in the case of @fego1290 is the following: RStudio prior to 1.4.1717 had a bug and therefore did not use tinytex, even if the corresponding checkbox was ticked (see [here](https://community.rstudio.com/t/rnw-file-compile-pdf-button-fails-after-miktex-update/99482/5?u=claudiusl)). This is why an update of RStudio to the latest version solved the issue for fego1290, because now tinytex was actually used.

However, even with RStudio 1.4.1717, latest MiKTeX, knit 1.33 and R 4.1.0, compilation with the "Compile PDF" button still fails when not using the tinytex option.

**Comment by rcragun** [comment]
What more is needed to satisfy the “repro needed” tag? I get the same error on

- Windows 10 21H1
- R 4.1.1
- RStudio 1.4.1717
- knitr 1.34
- MikTeX 21.8
- pdfTeX 3.141592653-2.6-1.40.23 (although `pdftex --version` and `pdflatex --version` in the Windows terminal both return `MiKTeX-pdfTeX 4.8 (MiKTeX 21.8)`, and I have no idea what why that is different)

**Comment by gwd666** [comment]
> What more is needed to satisfy the “repro needed” tag?

@rcragun current workaround is to avoid the "Compile PDF" button in RStudio and `knit::knit2pdf("path/to/file")  from the Console

**Comment by gwd999** [comment]
any progress here?

**Comment by dbrookswr** [comment]
I changed to tinytex. I had not want to use this because its selling point,
that it is tiny, was off putting since it suggests what you want to do a
lot things you'll have to go through the hassle of downloading
individually. But you can still just download a lot at the start. It is a
very poor strategy, imo, to get it to be used unless it is just for a class
where students don't need to worry much about the formatting.

**Comment by VincenzoCarabetta** [comment]
Hi. 
I have to produce a pdf file from a Sweave file. I would like to know if there is an alternative to the "Compile pdf" button that allows compiling with xelatex. Thanks

**Comment by BorjaRuizReverter** [comment]
I confirm that I run into this same error!

I am using the last version of R, RStudio and MiKTeX on Windows10. 

After hours and hours of testing and breaking my mind I think that I've found the solution to this issue!

Initially, I though that the problem was exclusive from Windows and related to the blank spaces in the paths (like C:\Program Files\R\...), but not. In fact, I installed everything in another computer with Windows11 in no-blank-space paths (like C:\Apps\R\...) and the issue persisted. 

I thought then that the problem might be in Sweave, but the R compiler worked well in sweaving from Rnw to tex. 

There were no other possibility but in the process of building from tex to pdf. And for that, compiling with TinyTex, as @ClaudiusL recommended helped a lot, because it points to where the compilation stops.

So, the issue arises from packages that are needed (to compile the pdf from the tex file), but are not pre-installed in MiKTeX. In fact, the compilation inmediately stops here in the tex file:
```latex
\usepackage{Sweave}
```
, which TinyTex points to the sweave.sty file (which by the way belongs to R, so please add this path C:\Program Files\R\R-4.1.3\share\texmf in the MiKTeK Console). A quick look at this sweave.sty file shows that some packages like this:
```latex
\RequirePackage{ifthen}
```
or this other:
```latex
\RequirePackage{graphicx, fancyvrb, textcomp}
```
might or might be not pre-installed in MiKTeK. 

So, if you install all these packages one by one the compilation might succeed. However, it is very likely that your pdf is not built  yet because other sty files, with their respective packages, are also needed. In fact, during my compilation, the epstopdf-base.sty file was called, which required the infwarerr package, that is not pre-installed in MiKTeX, the grfext.sty file was also called, which required the kvdefinekeys package, that is not pre-installed either and so on.

It is a pain in the ...., but if you manage to install all the required packages you could finally get your pdf compiled. 

As I final comment, I came back to Sweave these days after some years off, when I used to use in my former laptop on Windows 7, and I did not remember to run into these issues. I think that something has changed in the Latex package bundler from MiKTeX. I miss some package manager that looks for all the packages needed and its dependencies as it is in Linux. 

Hard times for Window's developers and data scientists 😅

**Comment by ClaudiusL** [comment]
@BorjaRuizReverter Thanks for sharing your research. Am I right to assume that you're using Sweave (instead of knitr)? Your `\usepackage{Sweave}` makes me think so.

Regarding LaTeX package dependencies: If you run pdflatex on a TEX file with packages missing on your system, MiKTeX should automatically install the missing packages _and their dependencies_ (unless you chose ["Never install missing packages on-the-fly"](https://miktex.org/howto/miktex-console)).

Therefore, following your suggestion that the issue might be due to missing packages (which for some reason might not be installed on-the-fly when pdflatex is invoked by RStudio), I tried the following: 

1. Use "Compile PDF" from within RStudio (which crashes with the well-known exit code).
2. Manually run pdflatex on the TEX file generated in step 1. 

I was hoping that step 2 might find (and install) any missing packages, solving the underlying problem. However, no luck in my case: All packages are already installed and the TEX file compiles just fine (which basically just confirms [this](https://github.com/rstudio/rstudio/issues/9019#issuecomment-805600653)).


So to summarize, I think there's still no progress on this issue and we need to stick to the tinytex workaround?

**Comment by ciernyd** [comment]
hi guys, maybe this will help someone who is facing this:
You can now run (pdf)latex on 'test_miktex_sweave.tex'
Running pdflatex.exe on test_miktex_sweave.tex...failed
Error running C:/Users/USER/AppData/Local/Programs/MiKTeX/miktex/bin/x64/pdflatex.exe (exit code -1073740791)

After spending on this a lot of hours, trying all the possible solutions and combinations of it, this is what worked for me:
1. complete uninstall of everything R and Miktex related (incl registry and AppData entries etc..)
2. clean install of below shown versions of required software (old R studio, old R, old Rtools, newest MikTex)
3. do not upgrade MikTex!
4. after initial of pdf export, install only packages that pop up during the export process.
5. after that it works

versions of soft:
![image](https://user-images.githubusercontent.com/24621562/219649123-7c9916a9-83c7-4070-b554-78a199278fb3.png)

**Comment by gwd666** [comment]
@ciernyd -have you also tested the (workaround mentioned above) which is avoiding the RStudio Knit button and running the `knitr::knit2pdf("path/to/file")` command in the R-Console? just curious if that failed for you?

**Comment by ciernyd** [comment]
> 

hi, not really, the users know only one way how to do it and knitting would mean stepping out of their comfort zone:))

**Comment by gwd666** [comment]
> > 
> 
> hi, not really, the users know only one way how to do it and knitting would mean stepping out of their comfort zone:))

np - thnx for the info

**Comment by grainnhogg** [comment]
Hello,
I am unable to compile `.tex` or `.rnw` files in RStudio using either the 'Compile PDF' button or by `knitr::knit2PDF`.
I'm using Windows 10 Enterprise 19045.2965, and I just uninstalled and reinstalled the following:
- MiKTeX 23.4
- R 4.3.0
- RStudio 2023.03.1+446 

Also, my current RStudio Global Sweave Options are as follow: 

```
Weave Rnw files using: knitr
Typeset LaTeX into PDF using: pdfLaTeX
Use tinytex when compiling .tex files 
Clean auxiliary output after compile 
```

My file (`stuff.rnw`) is as follows:

```
\documentclass{article}
\begin{document}
stuff
\end{document}
```

When I hit 'Compile PDF' in RStudio, I get the following error:
```
processing file: stuff.Rnw
                                                                                                                                                                       
output file: stuff.tex

! Sorry, but C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe did not succeed.

! The log file hopefully contains the information to get MiKTeX going again:

!   C:\Users\GeorgeGaines\AppData\Local\MiKTeX\miktex\log\pdflatex.log

Error: LaTeX failed to compile stuff.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See stuff.log for more info.
```

Furthermore, when I run the following function
```
knit2sumatra <- function(input) {
  # "input" should be the filename WITHOUT extension
  knitr::knit2pdf(paste0(input, ".Rnw"))
  system2(
    "C:/Program Files/Rstudio/resources/app/bin/sumatra/SumatraPDF.exe",
    args = paste0(input, ".pdf"),
    wait = FALSE,
    invisible = FALSE
  )
}
```
on `stuff.rnw`, I get the exact same error. This is the log output

```
2023-05-23 08:36:29,110-0600 INFO  pdflatex - this process (5104) started by Rterm in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Desktop/stuff.tex
2023-05-23 08:36:29,111-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 08:36:29,116-0600 INFO  pdflatex - running One MiKTeX Utility to refresh the file name database
2023-05-23 08:36:29,116-0600 INFO  pdflatex.core - start process: miktex --quiet fndb refresh
2023-05-23 08:36:32,819-0600 INFO  pdflatex - running One MiKTeX Utility to create font map files
2023-05-23 08:36:32,819-0600 INFO  pdflatex.core - start process: miktex --quiet fontmaps configure
2023-05-23 08:36:37,152-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 08:36:37,169-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 08:36:37,207-0600 INFO  pdflatex - going to create file: pdflatex.fmt
2023-05-23 08:36:37,207-0600 INFO  pdflatex.core - start process: miktex formats build pdflatex --engine pdftex
2023-05-23 08:36:45,421-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 08:36:45,421-0600 FATAL pdflatex.core - Data: 
2023-05-23 08:36:45,421-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 08:36:45,423-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 08:36:45,423-0600 FATAL pdflatex - Info: 
2023-05-23 08:36:45,423-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 08:36:45,423-0600 FATAL pdflatex - Line: 126
2023-05-23 08:36:45,426-0600 INFO  pdflatex - this process (5104) finishes with exit code 1
2023-05-23 08:36:45,427-0600 WARN  pdflatex.core - still open: C:/Users/myname/Desktop/stuff.tex
2023-05-23 08:36:45,428-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 08:36:54,362-0600 INFO  pdflatex - this process (7588) started by Rterm in directory C:\Users\myname\Documents\collaboration\umd_gedi with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Documents/collaboration/umd_gedi/gedi_ms_comments_20230417.tex
2023-05-23 08:36:54,362-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 08:36:54,365-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 08:36:54,369-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 08:36:54,522-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 08:36:54,522-0600 FATAL pdflatex.core - Data: 
2023-05-23 08:36:54,522-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 08:36:54,522-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 08:36:54,523-0600 FATAL pdflatex - Info: 
2023-05-23 08:36:54,523-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 08:36:54,523-0600 FATAL pdflatex - Line: 126
2023-05-23 08:36:54,525-0600 INFO  pdflatex - this process (7588) finishes with exit code 1
2023-05-23 08:36:54,526-0600 WARN  pdflatex.core - still open: gedi_ms_comments_20230417.log
2023-05-23 08:36:54,526-0600 WARN  pdflatex.core - still open: C:/Users/myname/Documents/collaboration/umd_gedi/gedi_ms_comments_20230417.tex
2023-05-23 08:37:35,575-0600 INFO  pdflatex - this process (17284) started by Rterm in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Desktop/stuff.tex
2023-05-23 08:37:35,576-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 08:37:35,587-0600 WARN  pdflatex - security risk: running with elevated privileges
2023-05-23 08:37:35,587-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 08:37:35,587-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 08:37:35,731-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 08:37:35,731-0600 FATAL pdflatex.core - Data: 
2023-05-23 08:37:35,731-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 08:37:35,731-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 08:37:35,731-0600 FATAL pdflatex - Info: 
2023-05-23 08:37:35,731-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 08:37:35,731-0600 FATAL pdflatex - Line: 126
2023-05-23 08:37:35,731-0600 INFO  pdflatex - this process (17284) finishes with exit code 1
2023-05-23 08:37:35,731-0600 WARN  pdflatex.core - still open: C:/Users/GeorgeGaines/Desktop/stuff.tex
2023-05-23 08:37:35,731-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 08:37:40,898-0600 INFO  pdflatex - this process (13660) started by Rterm in directory C:\Users\myname\Documents\collaboration\umd_gedi with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Documents/collaboration/umd_gedi/gedi_ms_comments_20230417.tex
2023-05-23 08:37:40,898-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 08:37:40,911-0600 WARN  pdflatex - security risk: running with elevated privileges
2023-05-23 08:37:40,912-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 08:37:40,916-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 08:37:41,041-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 08:37:41,041-0600 FATAL pdflatex.core - Data: 
2023-05-23 08:37:41,041-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 08:37:41,042-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 08:37:41,042-0600 FATAL pdflatex - Info: 
2023-05-23 08:37:41,042-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 08:37:41,042-0600 FATAL pdflatex - Line: 126
2023-05-23 08:37:41,042-0600 INFO  pdflatex - this process (13660) finishes with exit code 1
2023-05-23 08:37:41,044-0600 WARN  pdflatex.core - still open: C:/Users/myname/Documents/collaboration/umd_gedi/gedi_ms_comments_20230417.tex
2023-05-23 08:37:41,044-0600 WARN  pdflatex.core - still open: gedi_ms_comments_20230417.log
2023-05-23 08:40:46,779-0600 INFO  pdflatex - this process (15108) started by Rterm in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Desktop/stuff.tex
2023-05-23 08:40:46,779-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 08:40:46,791-0600 WARN  pdflatex - security risk: running with elevated privileges
2023-05-23 08:40:46,793-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 08:40:46,796-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 08:40:46,920-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 08:40:46,920-0600 FATAL pdflatex.core - Data: 
2023-05-23 08:40:46,920-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 08:40:46,920-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 08:40:46,920-0600 FATAL pdflatex - Info: 
2023-05-23 08:40:46,920-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 08:40:46,920-0600 FATAL pdflatex - Line: 126
2023-05-23 08:40:46,920-0600 INFO  pdflatex - this process (15108) finishes with exit code 1
2023-05-23 08:40:46,920-0600 WARN  pdflatex.core - still open: C:/Users/myname/Desktop/stuff.tex
2023-05-23 08:40:46,920-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 09:06:19,002-0600 INFO  pdflatex - this process (20932) started by Rterm in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Desktop/stuff.tex
2023-05-23 09:06:19,002-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:06:19,004-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:06:19,026-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:06:19,234-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 09:06:19,234-0600 FATAL pdflatex.core - Data: 
2023-05-23 09:06:19,236-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 09:06:19,236-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 09:06:19,236-0600 FATAL pdflatex - Info: 
2023-05-23 09:06:19,236-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 09:06:19,236-0600 FATAL pdflatex - Line: 126
2023-05-23 09:06:19,236-0600 INFO  pdflatex - this process (20932) finishes with exit code 1
2023-05-23 09:06:19,236-0600 WARN  pdflatex.core - still open: C:/Users/myname/Desktop/stuff.tex
2023-05-23 09:06:19,236-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 09:06:38,129-0600 INFO  pdflatex - this process (18532) started by rsession-utf8 in directory C:\Users\myname\Documents\projects\sae_simulation with command line: "C:/Program Files/MiKTeX/miktex/bin/x64/pdflatex.exe" --version
2023-05-23 09:06:38,129-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:06:38,133-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:06:38,137-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:06:38,151-0600 INFO  pdflatex - this process (18532) finishes with exit code 0
2023-05-23 09:08:17,380-0600 INFO  pdflatex - this process (22260) started by rsession-utf8 in directory C:\Users\myname\Documents\projects\sae_simulation with command line: "C:/Program Files/MiKTeX/miktex/bin/x64/pdflatex.exe" --version
2023-05-23 09:08:17,380-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:08:17,380-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:08:17,397-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:08:17,397-0600 INFO  pdflatex - this process (22260) finishes with exit code 0
2023-05-23 09:08:47,540-0600 INFO  pdflatex - this process (22472) started by rsession-utf8 in directory C:\Users\GeorgeGaines\Documents\projects\sae_simulation with command line: "C:/Program Files/MiKTeX/miktex/bin/x64/pdflatex.exe" --version
2023-05-23 09:08:47,540-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:08:47,542-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:08:47,546-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:08:47,559-0600 INFO  pdflatex - this process (22472) finishes with exit code 0
2023-05-23 09:17:33,478-0600 INFO  pdflatex - this process (19728) started by rsession-utf8 in directory C:\Users\GeorgeGaines\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode stuff.tex
2023-05-23 09:17:33,478-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:17:33,481-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:17:33,506-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:17:33,719-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 09:17:33,719-0600 FATAL pdflatex.core - Data: 
2023-05-23 09:17:33,719-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 09:17:33,719-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 09:17:33,719-0600 FATAL pdflatex - Info: 
2023-05-23 09:17:33,719-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 09:17:33,719-0600 FATAL pdflatex - Line: 126
2023-05-23 09:17:33,719-0600 INFO  pdflatex - this process (19728) finishes with exit code 1
2023-05-23 09:17:33,725-0600 WARN  pdflatex.core - still open: stuff.tex
2023-05-23 09:17:33,725-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 09:18:13,527-0600 INFO  pdflatex - this process (11328) started by rsession-utf8 in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode stuff.tex
2023-05-23 09:18:13,528-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:18:13,530-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:18:13,534-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:18:13,649-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 09:18:13,649-0600 FATAL pdflatex.core - Data: 
2023-05-23 09:18:13,649-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 09:18:13,649-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 09:18:13,649-0600 FATAL pdflatex - Info: 
2023-05-23 09:18:13,649-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 09:18:13,649-0600 FATAL pdflatex - Line: 126
2023-05-23 09:18:13,651-0600 INFO  pdflatex - this process (11328) finishes with exit code 1
2023-05-23 09:18:13,653-0600 WARN  pdflatex.core - still open: stuff.tex
2023-05-23 09:18:13,653-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 09:18:38,615-0600 INFO  pdflatex - this process (22388) started by rsession-utf8 in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode stuff.tex
2023-05-23 09:18:38,631-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:18:38,631-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:18:38,631-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:18:38,745-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 09:18:38,745-0600 FATAL pdflatex.core - Data: 
2023-05-23 09:18:38,745-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 09:18:38,745-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 09:18:38,745-0600 FATAL pdflatex - Info: 
2023-05-23 09:18:38,745-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 09:18:38,745-0600 FATAL pdflatex - Line: 126
2023-05-23 09:18:38,748-0600 INFO  pdflatex - this process (22388) finishes with exit code 1
2023-05-23 09:18:38,749-0600 WARN  pdflatex.core - still open: stuff.tex
2023-05-23 09:18:38,749-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 09:21:09,879-0600 INFO  pdflatex - this process (5444) started by rsession-utf8 in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode stuff.tex
2023-05-23 09:21:09,879-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:21:09,879-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:21:09,887-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:21:10,000-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 09:21:10,000-0600 FATAL pdflatex.core - Data: 
2023-05-23 09:21:10,000-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 09:21:10,000-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 09:21:10,000-0600 FATAL pdflatex - Info: 
2023-05-23 09:21:10,000-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 09:21:10,000-0600 FATAL pdflatex - Line: 126
2023-05-23 09:21:10,000-0600 INFO  pdflatex - this process (5444) finishes with exit code 1
2023-05-23 09:21:10,000-0600 WARN  pdflatex.core - still open: stuff.tex
2023-05-23 09:21:10,000-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 09:37:56,065-0600 INFO  pdflatex - this process (21068) started by rsession-utf8 in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode stuff.tex
2023-05-23 09:37:56,065-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 09:37:56,065-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 09:37:56,097-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 09:37:56,277-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 09:37:56,277-0600 FATAL pdflatex.core - Data: 
2023-05-23 09:37:56,278-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 09:37:56,278-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 09:37:56,278-0600 FATAL pdflatex - Info: 
2023-05-23 09:37:56,278-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 09:37:56,278-0600 FATAL pdflatex - Line: 126
2023-05-23 09:37:56,280-0600 INFO  pdflatex - this process (21068) finishes with exit code 1
2023-05-23 09:37:56,282-0600 WARN  pdflatex.core - still open: stuff.tex
2023-05-23 09:37:56,282-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 10:26:55,484-0600 INFO  pdflatex - this process (18256) started by Rterm in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode C:/Users/myname/Desktop/stuff.tex
2023-05-23 10:26:55,484-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 10:26:55,486-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 10:26:55,511-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 10:26:55,719-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 10:26:55,719-0600 FATAL pdflatex.core - Data: 
2023-05-23 10:26:55,720-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 10:26:55,720-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 10:26:55,720-0600 FATAL pdflatex - Info: 
2023-05-23 10:26:55,720-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 10:26:55,720-0600 FATAL pdflatex - Line: 126
2023-05-23 10:26:55,722-0600 INFO  pdflatex - this process (18256) finishes with exit code 1
2023-05-23 10:26:55,724-0600 WARN  pdflatex.core - still open: C:/Users/myname/Desktop/stuff.tex
2023-05-23 10:26:55,724-0600 WARN  pdflatex.core - still open: stuff.log
2023-05-23 10:30:40,310-0600 INFO  pdflatex - this process (3808) started by rsession-utf8 in directory C:\Users\myname\Desktop with command line: C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode stuff.tex
2023-05-23 10:30:40,310-0600 INFO  pdflatex - running on Windows 10.0.19045
2023-05-23 10:30:40,313-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.15.0 (1.40.25) (MiKTeX 23.5)
2023-05-23 10:30:40,317-0600 INFO  pdflatex - allowing known shell commands
2023-05-23 10:30:40,439-0600 FATAL pdflatex.core - GUI framework cannot be initialized.
2023-05-23 10:30:40,439-0600 FATAL pdflatex.core - Data: 
2023-05-23 10:30:40,439-0600 FATAL pdflatex.core - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp:126
2023-05-23 10:30:40,439-0600 FATAL pdflatex - GUI framework cannot be initialized.
2023-05-23 10:30:40,440-0600 FATAL pdflatex - Info: 
2023-05-23 10:30:40,440-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2023-05-23 10:30:40,440-0600 FATAL pdflatex - Line: 126
2023-05-23 10:30:40,442-0600 INFO  pdflatex - this process (3808) finishes with exit code 1
2023-05-23 10:30:40,443-0600 WARN  pdflatex.core - still open: stuff.tex
2023-05-23 10:30:40,443-0600 WARN  pdflatex.core - still open: stuff.log
```

The path to my MiKTeX executables, i.e. `C:\Program Files\MiKTeX\miktex\bin\x64\` is in my environment variable list. 

Finally, I don't have admin access to my own computer, so have to call an IT help desk everytime I want to try anything that requires elevated privelages. 

I've read extensively through recommended solutions for related problems, and cannot figure this out. Any suggestions? Thank you for considering.

**Comment by otago-palch04p** [comment]
I still get the same error (with exit  code -1073740791) when trying to compile a Sweave .Rnw file (generated from File->New File->R Sweave) into a PDF document. This is using RStudio 2024.04.0+735, R 4.4.0, and a freshly updated MiKTeX install on Windows 11 (22H2 22621.3447).

**Comment by SebastienGrall** [comment]
@otago-palch04p Have you tried tinytex? I had some problems at the beginning but it's working fine actually.

**Comment by grainnhogg** [comment]
I also moved to tinytex. I can now compile to pdf with the "Compile PDF"
button in Rstudio. I have absolutely no idea why, and don't really care.
