### ISSUE TITLE
Real time spell-checking stops working in source mode after several switches between editor modes

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9074]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1106, 1.4.1606, 1.4.1620
    OS Version      : MacOS 11.3, SLES 15 SP2 (using Safari), Red Hat 8.3 (using Firefox)
    R Version       : 4.0.4

### Steps to reproduce the problem

With real time spell-checking turned on:
1. Open an R Markdown file.
2. Switch to visual mode (if not already in it).
3. In a content area, type `hellllo`.
    - `hellllo` is underlined, identified as misspelled.
4. Save the document.
5. Switch to source mode.
    - Wait briefly.
    - `hellllo` should be underlined, identified as misspelled.
6. Switch back and forth between visual and source modes.
    - Visual mode: `hellllo` is underlined, identified as misspelled.
    - Source mode: Eventually, `hellllo` will not get underlined, as if it's spelled correctly.
7. In source mode, add a space somewhere in the doc.
    - Wait briefly.
    - `hellllo` should be underlined, identified as misspelled.

### Describe the problem in detail

Real time spell-checking works initially, but if switching back and forth between visual and source modes, misspelled words are no longer underlined in source mode. 

Note: See #8473 which was a slightly different issue in visual mode. Also note that this issue is present in 1.4 Wax Begonia and 1.4 Juliet Rose (post-fix).

### Describe the behavior you expected

Misspelled words should continue to be identified in real time when switching back-and-forth between visual and source modes.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by adamconroy** [comment]
This should be addressed in #9161 but possible it isn't. I wasn't able to repro after the changes.

**Comment by ronblum** [comment]
@adamconroy This still occurs in
- RStudio Server 1.4.1681 (056e606a)
- with R 4.0.5
- on Ubuntu 20.04
- via Chrome on MacOS 11.3

**Comment by adamconroy** [comment]
Ok I think I misunderstood this a little bit. My original reading of it was that it eventually fully breaks, if it just works again after typing triggers it this is pretty minor to me (and also I think I could fix this trivially). I'll spend a few minutes looking into it and seeing if I can trigger the linter all the time after switching from Visual back to Source.

**Comment by ronblum** [comment]
Confirmed fixed, in
- RStudio Desktop on MacOS 11.3
- RStudio Server on Red Hat 8.3 via Firefox on MacOS 11.3
- RStudio Server on SLES 15 SP2 via Chrome on MacOS 11.3
