### ISSUE TITLE
RStudio 1.4.1717 still won't run with R-4.1.0-arm64.pkg

### ISSUE THREAD

**Issue by greglum** [rstudio/rstudio#9543]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      :  macOS Big Sur 11.4
    R Version       : 4.1 (arm)

### Steps to reproduce the problem

- Install the R-4.1.0-arm64.pkg (and ensure it is your only version of R on the system)
- R will run fine on the system
- Install RStudio (1.4.1717) and ensure Rosetta 2 is properly installed ( /usr/sbin/softwareupdate --install-rosetta )
- RStudio will fail with the output 

```
dyld: could not load inserted library
'/Library/Frameworks/R.framework/Resources/lib/libR.dylib'
because no suitable image found. Did find:
/Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
/Library/Frameworks/R.framework/Resources/lib/libR.dylib: stat() failed with errno=1
```

### Describe the problem in detail

Hello, with the release notes of RStudio 1.4.1717 it is supposed to run natively with the R arm packages (with RStudio still running via Rosetta 2,  of course). However, I could not get it to work; in order to still run RStudio, I had to uninstall the R arm pkg and replace it with the Intel version, similar to this [thread here](https://community.rstudio.com/t/rstudio-does-not-start-up-with-r-4-1-0-on-macbook-pro-m1-macos-big-sur-11-3-1/105533/3). I have reproduced this off of a fresh OS install as well as multiple resets of RStudio's Desktop State. After running multiple diagnostics, I have isolated it to an RStudio issue as the  R-4.1.0-arm64.pkg would run successfully on my system. 

### Describe the behavior you expected

Would expect RStudio (1.4.1717) to run via Rosetta 2 with only the R(4.1) arm pkg installed on the system.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Edit: formatting

**Comment by ronblum** [comment]
@Marcusory Thank you for raising this! I'm marking it for triage as part of our development process.

**Comment by Marcusory** [comment]
Appreciate all that you do! 

Also, please keep in mind you have to download the arm pkg directly; installing R 4.1 stable through Homebrew will _not_ reproduce this issue.

**Comment by astayleraz** [comment]
@kevinushey I was not able to reproduce this on my M1 mac with that version of R installed. Do you have any other ideas or suggestions for this?

**Comment by Marcusory** [comment]
@astayleraz @kevinushey  Hmmmm. Did you ensure that the arm pkg installed directly[ from here ](https://cran.r-project.org/bin/macosx/) is the only version of R present on the system? 

RStudio will run for me if I have installed the intel R pkg from there or R via homebrew (even with the arm pkg present on the system as well), but on two fresh M1 Big Sur systems I've had this issue when the only R version installed is the arm pkg directly from https://cran.r-project.org/bin/macosx/. 

Did you try it in a VM? If so, I'm at a loss. I was thinking it was user error for some reason on my end, but once I was able to reproduce it myself on the fresh system I was stumped.

**Comment by kevinushey** [comment]
Thus far, we haven't been able to reproduce internally but this has been reported by one other user before:

https://github.com/rstudio/rstudio/issues/9396

Just to double-check, how are you launching RStudio on your system? Via the macOS Spotlight? Finder? Something else?

**Comment by Marcusory** [comment]
> #9396

Could be related, although my issue arises specifically when using the arm pkg from CRAN, not via homebrew. As discussed in that issue, may just be environment specific, but as it has occurred on a fresh OS install, I really wouldn't know what the parameters would be to reproduce it. 

I had attempted to launch RStudio both through Spotlight as well as through Finder > Applications. Same outcome.

**Comment by Marcusory** [comment]
As I've been using an adequate workaround and no one else seems to be able to reproduce the issue, I'll just close this for now. 

Feel free to re-open it if you'd like. I will circle back to it in the future if it persists on another fresh system (I tend to only interact with one every few months, so would not be for at least a few weeks. I can try to reproduce it again sooner if desired).

**Comment by Holer90** [comment]
> Update. I fixed this issue by moving/Applications/RStudio.app/Contents/MacOS/rsession to rsession-x86 and defining a symbolic link: ln -s rsession-arm64 rsession.

Thank you - I had this exact issue, and this fixed it! I did run in to an "app is damaged and cannot be opened" error message, which I fixed with `xattr`.

The entire fix was as follows:
```bash
cd /Applications/Rstudio.app/Contents/MacOS
mv rsession rsession-x86
ln -s rsession-arm64 rsession
# Open RStudio and if it fails then run this:
xattr -r -d com.apple.quarantine /Applications/RStudio.app
```

**Comment by kevinushey** [comment]
Re-opening as a number of users are still encountering this, and we really shouldn't require users modify the installed copy of RStudio to resolve this.

The only certain thing I've seen thus far is that users in this state will see something like:

```
> system("uname -m")
x86_64
```

even if they're running with an arm64 build of R, and I can't figure out why this is happening. (Note that with the above patch, users will still likely see issues when attempting to install packages from sources.)

**Comment by ukyoi** [comment]
> Re-opening as a number of users are still encountering this, and we really shouldn't require users modify the installed copy of RStudio to resolve this.
> 
> The only certain thing I've seen thus far is that users in this state will see something like:
> 
> ```
> > Sys.info()[["machine"]]
> [1] "arm64"
> > system("uname -m")
> x86_64
> ```
> 
> even if they're running with an arm64 build of R, and I can't figure out why this is happening. (Note that with the above patch, users will still likely see issues when attempting to install packages from sources.)

I have the same issue here and I found this behaviour happens in coreutils for x86-64 installed by homebrew. I installed coreutils on an x86 machine and migrated whole homebrew environment and profiles to my new MacBook. Then when I run `uname`, it actually uses `/usr/local/opt/coreutils/libexec/gnubin/uname`, thus gives the results of x86-64.

**Comment by Holer90** [comment]
I had this issue (again) after installing both `R` (formulae-version) and `RStudio` with `brew`. 

I have found no way to make neither the `rstudio` cask nor the `rstudio-preview` cask to work. But installing the most recent daily build (RStudio-2022.06.0-daily-435.dmg) solved the issue. 

Running `system("uname -m")` now returns `arm64`.

The daily builds can be found here: https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/

As a side note, this daily build also does not require editing the `RStudio.app`-file.

**Comment by ukyoi** [comment]
> Edit: This worked it for me:
> 
> ```
> brew install --cask rstudio-daily
> ```
> 
> I had this issue (again) after installing both `R` (formulae-version) and `RStudio` with `brew`.
> 
> I have found no way to make neither the `rstudio` cask nor the `rstudio-preview` cask to work. But installing the most recent daily build (RStudio-2022.06.0-daily-435.dmg) solved the issue.
> 
> Running `system("uname -m")` now returns `arm64`.
> 
> The daily builds can be found here: https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/
> 
> As a side note, this daily build also does not require editing the `RStudio.app`-file.

AFAIK, RStudio-Electron (as a unified application) handles architectures correctly.

**Comment by ronblum** [comment]
Switching to @Trevor-Reid as he has access to an M1 ARM machine.

**Comment by Trevor-Reid** [comment]
@kevinushey do you know of anyway to reliably reproduce the issue? I wasn't able to on my machine, but I had to uninstall previous versions of R and RStudio to install the arm64-R and RStudio 1.4. Is it reproducible only in clean macOS environments?

**Comment by kevinushey** [comment]
Unfortunately I don't know what it takes to reproduce this issue. 😞

**Comment by ronblum** [comment]
@greglum or anyone else who's experienced the problem: Would you be willing to try out [the latest preview build of Spotted Wakerobin](https://www.rstudio.com/products/rstudio/download/preview/) to see if this is fixed? We're unable to consistently reproduce the problem independently, so we can't confirm the fix. I appreciate the help!

**Comment by bunnell** [comment]
FWIW, I just installed 2022.02.3 Build 492 and confirmed that the problem was still present in that version, then installed 2022.07.0 Build 543 and confirmed that the problem was fixed in that version.

**Comment by dfalty** [comment]
Thanks @bunnell and @greglum! I'm going to close the issue but @greglum (or anyone else) please comment on it if you run into any problems.

**Comment by icps86** [comment]
Hello, I am having the same problem. I got a new MacBook Pro and after installing latest R (4.2.2 arm64) and RStudio (1.4.1106) I get a similar error when booting RStudio. I am bit lost, is the solution found yet? Thanks!

----------------------
This is the error:

Error Starting R
The R session failed to start.

ERROR MESSAGE
[No error available]

PROCESS OUTPUT
The R session process exited with code 6.

ERRORS
dyld[1615]: terminating because inserted dylib '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' could not be loaded: tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/icps86/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache), '/libR.dylib' (no such file), '/libR.dylib' (no such file), '/lib/libR.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/icps86/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache), '/libR.dylib' (no such file), '/libR.dylib' (no such file), '/lib/libR.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libR.dylib' (no such file)
dyld[1615]: tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/icps86/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache), '/libR.dylib' (no such file), '/libR.dylib' (no such file), '/lib/libR.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/icps86/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache), '/libR.dylib' (no such file), '/libR.dylib' (no such file), '/lib/libR.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libR.dylib' (no such file)

OUTPUT
[No output emitted]

RECENT LOG
Log File
[No logs available]

**Comment by ML33M** [comment]
@bunnell @greglum thank you for the fix and I have the exact issue. Except everything works in terminal but the last line
> xattr -r -d com.apple.quarantine /Applications/RStudio.app

I did run

    cd /Applications/Rstudio.app/Contents/MacOS
    mv rsession rsession-x86
    ln -s rsession-arm64 rsession
The open R studio, and it complains it cannot find R
<img width="1094" alt="1eae38718b2a1e46e99df3c99b0a3471" src="https://user-images.githubusercontent.com/44594887/214731994-4b0d2373-1b9a-4457-93e9-dff73da28249.png">

Then I tried in terminal to run xattr -r -d com.apple.quarantine /Applications/RStudio.app
How can I fix this?

<img width="850" alt="a1255f1fac3a589675c31f9ec3fa764a" src="https://user-images.githubusercontent.com/44594887/214732364-a1c04da5-fc90-4362-befa-402359fe2eb6.png">

**Comment by gnick18** [comment]
I am having an identical issue to @ML33M . Even after running the suggested terminal manual fix, I got the same error message when opening R-Studio (can't connect to R), and the same error message when running xattr. However, I'm aware that my version of Mac is different than that of the original support ticket, so this may be a different issue with the new Mac OS. I'll add, my first error message was the same as the original ticket _i.e.,_
```
dyld: could not load inserted library
'/Library/Frameworks/R.framework/Resources/lib/libR.dylib'
```

**Device details:**
OS Version: 13.2.1
R-studio version: 1.4.1106
R-Version: 4.2.2
Platform: aarch64-apple-darwin20 (64-bit)
Chip: Apple M2 Max

**Comment by Huii678** [comment]
I encountered the same situation as @gnick18 and @ML33M this morning. Then I tried another version of RStudio downloads at this link https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/, then the problem was gone. I still need to figure out the exact problem, but I can use RStudio now.
