### ISSUE TITLE
Stop RStudio always opening source viewer when in debug mode when evaluating R code

### ISSUE THREAD

**Issue by jeromyanglim** [rstudio/rstudio#9943]
I posted [this question on StackOverview](https://stackoverflow.com/q/69534050/180892), but it was suggested that this might be a better forum: 

I often code functions in the following way  by creating a basic function, entering debug mode, and then writing the function in debugmode. E.g., 

    myfun <- function(x) print(x)
    debugonce(myfun)
    myfun("test")

The benefits of this is that I can get real time feedback on whether my code is working with the arguments passed to it.

However RStudio appears to have recently changed its behaviour to make this more difficult. I recently upgraded to 2021.09.0 Build 351.

Previously, it would open the Source Editor when you call this command. 
[![rstudio debug viewer][1]][1]

But if you closed this screen, you could return to your code, edit the code, evaluate code, and so on without the viewer reappearing.
However, now it seems to reappear every time you evaluate your code. 
For instance, if I close the viewer, go back to my main script, and evaluate `x`, the Viewer opens back up.
This is super annoying for someone used to editing and evaluating code while in debugmode using the source script file.

Is there any way of entirely disabling the Source Editor view in Rstudio? Or alternatively, is there a way of being able to edit and evaluate code without the Source Editor constantly re-appearing in Rstudio (like how it used to work)?

Or to phrase as a feature request:

* Could you restore the previous functionality where the Debug Viewer only opens up once when in debug mode but not on subsequent calls or alternatively could there be a preference to disable the Debug Viewer either completely or only on first call.

My current fix is to downgrade to [Version 1.3.1093](https://www.rstudio.com/products/rstudio/older-versions/), where you could edit and evaluate code without the Viewer constantly re-appearing. But it would be a shame to miss out on future upgrades.

  [1]: https://i.stack.imgur.com/58oId.png

**Comment by jmcphers** [comment]
I think you might be seeing https://github.com/rstudio/rstudio/issues/9918, which was fixed very recently (just last week). Do you observe the same problem in the daily builds?

https://dailies.rstudio.com/

**Comment by jeromyanglim** [comment]
@jmcphers Fantastic! Yep. Installing the daily build fixed the issue.

**Comment by slipkid90515** [comment]
Just got a new computer and got RStudio up and running and I am experiencing the same thing. Is there an updated way to resolve this?

**Comment by kevinushey** [comment]
This should already be resolved in the latest release of RStudio (2022.02.1). If you're still having trouble, please file a new issue with more details.

**Comment by KasperThystrup** [comment]
This is not fixed!

Whenever I enter debug mode and edit a function, I'm redirected to a source view window (Away from the actual source code). This occurs at least twice per debug action / new step. So it is quite limitting. I don't know whether it's related to the browser() or trace(xxx, browser) functions, but these are my main tools for debugging...

 Rstudio: 2023.06.2 Build 561 R: 4.3.1

**Comment by kevinushey** [comment]
> This behavoir is not fixed!

> Rstudio: 2023.06.2 Build 561 R: 4.3.1

Why would you make this assertion without actually testing with the latest release of RStudio, or (ideally) a recent daily build as available from https://dailies.rstudio.com/rstudio/kousa-dogwood/?

**Comment by KasperThystrup** [comment]
> Why would you make this assertion without actually testing with the latest release of RStudio, or (ideally) a recent daily build as available from https://dailies.rstudio.com/rstudio/kousa-dogwood/?

You are right. I had had the issue for a long time, I seached for the wrong thing on Github (and other places), and I even oversaw the fixing issue... So I made the mistake of presuming.. Sorry! :-(

To prevent confusion I will remove above message, but keep this for shame :-P

**Comment by kevinushey** [comment]
No worries; I appreciate your taking the time to report + test the latest builds. Sorry for the breakage in the mean time!
